### ISSUE TITLE
m.data.toString() results in a weird message when long

### ISSUE THREAD

**Issue by markwylde** [nats-io/nats.js#102]
### Observed behavior

When using `m.data.toString()` I receive a different result to using `m.string()` when the payload is larger than a few kb.

### Expected behavior

They should return the same data.

### Server and client version

nats-server: v2.10.18

node v22.11.0
    "@nats-io/jetstream": "^3.0.0-18",
    "@nats-io/transport-node": "^3.0.0-12",

### Host environment

mac os, using docker

### Steps to reproduce

With a brand new node v22 project, here is the following code to reproduce the error:

```js
import { connect } from "@nats-io/transport-node";
import { jetstream, jetstreamManager } from "@nats-io/jetstream";

// Connect to the NATS server
const nc = await connect(["localhost:4442", "localhost:4443"]);

// Create a JetStream context
const js = jetstream(nc);
const jsm = await jetstreamManager(nc);

// Flush the stream
await jsm.streams.purge("a");

// Create a stream
await jsm.streams.add({ name: "a", subjects: ["a.*"] });

// Publish a messages
const payload = JSON.stringify({
  // Note 100 elements works fine
  // 10000 breaks (this may depend on your resources)
  hello: Array(10000).fill('').map((_, i) => i),
  from: Date.now()
});

// log bytes of payload
console.log('payload bytes', Buffer.byteLength(payload));

// Publish the event
await js.publish("a.b", payload);

// Consume messages
const oc = await js.consumers.get('a');
const messages = await oc.consume();

for await (const m of messages) {

  // this is the full message data and will parse correctly
  console.log(JSON.parse(m.string()));

  // this is not the correct message data and will throw
  console.log(JSON.parse(m.data.toString()));

  m.ack();
}
```

Notes:
- Changing the array to 100 items seems to deliver the correct payload

**Comment by aricart** [comment]
The api call is `msg.string()` - not `toString()`

**Comment by aricart** [comment]
and if you are doing `msg.data.toString()` that is just simply invoking the `toString()` on the uint - if you want to get the message payload as a string `msg.string()` as json `msg.json()`
