### ISSUE TITLE
Incorrect typing for connect in transport-node

### ISSUE THREAD

**Issue by markwylde** [nats-io/nats.js#103]
### Observed behavior

The following code is type compliant:

```ts
import { connect } from "@nats-io/transport-node";

// Connect to the NATS server
const options = {
  servers: ["localhost:4442", "localhost:4443"]
}
const nc = await connect(options);
```

There are no typescript errors, however when runm the code fails:

```
tsx main.ts
/natsbug/node_modules/@nats-io/transport-node/lib/node_transport.js:84
                ? nats_base_client_1.NatsError.errorForCode(nats_base_client_1.ErrorCode.ConnectionRefused, err)
                                               ^

TypeError: Cannot read properties of undefined (reading 'errorForCode')
    at NodeTransport.connect (/natsbug/node_modules/@nats-io/transport-node/src/node_transport.ts:104:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ProtocolHandler.dial (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:524:7)
    at async ProtocolHandler._doDial (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:576:9)
    at async ProtocolHandler.dodialLoop (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:628:11)

Node.js v22.11.0
```

However, passing an array of servers is both type compliant and works as expected:

```ts
import { connect } from "@nats-io/transport-node";

// Connect to the NATS server
const options = {
  servers: ["localhost:4442", "localhost:4443"]
}
const nc = await connect(options.servers);
```

### Expected behavior

I would expect, from looking at the type signature that connect accepts a ConnectionOptions, being an object with servers, which contains an array.

```
(alias) connect(opts?: ConnectionOptions | undefined): Promise<NatsConnection>
import connect
```

### Server and client version

Node: v22.11.0

"@nats-io/transport-node": "^3.0.0-12"

**Comment by aricart** [comment]
looks like you have libs that are no in-sync - there are current test versions that removed NatsError, but they should be in sync.... Can you list your transport-node, and core versions?

**Comment by markwylde** [comment]
Hey @aricart 

I've only installed `@nats-io/transport-node` at version `^3.0.0-12`.

Here is my package.json

```json
{
  "name": "natsbug",
  "version": "1.0.0",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@nats-io/transport-node": "^3.0.0-12"
  }
}
```

However, as a dependency, it has installed core.


```
markwylde@Marks-MacBook-Pro natsbug % npm ls @nats-io/transport-node
natsbug@1.0.0 /natsbug
└── @nats-io/transport-node@3.0.0-12

markwylde@Marks-MacBook-Pro natsbug % npm ls @nats-io/nats-core
natsbug@1.0.0 /natsbug
└─┬ @nats-io/transport-node@3.0.0-12
  └── @nats-io/nats-core@3.0.0-31
```

**Comment by aricart** [comment]
yes they are out of sync - the current constraint is not strong enough for the current changes.
I would do:
```
npm uninstall @nats-io/transport-node
npm install @nats-io/transport-node
```

That should leave a tree that looks like:
```
> npm ls -a
t@1.0.0 /private/tmp/t
└─┬ @nats-io/transport-node@3.0.0-12
  ├─┬ @nats-io/nats-core@3.0.0-31
  │ ├── @nats-io/nkeys@1.2.0-7 deduped
  │ └── @nats-io/nuid@2.0.1-2 deduped
  ├─┬ @nats-io/nkeys@1.2.0-7
  │ └── tweetnacl@1.0.3
  └── @nats-io/nuid@2.0.1-2
```

**Comment by aricart** [comment]
also note that this set of libs is NOT yet released, but appreciate you trying it!

**Comment by aricart** [comment]
I will release exact match for versions

**Comment by markwylde** [comment]
> also note that this set of libs is NOT yet released, but appreciate you trying it!

Oh no, really? I thought this was the official/latest nats library for nodejs. But looking at the nats.io website again, I can see it's not actually on there. The examples are only for deno.

For what it's worth the libraries been really stable for me. I've built a key value data store, using event sourcing from nats jetstream and it's all just worked like clockwork:
https://github.com/markwylde/eventbase

Is there a different library I should be using right now to integrate nats jetstream and nodejs?

> yes they are out of sync - the current constraint is not strong enough for the current changes. I would do:
> 
> ```
> npm uninstall @nats-io/transport-node
> npm install @nats-io/transport-node
> ```
> 
> That should leave a tree that looks like:
> 
> ```
> > npm ls -a
> t@1.0.0 /private/tmp/t
> └─┬ @nats-io/transport-node@3.0.0-12
>   ├─┬ @nats-io/nats-core@3.0.0-31
>   │ ├── @nats-io/nkeys@1.2.0-7 deduped
>   │ └── @nats-io/nuid@2.0.1-2 deduped
>   ├─┬ @nats-io/nkeys@1.2.0-7
>   │ └── tweetnacl@1.0.3
>   └── @nats-io/nuid@2.0.1-2
> ```


i ran the commands you suggested and can confirm my tree now looks like this:

```
markwylde@Marks-MacBook-Pro natsbug % npm uninstall @nats-io/transport-node && npm install @nats-io/transport-node

removed 5 packages, and audited 1 package in 148ms

found 0 vulnerabilities

added 5 packages, and audited 6 packages in 3s

found 0 vulnerabilities
markwylde@Marks-MacBook-Pro natsbug % npm ls -a
natsbug@1.0.0 /natsbug
└─┬ @nats-io/transport-node@3.0.0-12
  ├─┬ @nats-io/nats-core@3.0.0-31
  │ ├── @nats-io/nkeys@1.2.0-7 deduped
  │ └── @nats-io/nuid@2.0.1-2 deduped
  ├─┬ @nats-io/nkeys@1.2.0-7
  │ └── tweetnacl@1.0.3
  └── @nats-io/nuid@2.0.1-2
```

But still the same issue. `connect` expects a `ConnectionOptions` but only works with an array of servers.

I'm not sure if this helps at all:

```
node_modules/@nats-io/transport-node/lib/connect.d.ts:1:10 - error TS2305: Module '"./nats-base-client"' has no exported member 'ConnectionOptions'.

1 import { ConnectionOptions, NatsConnection } from "./nats-base-client";
           ~~~~~~~~~~~~~~~~~

node_modules/@nats-io/transport-node/lib/connect.d.ts:1:29 - error TS2305: Module '"./nats-base-client"' has no exported member 'NatsConnection'.

1 import { ConnectionOptions, NatsConnection } from "./nats-base-client";
                              ~~~~~~~~~~~~~~

node_modules/@nats-io/transport-node/lib/nats-base-client.d.ts:1:15 - error TS2307: Cannot find module '@nats-io/nats-core/internal' or its corresponding type declarations.
  There are types at '/natsbug/node_modules/@nats-io/nats-core/lib/internal_mod.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

1 export * from "@nats-io/nats-core/internal";
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by aricart** [comment]
right now we have 3 supported libs:
- github.com/nats-io/nats.node (this was called github.com/nats-io/nats.js, but I hijacked the name for the consolidation) - `npm install nats`
- github.com/nats-io/nats.deno
- github.com/nats-io/nats.ws

The correct synchrony of libs works correctly - but in your case one the node lib updated to the latest of the core, which created your issues. I would uninstall all, and re-install or make sure you are specifying `@latest` to the modules. Do keep reporting things you see.

**Comment by markwylde** [comment]
Thanks @aricart 

> would uninstall all, and re-install or make sure you are specifying @latest to the modules. 

Just to confirm, this doesn't work. A fresh install of this library does not work with correct types. Your suggestion of uninstalling and re-installing does not solve the issue.

Thanks for all your work on this library and nats ❤️

**Comment by aricart** [comment]
@markwylde  try now -- you should get transport-node@3.0.0-17...

**Comment by markwylde** [comment]
Hi @aricart 

Yeah I now get:

```
"@nats-io/transport-node": "^3.0.0-17"
```

Unfortunately, while the type errors now go away, it still won't connect when adhering to the typescript definition.

IE:

# Working great!

## Code
```
import { connect } from "@nats-io/transport-node";
const nc = await connect(["localhost:4442", "localhost:4443"]);
console.log('connected to:', nc.protocol.info.server_name);
```

## Terminal
```
markwylde@Marks-MacBook-Pro natsbug % tsx main.ts
connected to: nats-dev-1
```

# Fails

## Code
```
import { connect } from "@nats-io/transport-node";
const nc = await connect({
  servers: ["localhost:4442", "localhost:4443"]
});
console.log('connected to:', nc.protocol.info.server_name);
```

## Terminal
```
markwylde@Marks-MacBook-Pro natsbug % tsx main.ts
/natsbug/node_modules/@nats-io/transport-node/lib/node_transport.js:79
                ? new nats_base_client_1.errors.ConnectionError("connection refused", { cause: err })
                  ^

ConnectionError: connection refused
    at NodeTransport.connect (/natsbug/node_modules/@nats-io/transport-node/src/node_transport.ts:113:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ProtocolHandler.dial (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:518:7)
    at async ProtocolHandler._doDial (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:570:9)
    at async ProtocolHandler.dodialLoop (/natsbug/node_modules/@nats-io/nats-core/build/src/protocol.ts:622:11) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:4443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1610:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 4443
  }
}

Node.js v22.11.0
```

**Comment by markwylde** [comment]
Works perfectly now. Thanks so much @aricart
