### ISSUE TITLE
Creating Ordered Consumer with DeliverAll policy hangs

### ISSUE THREAD

**Issue by piotr-karas** [nats-io/nats.js#113]
### Observed behavior

Using code below to create new Ordered Consumer:

```
const c = await nats.connect({ servers: ["nats://localhost:4222"] });
const js = c.jetstream();

const consumer = await js.consumers.get("test", {
  deliver_policy: nats.DeliverPolicy.All,
});
```

causes code to hang indefinitely - when I looked at API response from nats-server using `nats sub ">"` I saw following response:

```
[#1] Received on "$JS.API.CONSUMER.CREATE.test.Z545MR1A63RG6ZCLDMMEGL_1" with reply "_INBOX.Z545MR1A63RG6ZCLDMMDP9.Z545MR1A63RG6ZCLDMN2DL"
{"config":{"name":"Z545MR1A63RG6ZCLDMMEGL_1","deliver_policy":"all","opt_start_seq":1,"ack_policy":"none","inactive_threshold":300000000000,"num_replicas":1,"max_deliver":1,"mem_storage":true},"stream_name":"test","action":"create"}

[#2] Received on "_INBOX.Z545MR1A63RG6ZCLDMMDP9.Z545MR1A63RG6ZCLDMN2DL"
{"type":"io.nats.jetstream.api.v1.consumer_create_response","error":{"code":400,"err_code":10094,"description":"consumer delivery policy is deliver all, but optional start sequence is also set"}}
```

JS client tries to create consumer in a loop, but it cannot be successful so it just hangs indefinitely.

### Expected behavior

First of all DeliverAll policy should erase `opt_start_seq` option. This is a main problem. I know that the same as DeliverAll could be accomplished using StartSequence deliver policy or by leaving this option undefined, but this behavior is confusing.

Nice to have: in this kind of situation JS client could try a few times and return some error to let the user know that something bad happen, instead of hanging like this.

### Server and client version

nats-server in Docker: nats:2.10.18-alpine3.20
nats-cli: 0.0.35
nats client Deno: nats@v1.28.2

### Host environment

Windows 10 Pro 22H2

### Steps to reproduce

Example script written in Deno:
[nats-bug.zip](https://github.com/user-attachments/files/17635089/nats-bug.zip)

**Comment by aricart** [comment]
@piotr-karas Thank you. It was reproduced and fixed in the new code base. The new codebase creates the order consumer when you initially get it, so the hang doesn't occur there,
