### ISSUE TITLE
Improved Codesplitting for smaller bundles

### ISSUE THREAD

**Issue by enex** [nats-io/nats.js#121]
I want to use the library in a webapp in the browser. However the bundle size is rather large even thought i do not use jetstream and several of the other APIs. To avoid having to load it an alternative connect could be introduced that does the bare minimum and has the bare minimum of methods. If you then want to use for example jetstream, the api consumer imports it directly and passes it the connection. This is similar to how firebase restructured there API and would allow efficient code splitting and thus more resource efficient usage in the browser. It might also be beneficial to edge functions because the bundle size of the resulting JS can be reduced in many cases.

**Comment by aricart** [comment]
This is what this repo is doing....
