### ISSUE TITLE
Dangling async iterator after closing connection

### ISSUE THREAD

**Issue by Pwndrian** [nats-io/nats.js#134]
### Observed behavior

Using (test) code below to monitor the status of a connection:

```
const lock = Lock(3);
const { nc } = await setup({}, { reconnect: false });

(async () => {
  for await (const s of nc.status()) {
    switch (s.type) {
      case Events.Disconnect:
        lock.unlock();
        break;
    }
  }

  lock.unlock()
})().then();

nc.closed().then(() => {
  lock.unlock();
});

await nc.close();
await lock;
```

causes a dangling async iterator to endlessly await the "submission" of a new signal, as the iterator instance in the `NatsConnectionImpl` instance is *not* stopped upon calling `close`. This causes memory leaks when connections are (intentionally) closed and re-created.

### Expected behavior

The async iterator created by invoking `status` on the `NatsConnection` is stopped and doesn't wait for the "submission" of a new signal, after the connection is closed explicitly.

### Server and client version

@nats-io/transport-node: 3.0.0-20

### Host environment

Node.js: 20.11.1

**Comment by aricart** [comment]
There's something going on, not sure what - but the issue with the test is that the last `lock.unlock()` which should be called when the status ends, is not executing - (at least not for me in Deno). The iterator is closed - hang a promise on the status async and you'll see that it returns.

**Comment by aricart** [comment]
``` javascript
const nc = await connect({ servers: "demo.nats.io" });
  console.log(nc.getServer());

  const done = (async () => {
    for await (const s of nc.status()) {
      console.log(s);
    }
    console.log(">>>>>");
  })();


  await nc.reconnect();

  nc.closed().then((err) => {
    console.log(`closed: ${err}`);
  });

  await delay(1000);

  await nc.close();

  await done;
```

The `>>>>>` never prints, but done resolves....

**Comment by Pwndrian** [comment]
Thanks for the quick response!

I ran your code as well and I can confirm that the `>>>>>` never prints. However, the `done` promise does not resolve. It's the entire process that exits with error code 0 when awaiting `done `.

**Comment by aricart** [comment]
For me it resolves in Deno.
