### ISSUE TITLE
[@nats-io/nats-core] Make the constructor of NatsConnectionImpl public

### ISSUE THREAD

**Issue by stpnov** [nats-io/nats.js#142]
### Proposed change

I propose changing the visibility of the constructor of NatsConnectionImpl from private to public. This adjustment would enable developers to extend NatsConnectionImpl in their applications, allowing for enhanced customization and functionality in NATS client implementations.

### Use case

Currently, the NatsConnectionImpl class has a private constructor, which prevents developers from extending it. This limitation poses challenges when trying to create custom NATS clients or wrappers that require subclassing NatsConnectionImpl.

For example, in building a wrapper library around NATS, I attempted to extend NatsConnectionImpl to add additional methods and tailor the client to specific needs. However, the private constructor hinders this approach, leading to TypeScript errors and complications in type declarations. Workarounds like using composition or suppressing TypeScript errors (@ts-expect-error) result in maintenance issues and incomplete type definitions, especially when generating .d.ts files for consumption in other projects.

### Contribution

I am willing and interested in contributing a pull request to implement this change if it is accepted. I believe that modifying the constructor's visibility from private to public is a minimal change with significant benefits

**Comment by aricart** [comment]
No sorry cannot do that, I would make a contract to support the actual implementation of the connection, rather than the interface of the connection. You are welcomed to fork it.
