### ISSUE TITLE
when creating a JetStream consumer, allow passing more config parameters, e.g. MaxDeliver

### ISSUE THREAD

**Issue by derhuerst** [nats-io/nats.js#143]
### Proposed change

Using nats.js, I'd like to create a consumer (`jetstreamManager.consumers.add()`) with the option `MaxDeliver` (as documented in the [JetStream consumer configuration docs](https://docs.nats.io/nats-concepts/jetstream/consumers).

### Use case

I'd like messages not to be redelivered indefinitely, but for a fixed number of attempts.

### Contribution

👎 – don't have the time right now

**Comment by aricart** [comment]
Absolutely supported:

```javascript
  const ci = await jsm.consumers.add(stream, {
    durable_name: "me",
    ack_policy: AckPolicy.Explicit,
    max_deliver: 4,
    backoff,
  });
```

**Comment by derhuerst** [comment]
Huh, then the documentation is lacking, as it currently [doesn't show a field `max_deliver` on `ConsumerConfig`](https://nats-io.github.io/nats.js/jetstream/types/ConsumerConfig.html), even though `ConsumerConfig` seems to get the field from `ConsumerUpdateConfig`, [which has `max_deliver` defined](https://github.com/nats-io/nats.js/blob/0e87219ff63ad24ea786866ff0bd2b5c292d69ed/jetstream/src/jsapi_types.ts#L972-L975).

**Comment by aricart** [comment]
If I look at it, here: https://nats-io.github.io/nats.js/jetstream/types/ConsumerConfig.html


I see.- ConsumerConfig : ConsumerUpdateConfig & { other fields} - ConsumerUpdateConfig shows the field...
<img width="443" alt="image" src="https://github.com/user-attachments/assets/4cf65bb0-1895-4803-97df-0e743ad8da09">

JSDoc doesn't expand the subtypes you have to go click at them. If you enable typescript also expansion will show everything.
