### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by plandem** [nats-io/nats.js#156]
### Observed behavior

Not sure how is it supposed to use with Typescript. For bundling, I'm using `esbuild`, if it makes sense.

```
import { jetstreamManager, DiscardPolicy, RetentionPolicy, StorageType  } from "@nats-io/jetstream";

const INTERVAL_1d = 86_400_000;

export class Queue {
  async init(nats: any) {
    const jsm = await jetstreamManager(nats);

    await jsm.streams.add({
      name: "posts",
      subjects: ["posts.*.*"],
      retention: RetentionPolicy.Workqueue,
      discard: DiscardPolicy.Old,
      storage: StorageType.File,
      max_age: INTERVAL_1d * 7,
      max_msgs: 20000,
    });
  }
}
```

getting this error:
```
node:internal/modules/esm/resolve:296
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/jsapi_types' is not defined by "exports" in /Users/.../node_modules/@nats-io/jetstream/package.json
```

### Expected behavior

Properly working with typescript

### Server and client version

any

**Comment by aricart** [comment]
@plandem what is your intended runtime?
I was able to use esbuild -  can you share your exact settings for esbuild?

**Comment by plandem** [comment]
> @plandem what is your intended runtime? I was able to use esbuild - can you share your exact settings for esbuild?


that's my package.json:
{
  "scripts": {
    "clean": "rm -rf ../build",
    "build": "yarn clean && esbuild src/index.ts --bundle --platform=node --packages=external --allow-overwrite --format=esm --sourcemap --outdir=build",
    "start": "yarn build && dotenvx run -- node build/index.js",
    "dev": "dotenvx run -- nodemon --signal SIGTERM --ext ts --watch src"
  },
  "type": "module",
  "dependencies": {
    "@nats-io/jetstream": "^3.0.0-32",
    "@nats-io/kv": "^3.0.0-26",
    "@nats-io/transport-node": "^3.0.0-30"
  },
  "devDependencies": {
    "@types/node": "^22.10.1",
    "esbuild": "^0.24.0",
    "nodemon": "^3.1.7",
    "typescript": "^5.7.2"
  }
}


and that's my tsconfig.json:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "verbatimModuleSyntax": true,
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "moduleResolution": "node",
    "module": "ESNext",
    "noEmit": true,
    "lib": ["es2022", "dom"],
  }
}

```

**Comment by plandem** [comment]
getting the same error even without types:
```
import { jetstreamManager } from "@nats-io/jetstream";
// import { DiscardPolicy, RetentionPolicy, StorageType } from "@nats-io/jetstream";

const INTERVAL_1d = 86_400_000;

export class Queue {
  async init(nats: any) {
    const jsm = await jetstreamManager(nats);

    await jsm.streams.add({
      name: "posts",
      subjects: ["posts.*.*"], 
      retention: "workqueue", //RetentionPolicy.Workqueue,
      discard: "old", // DiscardPolicy.Old,
      storage: "file", //StorageType.File,
      max_age: INTERVAL_1d * 7,
      max_msgs: 20000,
    });
  }
}
```

**Comment by plandem** [comment]
oh, wait. my bad. it was message from KV (IDEA auto injected StorageType there) :(

Sorry for bothering, need to rest :)
