### ISSUE TITLE
Client parser error, interpreting state=26

### ISSUE THREAD

**Issue by FlightToFreedom** [nats-io/nats.js#274]
I am sending a curl -X POST request to my running nats server on a kubernetes pod.
Server version: 1.2.0
The payload contains valid JSON:
`curl -d@postMockRequest.txt -X POST nats.test.svc:4222 --trace-ascii debugLog.txt`
Where `postMockRequest.txt` contains valid JSON (validated with json-spec on Ubuntu machine  and 2 online validators)
The response i get is:
`[7] 2019/05/21 09:18:12.727531 [ERR] 10.254.48.5:48736 - cid:30 - Client parser ERROR, state=26, i=2: proto='"ST / HTTP/1.1\r\nHost: nats.-"...'`
Is there any documentation where i can see what `state=26` relates to?

**Comment by KoryNunn** [comment]
@FlightToFreedom Did you figure out what the issue was here?

**Comment by aricart** [comment]
@KoryNunn NATS has it's own protocol, he was making an HTTP request which with headers and all that is completely invalid for NATS.

**Comment by KoryNunn** [comment]
We were seeing the same error message, which went away when we updated to the latest docker image.

**Comment by FlightToFreedom** [comment]
Hi Kory,
I was indeed unaware that NATS does not accept HTTP request, so i created a webhook in kotlin that uses a [https://static.javadoc.io/io.nats/java-nats-streaming/2.1.1/io/nats/streaming/StreamingConnection.html](StreamingConnection) to comunicate with Nats, i now send my Curl messages to the webhook specifying the subject and the NatsStreamingConnection object within the webhook takes care of 'forwarding' the payload and subject.
