### ISSUE TITLE
Support Objects by Default

### ISSUE THREAD

**Issue by cawoodm** [nats-io/nats.js#279]
IMHO natsJS should support objects by default. This is JavaScript everything is an object - passing them around should just work. As things stand you could have members (listeners) with or without `var nats = NATS.connect({json: true});` and this would break things. Is there any specific reason for not supporting json by default?

**Comment by aricart** [comment]
@cawoodm if all your clients are javascript this makes sense. However the NATS ecosystem is payload agnostic.
