### ISSUE TITLE
Update documentation ?

### ISSUE THREAD

**Issue by Zhuull** [nats-io/nats.js#283]
I think you should update documentation for subscribe callbacks.

I was trying to find a way to retrieve the subject name in a subscribe callback, but I didn't find it..
Until I realized that the callback can take 4 arguments : 
- response
- replyTo
- channel Name 
- subscribe id(?)

Readme.md show us a maximum of 2 argument.
I don't know if this is specified somewhere, but I definitely can't find it :/

**Comment by aricart** [comment]
This is addressed by #294 in the README
