### ISSUE TITLE
Incorrect handling of the permission errors

### ISSUE THREAD

**Issue by andriy-bulynko** [nats-io/nats.js#289]
After the `permission_error` is handled, the `inbound` buffer is not cleared and all subsequent data appended to that buffer is ignored.

After @aricart 's explanation changing this to: after 1 `permission_error` is encountered, all subsequent buffer reads result in `permission_errors`.

**Comment by aricart** [comment]
@andriy-bulynko - Not clearing the inbound buffer is the correct behaviour. Can you explain why you think that it ought to be cleared? I can think of many reasons why it shouldn't as the inbound buffer could contain many many messages that the client shouldn't have to loose.

**Comment by andriy-bulynko** [comment]
@aricart I updated the title and description to more accurately describe the problem I saw versus what I (wrongfully) thought would be its solution. Please see the related changes in the linked PR. Thanks!
