### ISSUE TITLE
Ability to acknowledge messages manually

### ISSUE THREAD

**Issue by rohit-ravikoti** [nats-io/nats.js#299]
Hello!
I was wondering if the Node.js version of the NATS client has the ability to acknowledge messages manually as mentioned in the docs [here](https://nats-io.github.io/docs/developer/streaming/acks.html).

**Comment by StarpTech** [comment]
I think you are talking about Nats Streaming NOT Nats.
Here is the client lib for nats-streaming https://github.com/nats-io/stan.js

**Comment by rohit-ravikoti** [comment]
ah got it. Thank you!
