### ISSUE TITLE
Connecting to NATS on OpenShift cluster

### ISSUE THREAD

**Issue by chainhead** [nats-io/nats.js#301]
I was able to deploy the NATS Docker image to an OpenShift cluster. Then, I created a route for the resulting service. This route can be accessed by external clients at e.g. `http://<route name>.<host name>`. (Yes, port `80`.)

This did not connect - 

```javascript
const NATS = require('nats')
const nats = NATS.connect(<route name>.<host name>)
```
How do we connect?

**Comment by derekcollison** [comment]
NATS has its own protocol that goes over TCP, not HTTP. You will need to connect directly to the server, or at least have layer 4 aware router/load balancer.
