### ISSUE TITLE
Missing properties in typescript types definitions

### ISSUE THREAD

**Issue by fosk06** [nats-io/nats.js#302]
Version of the module : 1.3.2
the "ClientOpts" interface exported in the file  "index.d.ts"
Is missing the properties to use the Nkeys and User Credentials.
Theses properties are:
- "nkey": to set the nkey
- "sigCB": for the sign callback
- "userJWT" to set the static JWT

**Comment by aricart** [comment]
@fosk06 thanks for the catch. I have updated the typescript definitions as well as normalized the official names - `signCB` is `nonceSigner`. Also if you are using typescript, the typescript client has a more concise api - see https://github.com/nats-io/nats.ts

**Comment by fosk06** [comment]
Thanks for the quick fix!
I've opened this request because there is some typescripts module using the js version of the module, for example this [one](https://github.com/nestjs/nest/blob/master/package.json) .
I know it's weird but they did use the JS version instead of TS one

**Comment by aricart** [comment]
@fosk06 glad to get the heads up. BTW awesome - Nest using nats.js! - I love nest, have it in all my homes.

**Comment by fosk06** [comment]
i think you have a confusion between nest, the products/company recently bought by Google and "Nest.js", a typescript framework :)

**Comment by aricart** [comment]
oops.
