### ISSUE TITLE
NATS#connect - missing error handling for offline TLS options' verification [Bug]

### ISSUE THREAD

**Issue by labsvisual** [nats-io/nats.js#310]
## Introduction
When TLS options are specified under the `tls` key, the NATS client attempts to open a [`tlsSocket`](https://nodejs.org/api/tls.html#tls_class_tls_tlssocket).

If the provided options are invalid as is the case in the following examples, there is no error handling which warrants Node to emit a `unhandledException` event which can be dangerous for the consumers.

1) if the `key` does not match the `cert`;
2) if the `key` or the `cert` is malformed; etc.

These errors are thrown as a part of the sanity check in OpenSSL and take place **before** a connection has been initialized.

## Bug
If we had a stream, its event listeners are stripped
https://github.com/nats-io/nats.js/blob/407193dbe851ac336da4c9cff1e052ffd9328bdf/lib/nats.js#L1170

TLS options are sanitized and sent over to `tls.connect()` here:
https://github.com/nats-io/nats.js/blob/407193dbe851ac336da4c9cff1e052ffd9328bdf/lib/nats.js#L1172

After this, event handlers are re-attached with:
https://github.com/nats-io/nats.js/blob/407193dbe851ac336da4c9cff1e052ffd9328bdf/lib/nats.js#L1175

The error handling works perfectly for errors happening after the initial handshake (SNI, etc.) However, OpenSSL does a sanity check on the CA, Certificates and their keys amongst other things **before** starting a TCP connection. These errors are `throw`n as opposed to emitted in a wrapped event. Since we do not have **any** error handling for thrown events, this leads to a `unhandledException` scenario.

## Reproduction Steps
The following options configurations will trigger the bug:

### Case 1
```javascript
const fs = require( 'fs' );
const nats = require( 'nats' );

const options = {
    url: 'nats://127.0.0.1:4222',
    tls: {
        key: fs.readFileSync( path.join( __dirname, './client-1.key' ) ),
        cert: fs.readFileSync( path.join( __dirname, './client-2.crt' ) ), 
        ca: [ fs.readFileSync( path.join( __dirname, './ca.crt' ) ) ],
    }
};

const _client = nats.connect( options );
_client.on( 'error', error => {
    console.trace( 'There was an error: %s', error.message );
} );

_client.on( 'connect', () => {
    _client.close();
    console.log( 'Client connected!' );
} );
```

### Case 2
```javascript
const fs = require( 'fs' );
const nats = require( 'nats' );

const options = {
    url: 'nats://127.0.0.1:4222',
    tls: {
        key: fs.readFileSync( path.join( __dirname, './client-2.key' ) ),
        cert: fs.readFileSync( path.join( __dirname, './client-1.crt' ) ), 
        ca: [ fs.readFileSync( path.join( __dirname, './ca.crt' ) ) ],
    }
};

const _client = nats.connect( options );
_client.on( 'error', error => {
    console.trace( 'There was an error: %s', error.message );
} );

_client.on( 'connect', () => {
    _client.close();
    console.log( 'Client connected!' );
} );
```

These cases should throw a `ERR_OSSL_X509_KEY_VALUES_MISMATCH` error.

## Mitigation
The mitigation is _very_ straightforward with just a simple `try-catch` block around `tls.connect(...)`:

```javascript
try {
    this.stream = tls.connect(tlsOpts, () => {
        this.flushPending();
    });
} catch ( error ) {
    this.emit('error', new NatsError(CONN_ERR_MSG_PREFIX + error, CONN_ERR, error));
}
```

This seems to take care of the error and gives a well-formatted error to the consumer.

## Conclusion
The test cases for this are pretty simple as is the implementation; as such, if it's agreed to by the community, I'd be more than happy to submit a PR for the issue at hand. 💯 😄

**Comment by derekcollison** [comment]
Extremely well articulated! What a great report.

Will have @aricart weigh in but a PR would be great.

**Comment by labsvisual** [comment]
Wanted to include absolutely everything I could so even if we put this on a back burner, the contributor - at that point in time - has everything required to patch the bug. I am glad it checked the boxes required! 😃 

---
Already started the PR; will submit it posthaste. 💯

**Comment by derekcollison** [comment]
Very well done! Thanks.

**Comment by labsvisual** [comment]
@derekcollison, @aricart - should we close this and move the discussion to https://github.com/nats-io/nats.js/pull/311?

**Comment by aricart** [comment]
@labsvisual yes, already merging your PR into master!
