### ISSUE TITLE
Changelog for 1.4.0

### ISSUE THREAD

**Issue by icebob** [nats-io/nats.js#316]
Hi,

could you provide a changelog for the latest 1.4.0 version? I didn't find it.

Thanks!

**Comment by aricart** [comment]
https://github.com/nats-io/nats.js/releases/tag/v1.4.0

**Comment by aricart** [comment]
> Hi,
> 
> could you provide a changelog for the latest 1.4.0 version? I didn't find it.
> 
> Thanks!

My bad, the draft was not pushed!

**Comment by icebob** [comment]
Thank you 👍
