### ISSUE TITLE
behavior of maxReconnectAttempts does not match go client

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats.js#318]
The go client counts reconnect attempts per server it knows about. Say the client knows about 3 servers and max reconnect attempts is 2. The client will attempt to connect each server twice and perform a total of 6 connect attempts.

This is in contrast to, the js client and presumably java client. They behave like this (excerpt from doc, will change)
Applications can set the maximum reconnect attempts. Generally, this will limit the actual number of attempts total, but check your library documentation. For example, in Java, if the client knows about 3 servers and the maximum reconnects is set to 2, it will not try all of the servers. On the other hand, if the maximum is set to 6 it will try all of the servers twice before considering the reconnect a failure and closing.

This seems to be an issue across clients...

**Comment by matthiashanel** [comment]
Checked other clients too. (java as expected.)
https://github.com/nats-io/nats.java/issues/288

**Comment by derekcollison** [comment]
Thanks @matthiashanel
