### ISSUE TITLE
1.4.6 Release errors

### ISSUE THREAD

**Issue by CaptainYarb** [nats-io/nats.js#336]
When sending basic requests we get constant errors when pushing large volumes of data constantly.
```
TypeError: Cannot read property 'push' of null
    at Client.sendCommand (~/node_modules/nats/lib/nats.js:1060:16)
    at Client.publish (~/node_modules/nats/lib/nats.js:1643:10)
    at Object.publish (~/node_modules/spawnpoint-nats/spawnpoint.nats.js:172:35)
    at ~/controllers/heartbeat.js:39:20
```

Using code

```javascript
const data = {...} // large payload
nats.publish('node-05ea96f0-9d94-4b59-b139-f561ae899a7a.heartbeat', data, err => {
// do something
});
```

From what we can tell the issue can take a couple of minutes to propagate. Something in the sending buffer creates a problem we have had since `1.4.2` was in beta. We are still investigating...

**Comment by aricart** [comment]
The issue seems to be related to a timer triggering after `closeStream()` is called (which nullifies the inbound buffer. When the timer triggers and the client attempts to publish, the client hasn't yet reset the pending buffer.

**Comment by CaptainYarb** [comment]
That PR has worked on our dev builds just fine. Thanks for the quick fix!
