### ISSUE TITLE
Basic usage examples doesn't work

### ISSUE THREAD

**Issue by karliky** [nats-io/nats.js#344]
Hi all,

First of all, thanks for creating this library.

I tried to execute the examples under the basic usage section: https://github.com/nats-io/nats.js#basic-usage and I found some problems:

- If you copy/paste the example, it doesn't work as the `.close()` is called and there is no enough time to process the messages. The script will terminate and it will not show anything on the stdout. Wrapping the `nc.close()` call in a setTimeout fixes the issue.
- It seems that wrapping the code with `nc.on('connect')` changes the behavior of the request/reply. The request/reply order should be changed in order to make it work, which is confusing, example:

This doesn't work:
```
const NATS = require('nats')
const nc = NATS.connect('0.0.0.0:4222');
nc.on('connect', () => {
  nc.request('help', null, { max: 1, timeout: 1000 }, (msg) => {
    if (msg instanceof NATS.NatsError && msg.code === NATS.REQ_TIMEOUT) {
      console.log('request timed out')
    } else {
      console.log('Got a response for help: ' + msg)
    }
  });

  // Replies
  nc.subscribe('help', function (request, replyTo) {
    nc.publish(replyTo, 'I can help!')
  });

  setTimeout(() => {
    nc.close();
  }, 5000);
});
```

Removing the `nc.on('connect')...` fixes the issue:
```
const NATS = require('nats')
const nc = NATS.connect('0.0.0.0:4222');

  nc.request('help', null, { max: 1, timeout: 1000 }, (msg) => {
    if (msg instanceof NATS.NatsError && msg.code === NATS.REQ_TIMEOUT) {
      console.log('request timed out')
    } else {
      console.log('Got a response for help: ' + msg)
    }
  });

  // Replies
  nc.subscribe('help', function (request, replyTo) {
    nc.publish(replyTo, 'I can help!')
  });

  setTimeout(() => {
    nc.close();
  }, 5000);
```

Another way to fix it is by changing the order of how `nc.subscribe` and `nc.request` are declared:
```
const NATS = require('nats')
const nc = NATS.connect('0.0.0.0:4222');
nc.on('connect', () => {

  // I've moved this above nc.request
  nc.subscribe('help', function (request, replyTo) {
    nc.publish(replyTo, 'I can help!')
  });

  // I've moved this down nc.subscribe
  nc.request('help', null, { max: 1, timeout: 1000 }, (msg) => {
    if (msg instanceof NATS.NatsError && msg.code === NATS.REQ_TIMEOUT) {
      console.log('request timed out')
    } else {
      console.log('Got a response for help: ' + msg)
    }
  });

  setTimeout(() => {
    nc.close();
  }, 5000);
});
```

I think that if the library works without setting `nc.on('connect')` then it should always work when you set it, this is really confusing and it took me a lot of time to figure out. A normal user would expect the same behavior under the connect event.

Thanks for the help.

**Comment by aricart** [comment]
@karliky thanks for pointing out the defect in the README. sometimes we err when write the documentation or as it evolves we fail to test the snippet and this type of error shows up.
The correct implementation is the last one, where the subscription is registered before the request is made.

**Comment by aricart** [comment]
This issue is actually present in quite a bit of our repositories. The misleading part is that it looks like a program, but really what it is doing is illustrating the API usage, the ordering is incorrect if you were to run it as an example. Thanks again for pointing this out.

**Comment by aricart** [comment]
v2 readme page hopefully better at this.
