### ISSUE TITLE
Request / Reply clarification

### ISSUE THREAD

**Issue by hungrymike** [nats-io/nats.js#355]
Could someone clarify the RequestOne versus Request with Max: 1 a bit further. 

Say there are 2 subscribers on ex "logs" and a request is being made for a find/get. Would both subscribers try to reply - and only the fastest end as the response? 

Basically we want to have multi instances of services - and we only want one of the services/subscribers to reply/respond. Otherwise, creating and updating of data would be duplicated - since every instance would reply, right?

Thanks in advance

**Comment by derekcollison** [comment]
Yes you would only receive one response.

A common pattern we recommend if tail latency is a concern is that writes go to a subject that has many queue subscriber, meaning only one gets the message, but reads go to plain subscribers and the requestor gets the first response which is the fastest.

**Comment by hungrymike** [comment]
Thanks for the swift reply. I completely missed the queue groups. 

So if you send a message to a subscription with a queue group then the max: 1 is actually irrelevant?

**Comment by derekcollison** [comment]
When you publish a message that is mutually exclusive and decoupled from delivery of that message. When a bunch of subscribers join a queue group, only one will be selected to process the message. This works over any NATS server topology and is geo aware in super clusters etc.

**Comment by derekcollison** [comment]
The requestor is the one who specifies it only wants N replies, has nothing to do with the subscribers per se.

**Comment by hungrymike** [comment]
Thanks for the clarification !
