### ISSUE TITLE
Subscribe to a null topic generates a reconnect loop

### ISSUE THREAD

**Issue by nicogon** [nats-io/nats.js#357]
If I try to subscribe to a null or undefined topic, nats client will enter in a reconnect loop.

Nats server will output the following error `processSub Parse Error: '5'`

No error is emitted by the nats client.

Using latest node client. Server version version: 2.1.7

**Comment by nicogon** [comment]
thanks guys!

**Comment by aricart** [comment]
@nicogon - you can download the pre-release with `npm install nats@next`
