### ISSUE TITLE
Wildcard capture params

### ISSUE THREAD

**Issue by kethan** [nats-io/nats.js#363]
```js 
app.get('/user/:id', function (req, res) {
  res.send('user ' + req.params.id)
})
```
I want to capture id from the path. How do I achieve the same using wildcard?

**Comment by aricart** [comment]
@kethan looks like you filed an issue on nats.js, but your code example looks suspiciously like a web application framework signature.

**Comment by kethan** [comment]
> @kethan looks like you filed an issue on nats.js, but your code example looks suspiciously like a web application framework signature.

Yes it's express js can I achieve something similar like this using nats wildcard?

**Comment by aricart** [comment]
your subject can simply be 'user.<id>.etc' and you would subscribe to it as `user.*.etc`.
