### ISSUE TITLE
Option to connect via TLS (start on TLS connection rather than an upgrade)

### ISSUE THREAD

**Issue by chris13524** [nats-io/nats.js#369]
Clients can support TLS-terminating reverse proxies by switching out [this line](https://github.com/nats-io/nats.js/blob/master/lib/nats.js#L938) for this:

```
this.stream = tls.connect(this.url.port, this.url.hostname, { servername: this.url.hostname })
```

This solution sidesteps [the current TLS issue](https://github.com/nats-io/nats-server/issues/291) as it replaces the actual socket connection with an already TLS-ified one. The existing server and client code are not aware that TLS is already happening. In fact, I think clients _could_ upgrade to an extra TLS layer if they wanted.

Would it be better to support this via a direct [flag](https://github.com/nats-io/nats.js#connect-options) or a [custom dialer](https://github.com/nats-io/nats.go/blob/cd74bc037e7c4ec3e5dc4cbcd93b669c1f4e3778/nats.go#L217) like the Go client supports?

**Comment by aricart** [comment]
The current API framework for the JavaScript clients makes it pretty easy to create a new transport - https://github.com/nats-io/nats.js/blob/nd/src/node_transport.ts. The idea of allowing the server do a one-step TLS connect is being discussed.

**Comment by chris13524** [comment]
@aricart to clarify, my solution does not involve the server needing to change anything.

Cool that we will at least be able to accomplish this via an alternate `Transport` soon!

**Comment by aricart** [comment]
@chris13524 yes I understand that direct TLS will solve it - my point is that currently none of the clients support this, but there's talk about this feature for the server (which means that clients will have to handle this). At worse, we can put a workaround on the new code base.

**Comment by yuriyyakym** [comment]
Guys, if you still struggle with this issue, consider using [patch-package](https://www.npmjs.com/package/patch-package). And here is a patch (just single line replacement) for `nats@2.2.0`:
File: `patches/nats+2.2.0.patch`
```js
diff --git a/node_modules/nats/lib/src/node_transport.js b/node_modules/nats/lib/src/node_transport.js
index 7360311..441c8b0 100644
--- a/node_modules/nats/lib/src/node_transport.js
+++ b/node_modules/nats/lib/src/node_transport.js
@@ -97,7 +97,7 @@ class NodeTransport {
     dial(hp) {
         const d = nats_base_client_1.deferred();
         let dialError;
-        const socket = net_1.createConnection(hp.port, hp.hostname, () => {
+        const socket = tls_1.connect(hp.port, hp.hostname, () => {
             d.resolve(socket);
             socket.removeAllListeners();
         });

```

You can, of course, create a better patch with a support of an additional flag passed through options, if needed.
