### ISSUE TITLE
`process.version is undefined`, prevents import in Vue.

### ISSUE THREAD

**Issue by jackonelli** [nats-io/nats.js#372]
*I'm not sure if this is relevant at all, please close this if you find it unrelated to this library*

### Description

Executing this test script with node works as intended:
```javascript
const NATS = require('nats')
const nc = NATS.connect({ url: "nats://localhost:4222", user: <user>, pass: <pass>})
nc.publish("Hi", "There")
```

However, virtually the same construct in Vue:
```javascript
<template>
  <div class="nats-test">
    <h1>Hello</h1>
  </div>
</template>

<script>
const NATS = require('nats')
const nc = NATS.connect({ url: "nats://localhost:4222", user: <user>, pass: <pass> })
export default {
  name: 'NatsTest',
  props: {
    msg: String
  },
  mounted() {
    nc.publish("Hi", "There");
  }
}
</script>
```
produces: `Uncaught TypeError: process.version is undefined`

### Details
```
nats: "1.4.12"
vue: "2.6.12"
node: "12.16.1" 
```

**Comment by derekcollison** [comment]
You will want to use the latest nightly server and our new websocket support to get access directly from the browser.

**Comment by jackonelli** [comment]
Ok, great. I suspected it was my severly restricted web-dev skills that was the issue.
I'm using your excellent rust client and wanted to add a simple webpage client.
I'll look into websockets. Thanks, sorry for bothering you!

**Comment by aricart** [comment]
@jackonelli never a bother...
