### ISSUE TITLE
Equivalent of 'default connection in cluster mode' in Nats v2 API

### ISSUE THREAD

**Issue by vugtis** [nats-io/nats.js#377]
When reconnecting using NATS v2 API (nd branch), I experienced issue when attempting reconnection. It seems to reconnect to local ip which is unwanted.

Connection string :
`nc = await connect({ servers: ["seed-1:4222","seed-2:4222"]  });`

Logs :
```
Example app listening at http://localhost:3000
connected seed-1:4222
disconnect: seed-1:4222
reconnecting: seed-1:4222
reconnecting: seed-2:4222
update: [object Object]
reconnect: seed-2:4222
update: [object Object]
disconnect: seed-2:4222
reconnecting: 172.17.0.2:4222 <-- this is local ip
```

In the Nats V1 API , there is an option to specify 'url' in the cluster mode to avoid the issue i described above. Can be seen on 'Clustered Usage' section on the readme.
What is the equivalent usage  of that option in the Nats v2 API (nd branch) ?

**Comment by aricart** [comment]
You can turn off the gossip members on the new library, so only the specified servers you give will be tried. 
` ignoreClusterUpdates?: boolean;` is the connection option, you need to set it to `true`. 

You may want to npm install nats@beta to get the

**Comment by vugtis** [comment]
Will this new parameter turn off the discovery of the new servers that are not specified in in the server list?
Cause if it is, it will break one good feature from nats.

**Comment by aricart** [comment]
@vugtis hum - the local IP shouldn't be tried, unless you have a server that is reporting that, and it learned that IP.

**Comment by aricart** [comment]
Also the only time the client adds a default host is when you don't specify options or servers is specified empty.

https://github.com/nats-io/nats.deno/blob/main/nats-base-client/options.ts#L49

**Comment by aricart** [comment]
If you stringify the data from nc.status(), you should be able to see servers as they are added or removed.

**Comment by vugtis** [comment]
You mean to say that even with version 213, it shouldn't happened?

I think I have local running nats server within the same environment as my local node server ( i need to verify this ), but I am pretty sure i didn't set any route to/from my localhost nats server instance.  The 2 servers that i showed you are actually in the cloud, so i don't see there is a way that it is added through discovery. Unless what happen is nats detected there are local nats server running, so it automatically added it even though there is no root. 

I will try to turn off my local nats server and try the nc.status you told me, and get back to you tomorrow.

**Comment by aricart** [comment]
Correct 213 shouldn't have added localhost unless it was gossiped. This is why I suggested printing the data in the event.

**Comment by vugtis** [comment]
Hi. I checked it already. The issue still persist even with no local docker nats server running.

I have also tried printing the stringified data on the nc.status. If 2 nats servers has been running before running the node server, there will be no message that indicate 172.17.0.2:4222 is added on nc.status. But if i start with just 1 nats server, when I start the 2nd one after node server has been started, then the "172.17.0.2:4222 is added on nc.status" is shown.

With both cases,  the issue of local ip being tried persist. However, the local ip that is being tried is not the local ip from the node server, instead the local ip of the nats server. So, my guess is when the 2nd server got discovered, both the internet ip and local ip are broadcasted.

I wonder if it is because I use --cluster nats://0.0.0.0:6222 on the docker run command.

Here is the full run command I use :
```
docker run -d --name nats-server -p 4222:4222 -p 6222:6222 -p 8222:8222 nats:alpine --cluster nats://0.0.0.0:6222 -c /etc/nats/nats-server.conf --routes=nats://ruser:T0pS3cr3t@<ip-1>:6222
docker run -d --name nats-server -p 4222:4222 -p 6222:6222 -p 8222:8222 nats:alpine --cluster nats://0.0.0.0:6222 -c /etc/nats/nats-server.conf --routes=nats://ruser:T0pS3cr3t@<ip-2>:6222
```

**Comment by aricart** [comment]
Yes it gossiped all interfaces...

**Comment by aricart** [comment]
Yes it gossiped all interfaces. The Nats server has options to specify what is gossiped. Check it out in docs.nats.io

**Comment by vugtis** [comment]
Hi. I already found a solution for this. But to be honest, the docs are not exactly clear on that. The example on the docs are mostly for same server deployment. I imagine this kind of setup is pretty basic, so I suggest a clearer documentation or a section regarding this issue, but maybe this is wrong place for that suggestion. 

For anyone having this kind of issue in the future, please refer to this thread :
https://github.com/nats-io/nats-streaming-server/issues/587

Anyway, thank you for your time.
