### ISSUE TITLE
How to call queue subscriptions

### ISSUE THREAD

**Issue by mstimvol** [nats-io/nats.js#378]
Hi everyone,

sorry for my ignorance, but I'm having trouble understanding how to work with queues. The documentation says:

```
  // All subscriptions with the same queue name will form a queue group.
  // Each message will be delivered to only one subscriber per queue group,
  // queuing semantics. You can have as many queue groups as you wish.
  // Normal subscribers will continue to work as expected.
  nc.subscribe('foo', { queue: 'job.workers' }, function (req, replyTo) {
    received += 1
    nc.publish(replyTo, received) // modified by myself...
  })
```

Ok, that's fine. But I cannot find anything in the documentation on how to call it - or with other words: How a requestOne() looks like to call this subscription. I tired the following without success:

`nc.requestOne('job.workers foo')`

But nothing happens. The application simply stalls... So how to invoke the subscription function using publish or request-functions? Actually I don't see any Request-Option where I can set the name of the target queue...

**Comment by aricart** [comment]
@mstimvol the issue is how you are calling it.

The subject for your subscription is `foo`, - the subscriber is the one that specifies the queue.
The client making a request, simply publishes to `foo`, ie change your code to be:
`nc.requestOne('foo')`

**Comment by aricart** [comment]
(spaces in a subject are invalid)
