### ISSUE TITLE
Jetstream durable name validation issue

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.js#382]
A user reported the following:

```When using the node library I’ve noticed that if you integrate with the Jetstream Admin API and provide a durable name containing a ., *, or > you don’t get an API error back from the server or the library. ```

The client should check for wildcards and error out when there is an invalid durable name.  We'll want to do the same for stream names.

**Comment by wallyqs** [comment]
Reference of what was done in the Go client: https://github.com/nats-io/nats.go/pull/633/files

**Comment by scottf** [comment]
based on this go client change, it looks like the only invalid character is the period `.` 
https://github.com/nats-io/nats.go/pull/633/files. This is matched in java in https://github.com/nats-io/nats.java/pull/398

**Comment by ripienaar** [comment]
The correct check is to fail for names with any of `.`, `*` or `>`

See isValidName() in the server code

**Comment by scottf** [comment]
That would seem to suggest that the change in PR 633 is also not correct.

**Comment by ripienaar** [comment]
663 would be enough - but it would fail slow after a server round trip rather than early where client dev can have an opportunity to provider better errors than the server - generally the server gives quite poor feedback on validation

**Comment by aricart** [comment]
this is handled.
