### ISSUE TITLE
Question: Is v2-2.0.0-218 "production ready"?

### ISSUE THREAD

**Issue by delps1001** [nats-io/nats.js#393]
My team is working on going to production with nats now, would it be advised to start implementing our project using the release candidate build? Or at this point would it still be advised to ts-nats or use the 1.4.x library? Is there any timeline for when there will be a proper release of version 2? I ask because it seems like there are pretty decent incompatibilities between the versions and I would like to avoid rewriting our entire nats client connection code if it's going to go to a fully released 2.0 version very soon.

**Comment by aricart** [comment]
@delps1001 you should use the release candidate unless you want to change your code at a later date. The proper release should be in the next few days. Also, ts-nats is completely deprecated as nats.js now has all the async functionality that was wrapped on the old nats.js client.

Having you develop on it would also help us to get additional integration testing from user code. File any issues you run into.

**Comment by delps1001** [comment]
> @delps1001 you should use the release candidate unless you want to change your code at a later date. The proper release should be in the next few days. Also, ts-nats is completely deprecated as nats.js now has all the async functionality that was wrapped on the old nats.js client.
> 
> Having you develop on it would also help us to get additional integration testing from user code. File any issues you run into.

Thank you for your answer!
