### ISSUE TITLE
Connecting while purposefully offline

### ISSUE THREAD

**Issue by semireg** [nats-io/nats.js#401]
When my "app" starts without a connection to NATS, I get this error.

```
(node:1) UnhandledPromiseRejectionWarning: NotConnectedError: Unable to establish a connection
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have tried many different options with the same result:

```
    const url = `nats://${this.address}:4222`;
    const options = {
      maxReconnectAttempts: Number.MAX_SAFE_INTEGER, // or -1
      reconnectTimeWait: 2500, // ms
      waitOnFirstConnect: true, // or false
      servers: [url]
    };
```

Similar to: https://github.com/nats-io/nats.js/issues/376 but I'm unable to install from the `beta` branch to test the fix.

**Comment by aricart** [comment]
The builds are now under "rc" `npm install nats@rc` - https://github.com/nats-io/nats.js#installation

**Comment by aricart** [comment]
@semireg  Open a new issue if you still have difficulties after updating.

**Comment by semireg** [comment]
I've been running with rc, the above error is with "nats": "^2.0.0-220"

**Comment by semireg** [comment]
This is very strange. This node app is running in a docker container on a Linux appliance. I'm specifically doing offline testing of the app by putting the appliance behind a raspberry pi's eth0 configured to route/forward Internet access via the pi's wifi. Everything works as expected.

On the pi, when I "turn off" networking (echo 0 > /proc/sys/net/ipv4/ip_forward) the app is isolated and can not connect to the Internet. However, the actual NATS server is on the appliance's host OS, so I'm connecting from the docker container to the host at 10.30.50.1.

I find it very strange that turning off the pi's routing stops the NATS client from connecting on what would otherwise be a localhost connection.

To see if it's truly the networking that's broken, I created this barebones test using the protocol demo docs at https://docs.nats.io/nats-protocol/nats-protocol-demo.

```
> var net = require('net'); var socket = net.createConnection(4222, '10.30.50.1', function() { console.log('connected'); }); socket.on('error', function(err) { console.error('error:' + err); }); socket.setEncoding("utf8"); socket.on('data', function(data) { console.log("data: " + data); }); socket.write("sub relay 99\n");
```

It works perfectly with the pi's routing off or on. So this really seems like a problem with NATS... and I'm just not sure why it would be affected like this. Any ideas?

```
true
> connected
data: INFO {"server_id":"ABCD","version":"1.0.4","go":"go1.9.7","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
+OK

data: MSG relay 99 214
{..... my expected payload here .....}
```

🤔 @aricart

**Comment by aricart** [comment]
@semireg sent you a meet, to see if we can solve the issue.

**Comment by semireg** [comment]
My issue ended up being a race on startup between nats.js connection to a localhost server (effectively docker container to docker host) and an Azure IOT client (https://github.com/Azure/azure-iot-sdk-node) which was connecting to Azure via wan. 

To workaround, I postponed creating the Azure IOT client until after nats.js establishes all local connections. It's worth noting that after I receive the UnhandledPromiseRejectionWarning, that existing execution path was dead. Meaning, code surrounding the error/warning never executed/executes. It's a frightening failure case and might be an opportunity to harden nats.js for this edge case.

Fwiw, this is on node v10.17.0 via docker image node:10-alpine.

**Comment by aricart** [comment]
@semireg the initial connection really needs to be handled, if you do there shouldn't be any unhandled promise.
Can you share your connect code?

**Comment by semireg** [comment]
```
import { connect as NatsConnect, NatsConnection, StringCodec } from 'nats';
....

    const url = `${this.address}:4222`;
    const options = {
      maxReconnectAttempts: Number.MAX_SAFE_INTEGER,
      reconnectTimeWait: 2500, // ms
      waitOnFirstConnect: true,
      servers: [url]
    };

    NatsConnect(options)
      .then(nc => {
        this.nc = nc;
        this.debug('connected to url: ' + url);
        nc.subscribe(this.defaultSubscribe, {
          callback: (err, { subject, data }) => {
            if (err) {
              this.warn(`subscribe callback error: ${SafeStringify(err)}`);
              return;
            }
            if (this.onMsgReceived != null) {
              this.onMsgReceived(subject, DecodeString(data)).catch(
                callbackError => `onMsgReceived error: ${callbackError}`
              );
            }
          }
        });
        return null;
      })
      .catch(natsError => {
        this.warn(`nats connect error: ${SafeStringify(natsError)}`);
        return null;
      });
```

**Comment by aricart** [comment]
so when you call your async function in node (the one that calls connect) if it catches, that function will return, possibly you want to handle that as a signal that your program is done. For `maxReconnectAttempts` you want to use `-1`.

**Comment by semireg** [comment]
It is my understanding that the catch on NatsConnect would catch any error being thrown from within that promise chain. Am I wrong? Perhaps the try/catch internally (I haven't looked at the source) isn't fully wrapping the internals with try/catch to reject the promise.

**Comment by aricart** [comment]
The async function is also returning a promise.... If you didn't then/catch it is in handled....
