### ISSUE TITLE
Can not import createInbox() function in nats.js 2.0.0-220

### ISSUE THREAD

**Issue by szapo** [nats-io/nats.js#404]
Hi there,
When trying to import createInbox I receive the following error:
import createInbox
Module '"nats"' has no exported member 'createInbox'.ts(2305)

createInbox() function used to generate a random inbox subject. Did you forget to export the function in nats 2.0.0-220?
Thank you.

**Comment by szapo** [comment]
I forgot to mention that I am writing in TypeScript (this is why the constrains). After poking around the code, I realized that there is a workaround like so:
import { createInbox } from 'nats/lib/nats-base-client/protocol'

and then you can use it like so:
const inbox:string = createInbox()

It would be great if createInbox() could be imported only from nats module, like all the other functions. Thank you.

**Comment by aricart** [comment]
@szapo yes that is an omission.

**Comment by aricart** [comment]
@szapo this is now fixed on master as well as when using the 2.0.0 library.
