### ISSUE TITLE
I can not implement the new concept of Headers in my client connecting via nats.js 2.0.0-220

### ISSUE THREAD

**Issue by szapo** [nats-io/nats.js#405]
Hi there,
I am having some difficulties being able to implement and run your new concept of Headers, despite of the documentation and examples you have provided.

I am running a docker-compose cluster of 3 nats-server ver. 2.1.9 and I am connecting to the cluster via nats.js ver. 2.0.0-220 connector. As per your documentation: "If the client wishes to send headers, it has to enable it must add a headers field with the true value in its CONNECT message: "
In TypeScript you don't even have the option available (headers: true), however you can force it if you declare the type any instead of ConnectionOptions.

Question: Is connector nats.js ver. 2.0.0-220 ready to use Headers? Is the latest nats-server 2.1.9 published on docker-nats able to handle the protocol with headers enabled?
Thank you.

**Comment by aricart** [comment]
@szapo where in the doc do you see this - I thought I have removed all those references. Previously the headers were opt-in, now they are enabled by default if the server supports them. Current README.md doesn't have that statement...

**Comment by szapo** [comment]
@aricart well, software developer learn in so many ways about new concepts; one is indeed the documentation; other avenue are the examples (take a look at nats-pubs.js, it looks to me like an opt in):
...
if (argv.headers) {
  opts.headers = true;
}
...
Also, all the info from nats.js I collaborated with documentation from the server.

In conclusion, the connector always has the feature. Do I have to understand that the latest container with nats-server server 2.1.9 does not have headers enabled? Is this feature (headers) going to be available in the server community edition? Do you know how can community gets its hands on a server like so in order to develop solutions? Any ideas when a server with headers enabled is going to be push out? 

Thank you.
Note: nats.js connector is very good; I like it. Congrats!

**Comment by aricart** [comment]
@szapo thanks, the update of the examples on nats.js fell through the cracks. Thanks.
The headers feature is not yet released. You'll need a nightly build of the server or build your own. 
You can get a docker nightly image that has it enabled https://github.com/nats-io/jetstream#using-docker

**Comment by aricart** [comment]
Very glad you like it. Code you write ports directly to browser and deno ;)

**Comment by szapo** [comment]
Thank you.
