### ISSUE TITLE
2.0 release notes

### ISSUE THREAD

**Issue by MickL** [nats-io/nats.js#410]
Awesome to see 2.0 published! Anyhow I was looking for some kind of release notes: What is new, what is different, why is it different, what is the motivation etc.

Is there anything like this I did miss or a blog post or something? Would love to read this!

**Comment by aricart** [comment]
You missed the migration document https://github.com/nats-io/nats.js/blob/master/migration.md

**Comment by aricart** [comment]
this other nugget may be interesting as well - https://github.com/nats-io/nats.js/#jetstream

**Comment by MickL** [comment]
No I saw that but it does not talk about the why which would be very interesting
