### ISSUE TITLE
RxJS

### ISSUE THREAD

**Issue by MickL** [nats-io/nats.js#411]
As nats.js is mostly about subscribtions and events, wouldnt it make sense to implement and use RxJS[RxJS](https://github.com/ReactiveX/rxjs) widley? It would give tons of useful features and sinplification of complex problems and could be widely used in the nats.js code, too. 

In the JavaScript context RxJS is widely used within Angular and Nest.js.

Alternatively a wrapper could be written.

**Comment by aricart** [comment]
@MickL, a wrapped fork would be fine. For purposes of our libraries limiting the number of dependencies and focusing on cross, environments is a better alternative. Note that for angular and other applications, you wouldn't use this library as this library uses raw TCP sockets that are not accessible on the browser. For browser clients check out [nats.ws](github.com/nats-io/nats.ws) - it has the same exact API as the node.js client.

**Comment by MickL** [comment]
I just mentioned Angular as a popular example that uses RxJS, too.
