### ISSUE TITLE
ReactJS: Unhandled Rejection (TypeError): net_1.createConnection is not a function

### ISSUE THREAD

**Issue by jaredgreener** [nats-io/nats.js#412]
I am not able to get a basic implementation of nats.js to run in a reactjs app. Followed the steps:

1) npm install nats@latest
2) import nats: import { connect, JSONCodec } from "nats";
3) connect to server
4) subscribe and handle messages:

```javascript
    async componentDidMount() {
        
        const codec = JSONCodec();
        const natsClient = await connect({ servers: "nats.invictme.com:4222" });
        const subscription = natsClient.subscribe("document."+this.state.documentID);
        await (async (subscription) => {
            for await (const m of subscription){
                subscription.getProcessed();
                let jsonData = codec.decode(m.data);
                this.serverMessageReceived(jsonData);
            }
        })(subscription);

    }
```

Always ends in: Unhandled Rejection (TypeError): net_1.createConnection is not a function

<img width="524" alt="Screen Shot 2021-03-18 at 9 41 46 PM" src="https://user-images.githubusercontent.com/2931865/111724225-de0bf500-8832-11eb-9b36-75fa962c0af1.png">

**Comment by aricart** [comment]
@jaredgreener are you running in a browser?

**Comment by aricart** [comment]
If you are, you want to look at [nats.ws](github.com/nats-io/nats.ws) - the nats.js library is intended to run on node.js with native tcp support which doesn't exist on the browser. Please reopen if you are doing something else.
