### ISSUE TITLE
Property 'on' does not exist on type 'NatsConnection'

### ISSUE THREAD

**Issue by huineng** [nats-io/nats.js#413]
Hi trying out this example https://docs.nats.io/developing-with-nats/reconnect/events

i'm using v 2.0.0

but i'm getting a typescript error 

```
client.ts:15:8 - error TS2339: Property 'on' does not exist on type 'NatsConnection'.

nc.on("reconnect", (conn, server) => {
         
```

maybe the interface needs to be updated

```
export interface NatsConnection {
    info?: ServerInfo;
    closed(): Promise<void | Error>;
    close(): Promise<void>;
    publish(subject: string, data?: Uint8Array, options?: PublishOptions): void;
    subscribe(subject: string, opts?: SubscriptionOptions): Subscription;
    request(subject: string, data?: Uint8Array, opts?: RequestOptions): Promise<Msg>;
    flush(): Promise<void>;
    drain(): Promise<void>;
    isClosed(): boolean;
    isDraining(): boolean;
    getServer(): string;
    status(): AsyncIterable<Status>;
    stats(): Stats;
    jetstreamManager(opts?: JetStreamOptions): Promise<JetStreamManager>;
    jetstream(opts?: JetStreamOptions): JetStreamClient;
}
```

thanks

**Comment by huineng** [comment]
also, if i may be so free 

https://docs.nats.io/developing-with-nats/sending

the example shows 

```
let nc = await connect({
    url: "nats://demo.nats.io:4222",
    payload: Payload.STRING
});
```

but payload doesn't exist on the interface (above)

Now if you can pass a string , this then would lead to the problem that string does not exist on publish

Maybe you can adapt it in the following way

```
publish(subject: string, data?: string | Uint8Array, options?: PublishOptions): void;
```

Finally you https://docs.nats.io/developing-with-nats/receiving/async is maybe not the best typescript way (it gives errors

```
    const subscription = await nc.subscribe("updates");

    for await (const m of subscription) {
      subscription.getProcessed();
      console.info(m.data.toString()); // in case of a buffer
      // console.info(m.data; // in case of a string
    }
  }

```

many thanks

**Comment by sayerrrr** [comment]
@huineng - I'm getting this error also, did you find a solution?

**Comment by huineng** [comment]
Well i opened this ticket initially reading the instructions i think  [here](https://docs.nats.io/developing-with-nats/connecting/default_server)

But i closed applying the methods described in this git using subscriptions.. i think the documentation on nats.io might need a bit of an update. But otherwise the subscription works perfectly and since i set it up, i never had any issue with nats (very stable)

**Comment by derekcollison** [comment]
Always looking to improve docs, so will take this suggestion, thanks.

/cc @aricart

**Comment by aricart** [comment]
@huineng yes the docs in nats.io are outdated - I started the update already.
