### ISSUE TITLE
export DebugEvents enum 

### ISSUE THREAD

**Issue by delps1001** [nats-io/nats.js#414]
When I try to access the `DebugEvents` enum it always comes as undefined. The same is not true for the `Events` enum, it is exported correctly.

```typescript
import { Events, DebugEvents } from 'nats';
console.info(Events.Error); // <-- outputs correctly the string enum
console.info(DebugEvents.Reconnecting); // <-- will throw an error because DebugEvents are undefined
```

**Comment by delps1001** [comment]
Created a PR:  not sure if it is complete or not: https://github.com/nats-io/nats.deno/pull/131

**Comment by aricart** [comment]
@delps1001 thanks for the contribution, this will be available shortly.
