### ISSUE TITLE
Unable to unsunscribe from a topic

### ISSUE THREAD

**Issue by arjunlondhey** [nats-io/nats.js#418]
I am subscribing to a topic with code: 
Also I am able to read the data form the topic:
```
const nc = await connect({ servers: ["HOST:PORT"] });
const sub = nc.subscribe(name, { queue: queue });
    (async () => {
      for await (const m of sub) {
        let data = jc.decode(m.data);
        console.log(JSON.stringify(data));// Able to read the data
         nc.unsubscribe(sub); // Unable to unsubscribe this `error:: nc.unsubscribe is not a function`
        }
      }
    })();
```

But I am unable to unsubscribe the topic. Getting error as nc.unsubscribe is not a function

**Comment by aricart** [comment]
`nc.unsubscribe()` doesn't exist, the connection => https://github.com/nats-io/nats.js/blob/master/index.d.ts#L37

https://github.com/nats-io/nats.js#publish-and-subscribe
> To cancel a subscription and terminate your interest, you call unsubscribe() or drain() on a subscription
