### ISSUE TITLE
Options port + servers

### ISSUE THREAD

**Issue by Sirogha** [nats-io/nats.js#420]
Hello.

I install nats packege (v2.0.2). And try to connect via servers + port.

`module.exports.connect = async function () {
  try {
    natsConnection = await connect({
      servers: servers: process.env.APP_NATS_SERVER_URL,
      port: process.env.APP_NATS_SERVER_PORT,
      user: process.env.APP_NATS_SERVER_USERNAME,
      pass: process.env.APP_NATS_SERVER_PASSWORD,
      maxReconnectAttempts: -1,
      reconnectTimeWait: 5000
    });
    closedStatus = natsConnection.closed();
    console.log(`natsModule connected`);
  } catch (err) {
    console.warn(`natsModule catch err`, err);
  }
};`

After that i get error: 
`NatsError: CONNECTION_REFUSED
    at Function.errorForCode (C:\git_dreamapps\marketing_appstoreconnect_grabber_service\node_modules\nats\lib\nats-base-client\error.js:98:16)
    at NodeTransport.<anonymous> (C:\git_dreamapps\marketing_appstoreconnect_grabber_service\node_modules\nats\lib\src\node_transport.js:82:52)
    at Generator.throw (<anonymous>)
    at rejected (C:\git_dreamapps\marketing_appstoreconnect_grabber_service\node_modules\nats\lib\src\node_transport.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'NatsError',
  code: 'CONNECTION_REFUSED',
  chainedError: Error: connect ECONNREFUSED 127.0.0.1:4222
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 4222
  }
}`

I try to search this kind error in code. And see this: http://prntscr.com/116fmu3

**Comment by aricart** [comment]
@Sirogha the options for `servers` and `port` are mutually exclusive. If you provide a port it will try to connect to `127.0.0.1:<port>`. The servers option can specify just hostnames or host:ports. If you specify hostnames, the port used will be `4222`. Otherwise, it will attempt the specified host:port. If you need local and remote servers, you can do so by specifying them in the `servers` option. 

Note the `servers` option will accept a string, but the string must contain a single `host:port`. For information on how to connect please take a look at: https://github.com/nats-io/nats.js#connecting-to-a-nats-server

**Comment by aricart** [comment]
Your connect should look like this:
```javascript
async function() {
    try {
        natsConnection = await connect({
            servers: process.env.APP_NATS_SERVER_URL,
            user: process.env.APP_NATS_SERVER_USERNAME,
            pass: process.env.APP_NATS_SERVER_PASSWORD,
            maxReconnectAttempts: -1,
            reconnectTimeWait: 5000
        });
        closedStatus = natsConnection.closed();
        console.log(natsModule connected);
    } catch (err) {
        console.warn(natsModule
            catch err, err);
    }
};
```
Note that the rogue nested `servers` and `port` were removed. If you need to include a local server do:
```javascript
async function() {
    try {
        natsConnection = await connect({
            servers: [process.env.APP_NATS_SERVER_URL, "127.0.0.1:`${process.env.APP_NATS_SERVER_PORT}"],
            user: process.env.APP_NATS_SERVER_USERNAME,
            pass: process.env.APP_NATS_SERVER_PASSWORD,
            maxReconnectAttempts: -1,
            reconnectTimeWait: 5000
        });
        closedStatus = natsConnection.closed();
        console.log(natsModule connected);
    } catch (err) {
        console.warn(natsModule
            catch err, err);
    }
};
```
