### ISSUE TITLE
What kind of release versioning does this project use?

### ISSUE THREAD

**Issue by delps1001** [nats-io/nats.js#425]
In the latest *patch* version it included breaking changes to the way headers are handled see [here](https://github.com/nats-io/nats.deno/releases/tag/v1.0.4). I'm curious as to what the recommended upgrade path is for this project. Is it generally safe to do minor/patch updates? I use tools to automate dependency updates (Renovate), and would like to know if I should add a special rule for this project.

**Comment by aricart** [comment]
Yes unfortunately all the NATS clients have changes related to this. I had proposed that the case-insensitive lookups with case-preserving writes were the correct solution but was overruled.

**Comment by aricart** [comment]
More direct to your question the minor and micro should be safe, to have compatibility with the old behaviour, simply refactor your code to use the canonical match strategy. https://github.com/nats-io/nats.js/blob/master/index.d.ts#L161

**Comment by delps1001** [comment]
> More direct to your question the minor and micro should be safe, to have compatibility with the old behaviour, simply refactor your code to use the canonical match strategy. https://github.com/nats-io/nats.js/blob/master/index.d.ts#L161

@aricart why was there not a major version bump to the project if there were breaking changes included?

**Comment by aricart** [comment]
because we just released.

**Comment by delps1001** [comment]
so basically because there was a release so recently the breaking change was more or less treated as a bug?

**Comment by ripienaar** [comment]
I believe this is a bug fix personally, we literally made a mistake in designing this feature and found it did not work in the real world, a bug fix resolved that and made it more useful in the general sense.  

In my mind the feature was broken.

**Comment by ColinSullivan1** [comment]
I agree.  The decision was to support both.  Case is preserved, with client allowing a case sensitive lookup and optionally a case insensitive lookup as well as case sensitive.

This provides the most functionality and flexibility moving forward.
See:  https://github.com/nats-io/nats-server/pull/2158 and https://github.com/nats-io/nats-server/pull/2177 for discussion.

**Comment by delps1001** [comment]
fair enough, I respect the decision. Was just looking for some clarity! Thank you @aricart @ColinSullivan1 @ripienaar

**Comment by ripienaar** [comment]
Thanks @delps1001, to be clear in general we try to follow SemVer, but sometimes the reality of life is we think a brand new feature or super infrequently used feature is just not going to fly in the real world and we fix it.

The NATS protocol has > 10 years of client stability, so we take this very seriously  - but at the same time sometimes to achieve that level of stability we need to be able to say we messed up and we will fix it as soon as possible before a large set of users are impacted.

**Comment by aricart** [comment]
@delps1001 - I totally get what you are saying. We tend to regard major versions as something really major (matching features) - "usually", but really it is just about the dev contract. Unfortunately because of the spread/maturity of different clients, the versions don't line up. Perhaps the concept of API version and Feature version should be something we explore. This would allow aligning server/client versions while allowing the semver for the library to move at the speed it needs and provide the protection you seek.

**Comment by aricart** [comment]
Maybe R.I. nailed it there, we should look into a "PROTOCOL" client version that normalizes features between clients/server/etc. And the lib version (what you see as npm version). That may be useful for sure.

**Comment by delps1001** [comment]
> @delps1001 - I totally get what you are saying. We tend to regard major versions as something really major (matching features) - "usually", but really it is just about the dev contract. Unfortunately because of the spread/maturity of different clients, the versions don't line up. Perhaps the concept of API version and Feature version should be something we explore. This would allow aligning server/client versions while allowing the semver for the library to move at the speed it needs and provide the protection you seek.

I think this would be a good compromise 🙂
