### ISSUE TITLE
[nats.js@2.0.0] One request several answers, possible?

### ISSUE THREAD

**Issue by aabbdev** [nats-io/nats.js#426]
Hello,

I wanted to know if it was possible to make a request and receive several answers with nats.js@2.0.0

Thanks

**Comment by aricart** [comment]
The request API returns a promise to a single message, but requests are simply publishing a message that specifies a reply address. To receive multiple replies simply create an inbox, start a subscription and publish your request. If you know the number of replies you are expecting, you can specify the max number of messages to receive in the subscription. In all actuality you probably want to specify some sort of timeout in case not all replies (or none) arrive:

```javascript
connect({ servers: "demo.nats.io" })
  .then((nc) => {
    const inbox = createInbox();

    // some service listening
    nc.subscribe("reqsubj", {
      callback: (err, msg) => {
        msg.respond();
      },
    });
    nc.subscribe("reqsubj", {
      callback: (err, msg) => {
        msg.respond();
      },
    });
    nc.subscribe("reqsubj", {
      callback: (err, msg) => {
        msg.respond();
      },
    });

    nc.subscribe(inbox, {
      max: 3,
      callback: (err, msg) => {
        console.log(`got response`);
      },
    });
    nc.publish("reqsubj", Empty, { reply: inbox });
  });
  ```
