### ISSUE TITLE
request() multiple responses

### ISSUE THREAD

**Issue by roguh** [nats-io/nats.js#427]
Hello, I was wondering if it was possible to use NatsConnection.request to receive multiple responses?

I believe the Python version of request has an `expected` argument that's 1 by default but can be `N`. Could it be possible to use the `reply` argument to receive multiple responses?

Thank you

**Comment by roguh** [comment]
It seems v1 of nats.js supported a `max` argument:
`nc.request('help', null, { max: N, timeout: 1000 }, (msg) =>...`

**Comment by roguh** [comment]
I see that nats.request creates a subscription with `max=1` at https://github.com/nats-io/nats.deno/blob/main/nats-base-client/nats.ts#L160
I could easily modify this code in a fork if this feature is not a priority for you.

**Comment by aricart** [comment]
In v2 the API of request, it simply returns a promise to a message, so multiple responses would require an API break or a different function.

**Comment by aricart** [comment]
Also, what would the behaviour be if you wanted 10 responses and just got 9? - In call cases, the code cannot simply limit the number of responses to the know counts, because, in the end, you'll either get the expected number of messages or timeout.

**Comment by roguh** [comment]
I think I'd want to it to return 9 out of 10 responses without an error, and I would let the user of my software figure out something is missing.

**Comment by roguh** [comment]
Ok. I can create a separate function by copying the current code an modifying it a little bit.

**Comment by tacyarg** [comment]
@roguh To accept multiple responses you can publish an event with a reply inbox attached.

```js
//CLIENT
const inbox = createInbox();

// emit the request
return nats.publish("calls", event, {
    reply: inbox
});

// replies will come here
const inboxSub = nats.subscribe(inbox);
inboxSub.on('message', msg => {
    nats.publish(msg.reply, chunk)
})



// SERVER
const callSub = nats.subscribe("calls");
callSUb.on('message', msg => {
    nats.publish(msg.reply, chunk)
})
```

**Comment by roguh** [comment]
Thank you so much!

**Comment by aricart** [comment]
This is the way all requests work underneath.  However you need to stop the subscription what you have handled the number of responses you expected or some timeout happens...

**Comment by tacyarg** [comment]
Is thier any other downsides to the implementation? @aricart

**Comment by aricart** [comment]
Not at all.  It is just that it is an application choice of when to close or determine if there's an error etc....

**Comment by roguh** [comment]
I made a library for this https://www.npmjs.com/package/nats-request-multi

**Comment by roguh** [comment]
I also made a Python library https://pypi.org/project/nats-request-asap/

I might rename it to NATS request multi.

**Comment by aricart** [comment]
this implemented in the javascript libraries - https://nats-io.github.io/nats.deno/interfaces/NatsConnection.html#requestMany
