### ISSUE TITLE
waitOnFirstConnect and timeout

### ISSUE THREAD

**Issue by tkjwa** [nats-io/nats.js#439]
Hello, 
I've been making some tests and i'm having some issue when using the `waitOnFirstConnect` together with the `timeout` option.
The script is waiting forever and does not seem to respect the timeout. Here is simple example script
```JavaScript
const NATS = require("nats");

async function run() {
    const nc = await NATS.connect({
        servers: 'nats://localhost:4222',
        waitOnFirstConnect: true,
        timeout: 10000,
    });
    console.log('connected');

    nc.closed().finally(() => {
        console.log(`Connection definitely closed`);
    });
}

run();
```

Expected: finish after 10 seconds when no nats server is running
Actual: hangs forever

Am i missing something or do you think there could be a bug somewhere ?

Thank you for your help

**Comment by aricart** [comment]
waitOnFirstConnect will keep trying to dial.  The timeout option on the context of connecting,  triggers if the handshake with server doesn't complete in the specified time. In your case I think you don't want waitOnFirstConnect.

**Comment by tkjwa** [comment]
Thank you @aricart , I've been trying different combination of options but either the script fails right away, or it hangs forever. I can easily create a simple retry in my own code so not a big deal.

**Comment by aricart** [comment]
@tkjwa in your case max reconnect of 5 with 2 sec wait interval should do what you want.

**Comment by tkjwa** [comment]
@aricart, again thanks for your help, I've been trying the following test script with the options you suggested

```JavaScript
const NATS = require("nats");

async function run() {
    const nc = await NATS.connect({
        servers: 'nats://localhost:4222',
        reconnectTimeWait: 2000,
        maxReconnectAttempts: 5,
    });
    console.log('connected');

    nc.closed().finally(() => {
        console.log(`Connection definitely closed`);
    });
}

run();
```

When no nats server is running I get the following error right away, no 10 sec waiting:
```
node test-nats.js
/home/jwalab/airlock/node_modules/nats/lib/nats-base-client/error.js:98
        return new NatsError(m, code, chainedError);
               ^

NatsError: CONNECTION_REFUSED
    at Function.errorForCode (/home/jwalab/airlock/node_modules/nats/lib/nats-base-client/error.js:98:16)
    at NodeTransport.<anonymous> (/home/jwalab/airlock/node_modules/nats/lib/src/node_transport.js:82:52)
    at Generator.throw (<anonymous>)
    at rejected (/home/jwalab/airlock/node_modules/nats/lib/src/node_transport.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'CONNECTION_REFUSED',
  chainedError: Error: connect ECONNREFUSED 127.0.0.1:4222
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 4222
  }
}
```

**Comment by aricart** [comment]
That is a bug then.  Will fix Monday.

**Comment by aricart** [comment]
@tkjwa just verified with the other clients, the logic you want is not currently supported by the clients.
This is the current behavior:

- if `waitOnFirstConnect` is provided, the server will continue to attempt to connect forever - the only way to bail out of loop is for you set up your own timer for the initial connection and abort, after the initial connect, the options for `reconnectTimeWait`, and `maxReconnectAttempts` will be honored. So if you disconnect, it will attempt 5 times waiting 2 seconds between attempts.

If `waitOnFirstConnect` is not provided, the client will go through its list of servers, and if it fails to connect to any of the connection will fail. All of our internally supported clients work in this way. Note that in this case, there's no `reconnect` attempt, the client has never connected.

In a service implementation, this makes sense, if the connection is not available, you would likely not want any other functionality to enable, as you may never be able to connect, even if after starting you can sustain a brief disruption while the service reconnects to any of the other cluster members.

**Comment by tkjwa** [comment]
@aricart Thank you very much for your time and detailed explanation !
