### ISSUE TITLE
NatsError: CONNECTION_REFUSED

### ISSUE THREAD

**Issue by CloudWoR** [nats-io/nats.js#440]
my project used the framework of nestjs, I tried to start a micro service based on NATs according to the configuration mode recommended by the official, and the result showed natserror: connection_ Refuse, how should I set it?
## this is my branch of github：https://github.com/CloudWoR/nestAssest.git
please select the branch of minimum, thanks.

**Comment by aricart** [comment]
Can you provide a sample on how you are building the connection, rather than ask me to debug your project?

Are you trying to connect via NATS websockets?

**Comment by CloudWoR** [comment]
sorry,please cd the base dir and npm install,open two shell window,shell one please run npm run dev:server,shell two please run npm run dev:broker-nats。if no error,shell one will publish a request on shell two.

**Comment by CloudWoR** [comment]
> 您能否提供有关如何构建连接的示例，而不是让我调试您的项目？
> 
> 您是否尝试通过 NATS websockets 进行连接？

thank you very much,I'm stupida，not start the nats server on docker container 😊.
