### ISSUE TITLE
Provide an example for authenticator using nkeys

### ISSUE THREAD

**Issue by kosecki123** [nats-io/nats.js#449]
Documentation on how to use nkey and nonce signing published here https://docs.nats.io/developing-with-nats/security/nkey for js/typescript client is outdated. Latest (`2.2.0`) have the definition for `authenticator` function to achieve that functionality.

Now, when trying to implement it as below it looks like `sig` object is sent as the uint8 array and needs some compacting function but I was not able to find any (in ants and nkeys.js libs)

Server logs error is `json: cannot unmarshal object into Go struct field ClientOpts.sig of type string`

```
const authenticator = (nonce) => {
  const sk = fromSeed(
    Buffer.from("SUAEL6GG2L2HIF7DUGZJGMRUFKXELGGYFMHF76UO2AYBG3K4YLWR3FKC2Q")
  );

  const sig = sk.sign(Buffer.from(nonce));

  return {
    nkey: sk.getPublicKey(),
    sig,
  };
}
```

**Comment by aricart** [comment]
@kosecki123 yes the examples there are outdated. I will have updates for them soon.
In the meanwhile, check this out:
https://github.com/nats-io/nats.js#authenticators

**Comment by kosecki123** [comment]
> @kosecki123 yes the examples there are outdated. I will have updates for them soon.
> 
> In the meanwhile, check this out:
> 
> https://github.com/nats-io/nats.js#authenticators
> 
> 
> 
> 

Thanks, all good, works as expected.
