### ISSUE TITLE
Best approach for handling messages parallely

### ISSUE THREAD

**Issue by Blitss** [nats-io/nats.js#450]
I want to achieve parallel message handling using Jetstream. What would you say is the best way to go around this?
I thought about something like this (pseudo-code), but it doesn't look like the most reliable way.

```typescript
import { consumerOpts, DeliverPolicy, createInbox, JetStreamClient, JSONCodec } from 'nats'
import PQueue                                                                   from 'p-queue'

export interface ConsumerOptions {
  durable: string
  policy?: DeliverPolicy
}

const createConsumer = ({ durable, policy }: ConsumerOptions) => {
  const opts = consumerOpts({
    deliver_policy: policy || DeliverPolicy.New,
  })

  opts.durable(durable)
  opts.manualAck()
  opts.ackExplicit()
  opts.deliverTo(createInbox())
  // Here I should adjust the number of inflight messages. Not sure which one to use?
  // opts.maxAckPending(10)
  // opts.maxWaiting(10)

  return opts
}

class MessageEventHandler {
  jetStream: JetStreamClient

  protected async handleEvent(event: unknown) {
    // ...

    await new Promise(resolve => setTimeout(resolve, 2000))

    event.ack()
  }

  async handleMessages() {
    const encoder = JSONCodec<Record<string, any>>()
    const subscription = await this.jetStream.subscribe(
      'events.messages.created',
      createConsumer({
        durable: 'updateSomething',
      })
    )
    // Promise queue which allows only to handle 5 messages at once
    const promiseQueue = new PQueue({ concurrency: 5 })

    for await (const message of subscription) {
      const decoded = encoder.decode(message.data)

      promiseQueue.add(() =>
        this.handleEvent({
          ...message,
          ...decoded,
        })
      )
    }
  }
}

```

In Nats Streaming (which had a callback-based model of processing the messages) I would just use the promise queue and adjust the number of the inflight messages. This way I would just get the number of messages I need. In the example above I use a similar way.

What are your thoughts on how this case should be handled with Jetstream and iterators?

**Comment by aricart** [comment]
Not quite sure what you are trying to accomplish, are you offloading to workers?

You'll want to take a look at:

https://github.com/nats-io/nats.deno/blob/main/jetstream.md#processing-messages

There are several options:

- `js.pull(stream, durable)` will return a single message (if you have different workers, possibly each could do their own pull()) - https://github.com/nats-io/nats.deno/blob/main/jetstream.md#requesting-a-single-message
- If you are trying to do the coordination, say you want to pull at most N messages, then you can do `js.fetch(stream, durable, {batch: 10, expires: 30*1000})` - this will return an iterator that will at most feed you 10 messages, but the iterator will remain open for 30 seconds if 10 are not available. Note you don't have to process your messages in the iterator, the iterator really is just a buffer for the returned messages, which allows for additional messages to come in if they arrive after the request but before the expiration timer kicks in. This allows you to retrieve a batch of messages without spamming the server when no messages are available.
- `js.pullSubscribe()` is similar to pull and fetch but in the context of a subscription. The subscription remains open but you have to 'pull' (you can specify the batch size) to get it to send you messages. https://github.com/nats-io/nats.deno/blob/main/jetstream.md#pull-subscriptions.
- If you use standard `js.subscribe()` with a deliver subject, the server will send messages to you which you may not be able to cope with (you can set consumer `maxAckPending`, which will throttle the server). Note that if you are using queue subscribers this number is shared by all queue members and there's no guarantee that the workers will get them evenly distributed.

If you are doing what I think you are doing, I would go with either js.pullSubscribe() or js.fetch().

**Comment by Blitss** [comment]
@aricart thank you for your input! I'll experiment with those options to see which is one is the best.

> Not quite sure what you are trying to accomplish, are you offloading to workers?

This could be one of the usage cases, yes. Say, I have 1000 pending messages in the queue which should be handled by the queue subscribers. If I use async iterators, that would mean that each message is sequentially, one by one. The message must be handled before moving on to the next. 

What I want to do instead is handle those events concurrently, e.g. at most 10 at a time per one queue subscriber. That would mean I need no more than 10 messages at the time and other messages could be offloaded to the other workers (queue subscribers). So if I have 2 workers, it would mean I have the bandwidth of 20 messages at once, 3 = 30, and so on.

> Note that if you are using queue subscribers this number is shared by all queue members

That's what I was afraid of and what is making `js.subscribe()` unviable for this situation. I guess there is no way to specify how many unacknowledged messages one subscriber could get, right?

**Comment by aricart** [comment]
If you do a pull subscriber, you can set the pace for the message consumption. The server won't give you any messages that are in flight. The pull consumer is effectively for your usecase.
