### ISSUE TITLE
duplicate_window in StreamConfig not working correctly with value of zero

### ISSUE THREAD

**Issue by yartman** [nats-io/nats.js#452]
I tried to create a stream with duplicate_window is set to 0 but window remained 2min for the stream.
It works fine with values other than zero.

**Comment by ripienaar** [comment]
You cannot disable the window, so it defaults to 2 minutes when not set (0 is not set)

**Comment by yartman** [comment]
but `--dupe-window="0s"`  is used in nats cli
https://docs.nats.io/jetstream/administration/streams

**Comment by ripienaar** [comment]
yeah that's misleading, but it can't be disabled.

https://github.com/nats-io/nats-server/blob/765d39a2b6b09816985418e48bdfb9f93226dd18/server/stream.go#L793-L798
