### ISSUE TITLE
How to have multiple subscription Instance on a single subject

### ISSUE THREAD

**Issue by abiram1991** [nats-io/nats.js#453]
I want to run more than one subscription instance against the subject, so that if any subscription instance getting failed or disturbed then remaining instance will able to do the operation and note that each and every instance should receive only one msg at time in the sense one msg should be received only once in any one subscribed instance and not any other subscribed instance.

How can I achieve with the help of nats jetstream?

nats jetstream version - 2.5.0
nats npm version - 2.2.0

Note - Same msg not to share for multiple subscription

**Comment by derekcollison** [comment]
Pull based consumers can have as many applications running as you wish.
If you prefer push based, you can bind multiple queue subscribers to a single push consumer.

**Comment by abiram1991** [comment]
Ok...How can i create Pull based consumer?

Give me a link with any sample.

**Comment by aricart** [comment]
https://github.com/nats-io/nats.deno/blob/main/examples/jetstream/07_pullsub.ts
