### ISSUE TITLE
Connect using websocket ?

### ISSUE THREAD

**Issue by game5413** [nats-io/nats.js#454]
Hello, i want ask a question. I'm enabling websocket connection on nats-server config, can this library connect using websocket protocol instead standard protocol ? i'm already tried change server url from `localhost:4222` into `ws://localhost:${PORT}` but got nothing response.

My Environtment:
node: 14.17.5
natsjs: ^2.2.0
nats-server: docker alpine:latest

**Comment by derekcollison** [comment]
JS/TS and Go clients can use websockets. Others will follow.
You can also use a leafnode connection between servers that can utilize wss.

**Comment by aricart** [comment]
@game5413 we socket transport runs in a different port.  To enable it, please take a look here:

https://docs.nats.io/nats-server/configuration/websocket/websocket_conf

**Comment by game5413** [comment]
> @game5413 we socket transport runs in a different port. To enable it, please take a look here:
> 
> https://docs.nats.io/nats-server/configuration/websocket/websocket_conf

I'm already set that port to another and not using tls for local dev, still got no response, if i'm add timeout to config connect the error was timeout, but if connect using standard protocol, it working properly

```js
import { connect } from 'nats';

const client = await connect({
    servers: 'ws://localhost:4222',
    user: 'someuser',
    pass: 'somepassword'
});
```

**Comment by game5413** [comment]
Also already tried another client, using this lib [nats.ws](https://github.com/nats-io/nats.ws) and it's working. I'm assume that this client not support for connecting using websocket protocol, am i right ?

**Comment by aricart** [comment]
The config for me looks like this - note that `no_tls` - that is required for the server to support non-tls connections.

```
websocket 
{
 	port: 9191
 	no_tls: true
}
```
For docker, since the websocket is not started automatically: 

```bash
docker run -it --rm  -v /tmp:/container -p 9191:9191 nats -c /container/nats.conf
```

On your connect:

```javascript
const nc = await connect({ servers: 'ws://127.0.0.1:9191', debug: true })
```

```bash
node examples/ws-sub.js
connected to NATS!
published a message to `hello`
listening for request on `help`
making a request to `help`
got response 'I can help nats request'
closed the connection
```

The program I used:
```
// change to import if you want to run on the broser
const { connect, StringCodec } = require("../nats.cjs");
// these too lines only if you are running ws on node
const browserEnv = require("browser-env");
browserEnv();

// add an entry to the document
function addEntry(s) {
  console.log(s);
}

const sc = StringCodec();

const init = async function () {
  // create a connection
  const nc = await connect({ servers: 'ws://127.0.0.1:9191', debug: true })
  addEntry('connected to NATS!');

  // simple publisher
  nc.publish('hello', sc.encode('nats'))
  addEntry('published a message to `hello`');

  // simple subscriber, if the message has a reply subject
  // send a reply
  const sub = await nc.subscribe('help');
  (async () => {
    addEntry('listening for request on `help`');
    for await (const m of sub) {
      m.respond(sc.encode(`I can help ${sc.decode(m.data)}`));
    }
  })().then()

  // request data - requests only receive one message
  // to receive multiple messages, create a subscription
  addEntry('making a request to `help`');
  const msg = await nc.request('help', sc.encode('nats request'))

  addEntry(`got response '${sc.decode(msg.data)}'`);

  // close the connection
  nc.close();
  addEntry('closed the connection');
}
init();
```

**Comment by game5413** [comment]
> The config for me looks like this - note that `no_tls` - that is required for the server to support non-tls connections.
> 
> ```
> websocket 
> {
>  	port: 9191
>  	no_tls: true
> }
> ```

Yeah, i'm already set the value of `no_tls` to **true**
> 
> For docker, since the websocket is not started automatically:
> 
> ```shell
> docker run -it --rm  -v /tmp:/container -p 9191:9191 nats -c /container/nats.conf
> ```
> 
and also already replace my default configuration using volume

> On your connect:
> 
> ```js
> const nc = await connect({ servers: 'ws://127.0.0.1:9191', debug: true })
> ```
> 
> ```shell
> node examples/ws-sub.js
> connected to NATS!
> published a message to `hello`
> listening for request on `help`
> making a request to `help`
> got response 'I can help nats request'
> closed the connection
> ```
> 
> The program I used:
> 
> ```
> // change to import if you want to run on the broser
> const { connect, StringCodec } = require("../nats.cjs");
> // these too lines only if you are running ws on node
> const browserEnv = require("browser-env");
> browserEnv();
> 
> // add an entry to the document
> function addEntry(s) {
>   console.log(s);
> }
> 
> const sc = StringCodec();
> 
> const init = async function () {
>   // create a connection
>   const nc = await connect({ servers: 'ws://127.0.0.1:9191', debug: true })
>   addEntry('connected to NATS!');
> 
>   // simple publisher
>   nc.publish('hello', sc.encode('nats'))
>   addEntry('published a message to `hello`');
> 
>   // simple subscriber, if the message has a reply subject
>   // send a reply
>   const sub = await nc.subscribe('help');
>   (async () => {
>     addEntry('listening for request on `help`');
>     for await (const m of sub) {
>       m.respond(sc.encode(`I can help ${sc.decode(m.data)}`));
>     }
>   })().then()
> 
>   // request data - requests only receive one message
>   // to receive multiple messages, create a subscription
>   addEntry('making a request to `help`');
>   const msg = await nc.request('help', sc.encode('nats request'))
> 
>   addEntry(`got response '${sc.decode(msg.data)}'`);
> 
>   // close the connection
>   nc.close();
>   addEntry('closed the connection');
> }
> init();
> ```
i'm assume that your **connect** function was imported from [nats.ws](https://github.com/nats-io/nats.ws) right ? because i'm only can connected using websocket protocol using that client. If i'm using this client [nats.js](https://github.com/nats-io/nats.js) the problem was i'm mentioned at first post.

**Comment by aricart** [comment]
correct - if you installed as `npm install nats.ws`, then your import will be:
```
import { connect, StringCodec } from "./node_modules/nats.ws/nats.js";
```

If you are using node, as I was, the import was from the `./node_modules/nats.ws/nats.cjs`

**Comment by aricart** [comment]
Be sure to fully read:
https://github.com/nats-io/nats.ws/blob/master/README.md 
and https://github.com/nats-io/nats.ws/blob/master/README.md#installation

If you are running on the browser, you'll also want to take a peek at:
https://github.com/nats-io/nats.ws/blob/master/developer_notes.md
