### ISSUE TITLE
Redelivery with consumer queue groups

### ISSUE THREAD

**Issue by AndreMaz** [nats-io/nats.js#455]
I'm testing JetStream consumer groups and I have a question regarding the redelivery.  I'm using `nats-server: v2.6.0` and `nats.js: v2.2.0`

My scenario looks like this:

![image](https://user-images.githubusercontent.com/9802754/134669780-9c48dbe2-b006-48d6-9e5c-53749620d60c.png)

In this scenario the publisher creates a generates a burst of 10 messages (`{ id: 0 }`, ..., `{ id: 9 }`).

**Expected behavior** 
All messages that **sub1** rejects to be redelivered.

**Actual behavior** 
Some of the messages being redelivered.

Here are `consumerOpts` of each subscription
**sub1**
```js
ConsumerOptsBuilderImpl {
  stream: '',
  mack: true,
  config: {
    name: '',
    deliver_policy: 'new',
    ack_policy: 'all',
    ack_wait: 30000000000,
    replay_policy: 'instant',
    deliver_group: 'test_unstable_topic',
    durable_name: 'mygroup',
    deliver_subject: 'sub1.test.unstable.topic',
    max_deliver: 5
  },
  qname: 'test_unstable_topic',
  callbackFn: [AsyncFunction (anonymous)]
}
```

**sub 2**
```js
ConsumerOptsBuilderImpl {
  stream: '',
  mack: true,
  config: {
    name: '',
    deliver_policy: 'new',
    ack_policy: 'all',
    ack_wait: 30000000000,
    replay_policy: 'instant',
    deliver_group: 'test_unstable_topic',
    durable_name: 'mygroup',
    deliver_subject: 'sub2.test.unstable.topic',
    max_deliver: 5
  },
  qname: 'test_unstable_topic',
  callbackFn: [AsyncFunction (anonymous)]
}
```

The `consumerOpt.callback()` is defined here: https://github.com/moleculerjs/moleculer-channels/blob/e61c4596db6d57145e960b785fb85868737326fa/src/adapters/nats.js#L173-L247

and here are the logs:

![image](https://user-images.githubusercontent.com/9802754/134672471-681f0679-f741-4d87-b850-72ecab864f4b.png)

Logs explanation:
- `{ id: 0 }` - delivered to **sub1**, got "NACKed" via `message.nack()` and was NOT redelivered.
- `{ id: 1 }` - delivered to **sub2** and logged successfully
- `{ id: 2 }` - delivered to **sub2** and logged successfully
- `{ id: 3 }` - delivered to **sub2** and logged successfully
- `{ id: 4 }` - delivered to **sub2** and logged successfully
- `{ id: 5 }` - delivered to **sub2** and logged successfully
- `{ id: 6 }` - delivered to **sub2** and logged successfully
- `{ id: 7 }` - delivered to **sub1**, got "NACKed" via `message.nack()` and was redelivered again to **sub1** and got "NACKed" again. However, after that it was not redelivered. Even with the `max_deliver: 5` set.
- `{ id: 8 }` - delivered to **sub1**, got "NACKed" via `message.nack()` and was redelivered to **sub2** and then logged successfully
- `{ id: 9 }` - delivered to **sub1**, got "NACKed" via `message.nack()` and was redelivered to **sub2** and then logged successfully

My question is regarding the messages with id=0, id=7, id=8 and id=9. Can you explain why their behavior differs? Is this a config issue?

---

Also, how the load balancing is being done in JetStream? I didn't find any info about it in the docs.
The only reference I found was in [Queue Groups](https://docs.nats.io/nats-concepts/queue) which states that `one member of the group is chosen randomly to receive the message`

However, in the image below the message is being constantly redelivered to the same consumer. It seems that load balancing is not working properly
![image](https://user-images.githubusercontent.com/9802754/134674172-41772c60-05e5-4f75-aedf-fba7f8ffddf1.png)

**Comment by aricart** [comment]
I think the issue is you see is due to your `AckPolicy.All` - What that policy does is ack all sequences below it. TBH, the policy you want is `AckPolicy.Explicit`. 

The part that seems unexpected to me is that ack'ing shouldn't affect a nack'ed message unless it was in flight. Worse, I am not sure what the meaning of `AckPolicy.All` is in the context of a queue subscriber. I am going to do a test and ask a couple of questions around.

**Comment by AndreMaz** [comment]
Thank you for the quick answer.
Tested here with ack explicit and it doesn't seem to help
```js
ConsumerOptsBuilderImpl {
  stream: '',
  mack: true,
  config: {
    name: '',
    deliver_policy: 'new',
    ack_policy: 'explicit', // <---- changed this config
    ack_wait: 30000000000,
    replay_policy: 'instant',
    deliver_group: 'test_unstable_topic',
    durable_name: 'mygroup',
    deliver_subject: 'desktop-u6prr0v-2173.sub2.test.unstable.topic',
    max_ack_pending: undefined,
    max_deliver: 5
  },
  qname: 'test_unstable_topic',
  callbackFn: [AsyncFunction]
}
```

Here's the result:
![image](https://user-images.githubusercontent.com/9802754/134684661-4c8c70e8-1c87-440c-a4df-ff5ed8358033.png)

Something happened with messages with ids = 5,6,7,9

**Comment by aricart** [comment]
OK, yes I verified it:

If you `nak()`, messages will be re-delivered, but the minute that there's an `ack()` the redeliveries will stop. And all messages below that sequence number will be acknowledged.

```javascript
const { ns, nc } = await setup(jetstreamServerConf({}, true));
  if (await notCompatible(ns, nc, "2.3.5")) {
    return;
  }
  const { stream, subj } = await initStream(nc);
  const js = nc.jetstream();

  const opts = consumerOpts();
  opts.ackAll();
  opts.queue("q");
  opts.durable("n");
  opts.deliverTo(createInbox());
  opts.callback((_err, m) => {
    if (m) {
      if(m.info.redelivered) {
        console.log(`R: ${m.seq}`);
      }
      if(m.seq === 100) {
        m.ack();
      }
      if(m.seq % 3 === 0) {
        m.nak();
      }
    }
  });

  const sub = await js.subscribe(subj, opts);
  const sub2 = await js.subscribe(subj, opts);

  for (let i = 0; i < 100; i++) {
    await js.publish(subj, Empty);
  }
  await nc.flush();
  await sub.drain();
  // await sub2.drain();

  assert(sub.getProcessed() > 0);
  assert(sub2.getProcessed() > 0);
  assert(sub.getProcessed() + sub2.getProcessed() > 100);

  const jsm = await nc.jetstreamManager();
  const ci = await jsm.consumers.info(stream, "n");
  console.log(ci);

  await cleanup(ns, nc);
  ```


```javascript
{
  type: "io.nats.jetstream.api.v1.consumer_info_response",
  stream_name: "6M7L1RK5TBV1MLB4F729IP",
  name: "n",
  created: "2021-09-24T13:45:37.106535Z",
  config: {
    durable_name: "n",
    deliver_subject: "_INBOX.6M7L1RK5TBV1MLB4F729ZX",
    deliver_group: "q",
    deliver_policy: "all",
    ack_policy: "all",
    ack_wait: 30000000000,
    max_deliver: -1,
    filter_subject: "6M7L1RK5TBV1MLB4F729IP.A",
    replay_policy: "instant",
    max_ack_pending: 20000
  },
  delivered: { consumer_seq: 133, stream_seq: 100, last_active: "2021-09-24T13:45:37.755238Z" },
  ack_floor: { consumer_seq: 133, stream_seq: 100, last_active: "2021-09-24T13:45:37.762339Z" },
  num_ack_pending: 0,
  num_redelivered: 0,
  num_waiting: 0,
  num_pending: 0,
  cluster: { leader: "NDRA22KTJV3V7EU4VVEVV3TPKSDVWADPSJULWUGHPUH6QQAYDW3YXDIN" },
  push_bound: true
}
```

On my current server the only unexpected part is that `nak()` messages don't get counted as re-delivered. But they are, because the number of messages sent is 133 vs 100, and additional probing into actual processed shows on client getting 77 and and the other 56.

**Comment by aricart** [comment]
For your use-case you really want to `AckPolicy.Explicit`.

**Comment by aricart** [comment]
> Thank you for the quick answer.
> Tested here with ack explicit and it doesn't seem to help
> 
> ```js
> ConsumerOptsBuilderImpl {
>   stream: '',
>   mack: true,
>   config: {
>     name: '',
>     deliver_policy: 'new',
>     ack_policy: 'explicit', // <---- changed this config
>     ack_wait: 30000000000,
>     replay_policy: 'instant',
>     deliver_group: 'test_unstable_topic',
>     durable_name: 'mygroup',
>     deliver_subject: 'desktop-u6prr0v-2173.sub2.test.unstable.topic',
>     max_ack_pending: undefined,
>     max_deliver: 5
>   },
>   qname: 'test_unstable_topic',
>   callbackFn: [AsyncFunction]
> }
> ```
> 
> Here's the result:
> ![image](https://user-images.githubusercontent.com/9802754/134684661-4c8c70e8-1c87-440c-a4df-ff5ed8358033.png)
> 
> Something happened with messages with ids = 5,6,7,9

Did you reset your server the consumer configuration/policy etc won't change once created in the server.

**Comment by aricart** [comment]
Grab the consumer configuration by asking for it, also list the number of consumers for the stream, there should be one - on your config there you have different delivery subjects, but they are not. The durable is written with the first deliver_to, and when the client grabs the consumer, it uses whatever is already on the server.

```
const jsm = await nc.jetstreamManager();
const ci = await jsm.consumers.info(stream, "n");
```

**Comment by AndreMaz** [comment]
> Did you reset your server the consumer configuration/policy etc won't change once created in the server.

Ups, sorry. 

After resetting the server, things seem to be working fine
![image](https://user-images.githubusercontent.com/9802754/134694181-3b7715c3-9484-401e-9335-9ce2b4702c51.png)

Here's my consumer info:
```js
{
  type: 'io.nats.jetstream.api.v1.consumer_info_response',
  stream_name: 'test_unstable_topic',
  name: 'mygroup',
  created: '2021-09-24T14:43:35.5786762Z',
  config: {
    durable_name: 'mygroup',
    deliver_subject: 'desktop-u6prr0v-2838.sub1.test.unstable.topic',
    deliver_group: 'test_unstable_topic',
    deliver_policy: 'new',
    ack_policy: 'explicit',
    ack_wait: 30000000000,
    max_deliver: -1,
    filter_subject: 'test.unstable.topic',
    replay_policy: 'instant',
    max_ack_pending: 20000
  },
  delivered: {
    consumer_seq: 21,
    stream_seq: 10,
    last_active: '2021-09-24T14:43:37.0620984Z'
  },
  ack_floor: {
    consumer_seq: 21,
    stream_seq: 10,
    last_active: '2021-09-24T14:43:37.0621028Z'
  },
  num_ack_pending: 0,
  num_redelivered: 0,
  num_waiting: 0,
  num_pending: 0,
  cluster: {
    leader: 'NDWYJZQCRJRGBOS7DCC36P2MQRWYRXWRBYODQ4TMNHJ5NGOIY43GV7OK'
  },
  push_bound: true
}
```

and stream info 
```js
{
  type: 'io.nats.jetstream.api.v1.stream_info_response',
  config: {
    name: 'test_unstable_topic',
    subjects: [ 'test.unstable.topic' ],
    retention: 'limits',
    max_consumers: -1,
    max_msgs: -1,
    max_bytes: -1,
    max_age: 0,
    max_msgs_per_subject: -1,
    max_msg_size: -1,
    discard: 'old',
    storage: 'file',
    num_replicas: 1,
    duplicate_window: 120000000000
  },
  created: '2021-09-24T14:43:35.5646832Z',
  state: {
    messages: 10,
    bytes: 570,
    first_seq: 1,
    first_ts: '2021-09-24T14:43:37.0227984Z',
    last_seq: 10,
    last_ts: '2021-09-24T14:43:37.0229304Z',
    consumer_count: 1
  }
}
```

Thank you for the help 👍
