### ISSUE TITLE
Json payload nats 2.2

### ISSUE THREAD

**Issue by dfyz011** [nats-io/nats.js#457]
Hi!
I am currently swapping from ts-nats to nats 2.2
How can I decode all messages data to json now?
Examples for JavaScript and TypeScript at https://docs.nats.io/developing-with-nats/receiving/structure aren't working, because of no argument(json or payload) at ConnectionOptions type.
I know that I can use JSONCodec, but I didn't find the way to provide it somewhere to decode all messages

**Comment by aricart** [comment]
@dfyz011 the payloads are always byte arrays. If you want to decode it you have to use the decoder in your callback/iterator as shown here: https://github.com/nats-io/nats.js#publish-and-subscribe and here https://github.com/nats-io/nats.js/blob/master/migration.md#payloads.

This approach promotes safety in the library. If a different client sends something that cannot be decoded as JSON, ie a payload like `hello` (JSON would be `"hello"`) the exception happens in your code not in the library. Also, the previous client had the problem that encoding/decoding was global to the client so in/out payloads were always required to have JSON.

**Comment by aricart** [comment]
@dfyz011 there's an internal mechanism that may be interesting to you, that I implemented for JetStream. It is a "typed" subscription, which is created by passing a connection, a subject and several options, the important being `adapter` which then converts the payload of the message to whatever is desired. The `TypedSubscription` is not exposed (but should be available if you add a warning suppression).

https://github.com/nats-io/nats.deno/blob/main/nats-base-client/typedsub.ts

Note the above is still internal, but my thoughts are that in a future release `subscribe` will let you pass the adapter and return one of those. For publishing, there's no equivalent.
