### ISSUE TITLE
Programatically getting all messages from a JetStream stream

### ISSUE THREAD

**Issue by ruidfigueiredo** [nats-io/nats.js#469]
What would a reasonable way of doing the same as `nats str view streamName --subject filter_subject` programmatically be?

I've been using `JetStreamManager.streams.info(streamName)` to get the number of messages in the stream to then use `jetstreamClient.fetch(streamName, temporaryDurableConsumerThatUsesFilterSubject, { batch: numberOfMessagesInStream, no_wait: true})` to get to all messages.

And after this, deleting the `temporaryDurableConsumerThatUsesFilterSubject`

Are there any dangers that might not be obvious in doing this, or is this a reasonable approach?

This is to enable projections over a specific stream, for example:  users.someUserId that has a message of type Registered, and then EmailConfirmed from which I can "project" `{hasUserConfirmedEmail: true}`

**Comment by ripienaar** [comment]
You probably dont want to pull the full stream in one go as it could overwhelm our client.  Do it in batches of 10 or whatever.

Using a durable is annoying, but its the only way we can do pull.

**Comment by derekcollison** [comment]
Maybe consider an ordered push consumer?

**Comment by ruidfigueiredo** [comment]
Hi @derekcollison 

Would you mind elaborating on that a little bit more?

From my understanding an ordered push consumer is what you'd get by creating a subscription, something like this:

        const opts = consumerOpts()
        opts.deliverTo(createInbox())
        opts.ackExplicit();
        opts.manualAck();
        opts.durable(consumerName)
        const subscription = await jetstreamClient.subscribe('theFilter', opts)
        for await (let message of subscription) {
         ...
         
         
This is "open ended", it will continue waiting for messages until explicitly told to stop (subscription.unsubscribe() or destroy()).

The goal here is not that, it's to get all messages that are currently now in the stream (filtered by a subject) without waiting for more.

AFAIK jetstreamClient.fetch is the only way to do that, and that requires a pull consumer

**Comment by aricart** [comment]
Really what you are asking is given a stream I want to get the messages that are there now, but then stop.
The break condition for you is when the consumer doesn't have any more pending messages. So If you look at the info for the message `msg.info.pending` when that is `0` your consumer has received all messages known.

**Comment by aricart** [comment]
`Also - if you have an ordered consumer - you need to do `opts.orderedConsumer()` - note that ordered consumers are not durable, the ordered consumer guarantees that you get all the messages in order, possibly re-creating the consumer if something goes out of sequence.

**Comment by aricart** [comment]
@ruidfigueiredo there are a few problems with the above approach including that when you are fetching, the request is asking for ALL messages in the stream. If you have more than a few, your client won't be able to process them quickly enough as the server will flood you messages. This then starts a sequence of events where the server missing responses will resend some messages (so now you'll get duplicates queued up). 

If you wanted to go with fetch, you should ask for a few messages, you can always tell where there are no more by looking at the `m.info.pending`.

The ordered consumer does a lof of work behind the scenes. You will get messages pushed, but it also uses flow control, so the server will back off. The ordered consumer also doesn't use ack, so the server won't go there are outstanding messages and resend. 

If you want to list messages in a stream, it seems reasonable to limit how many you will get/process in one go - if you are not dealing with a large volume, then it should be OK.

**Comment by ruidfigueiredo** [comment]
@aricart Thanks

The ordered consumer does seem like the best approach. The only issue I'm having with it is when there are no messages in the subject I'm interested in (e.g. `user.john` for a stream with subjects `users.*` for example). 

The subscription using the ordered consumer will just hang waiting for the first message (I don't have access to message.info.pending before the first message)

**Comment by ruidfigueiredo** [comment]
Apologies, as I typed that last message I went and checked again and the subscription itself has a `getPending` method, 

This seems to be exactly what I need:
```
const consumerOptions = consumerOpts()
consumerOptions.orderedConsumer()
const getAllMessagesSubscription = await jsc.subscribe(subject, consumerOptions)

if (getAllMessagesSubscription.getPending() === 0)
    return [];

let messages = []
for await (let m of getAllMessagesSubscription) {
    messages.push({ ...jc.decode(m.data), seq: m.seq })
    if (m.info.pending === 0)
        getAllMessagesSubscription.destroy()
}

return messages;
```
The destroy might not be necessary given that the consumer will be ephemeral, but I guess it doesn't hurt

**Comment by aricart** [comment]
You can get the consumer info from the subscription and check the count of pending messages.  And stop subscription in it has zero pending messages

**Comment by aricart** [comment]
You can also get the stream info and see if there are messages...

**Comment by ruidfigueiredo** [comment]
Just mentioning this extra bit of information in case someone else bumps into this issue.
When doing this:
```
        const opts = consumerOpts()
        opts.orderedConsumer()
        
        const subscription = await jsc.subscribe(subject, opts)
```

**Comment by aricart** [comment]
you do NOT want to use subscription to see - pending/processed/or received. These numbers are related to actual messages that might have flowed through the subscription. You want to look at the consumer info.
if you are filtering subjects you are correct.- you cannot look at the stream, but the consumer will tell you how many messages are pending for it.

**Comment by ruidfigueiredo** [comment]
@aricart I've just discovered that the hard way, looking at processed, received and pending in the subscription is not a reliable way to do this (sometimes they are all 0 even when there are messages).

Can you elaborate where to look in the consumer, what I'm currently going with is this:

`const hasAnyMessages = !(await getAllMessagesSubscription.consumerInfo()).delivered.last_active)`

looks really convoluted, but that's all I was able to find

**Comment by ruidfigueiredo** [comment]
Just sharing this in support of the idea of picking `last_active` or `num_pending` (which I didn't noticed initially) as a way to check if there are any messages for stream using the subject as a filter, here's how the consumer info looks like if there are no messages:

```
{
  type: 'io.nats.jetstream.api.v1.consumer_info_response',
  stream_name: 'test',
  name: 'xrTV72Y1',
  created: '2021-12-14T10:18:17.606833603Z',
  config: {
    deliver_subject: '_INBOX.NT8I3LGDAR40JL2JO1ZQUK',
    deliver_policy: 'all',
    ack_policy: 'none',
    ack_wait: 79200000000000,
    max_deliver: 1,
    filter_subject: 'test.099',
    replay_policy: 'instant',
    idle_heartbeat: 5000000000,
    flow_control: true
  },
  delivered: { consumer_seq: 0, stream_seq: 110007 },
  ack_floor: { consumer_seq: 0, stream_seq: 0 },
  num_ack_pending: 0,
  num_redelivered: 0,
  num_waiting: 0,
  num_pending: 0,
  cluster: {
    leader: 'NCRYGATIOMNPRZGULGWDYEZJ7QXXV5QXFJKENABQW6Y2BYGBQPAFQL3G'
  },
  push_bound: true
}
```
And with messages:
```
{
  type: 'io.nats.jetstream.api.v1.consumer_info_response',
  stream_name: 'test',
  name: 'ph53AXHs',
  created: '2021-12-14T00:46:55.560154734Z',
  config: {
    deliver_subject: '_INBOX.1TN8WU769WFZBYW3AT1NGY',
    deliver_policy: 'all',
    ack_policy: 'none',
    ack_wait: 79200000000000,
    max_deliver: 1,
    filter_subject: 'test.0',
    replay_policy: 'instant',
    idle_heartbeat: 5000000000,
    flow_control: true
  },
  delivered: {
    consumer_seq: 3,
    stream_seq: 25,
    last_active: '2021-12-14T00:46:55.56474119Z' //<---- only here if there are messages
  },
  ack_floor: { consumer_seq: 3, stream_seq: 25 },
  num_ack_pending: 0,
  num_redelivered: 0,
  num_waiting: 0,
  num_pending: 10997, //<---------
  cluster: {
    leader: 'NAYT4OXN5RMM5OUFQWXRJXWDEDXDC2NRQVCZ4V4UU7CTMVPQA7QBIXSE'
  },
  push_bound: true
}
```

**Comment by ruidfigueiredo** [comment]
Just experience an instance where num_pending in the consumer is 0 when there are actual messages, `last_active` really does seem like the only option which is unfortunate. 
Here's the consumer info:

```
subscription consumerInfo: {
  type: 'io.nats.jetstream.api.v1.consumer_info_response',
  stream_name: 'dev-check-audio-spam',
  name: 'qmXnZGeU',
  created: '2021-12-14T15:14:14.93922231Z',
  config: {
    deliver_subject: '_INBOX.CHND2NFODYEGAGELC0W4K5',
    deliver_policy: 'all',
    ack_policy: 'none',
    ack_wait: 79200000000000,
    max_deliver: 1,
    filter_subject: 'dev.check-audio-spam.61b8b292899bc00029201488.file',
    replay_policy: 'instant',
    idle_heartbeat: 5000000000,
    flow_control: true
  },
  delivered: {
    consumer_seq: 16,
    stream_seq: 2208,
    last_active: '2021-12-14T15:14:14.941194031Z'
  },
  ack_floor: { consumer_seq: 16, stream_seq: 2204 },
  num_ack_pending: 0,
  num_redelivered: 0,
  num_waiting: 0,
  num_pending: 0,
  cluster: { name: 'nats', leader: '....' },
  push_bound: true
}
```
