### ISSUE TITLE
connect() raises error when used in browser app

### ISSUE THREAD

**Issue by adhocmaster** [nats-io/nats.js#472]
Hi there,

I use the library both for the backend and front-end side. However, the connect method fails with this error on the front-end running in Google chrome:

```
TypeError: (0 , h.createConnection) is not a function
    at t.value (node_transport.ts:104)
    at t.<anonymous> (node_transport.ts:64)
    at s (runtime.js:63)
```

**Comment by adhocmaster** [comment]
I got the issue. nats.js uses net package of node which is not available on the browser. It was not clear from the documentation that this module is only for node servers.

**Comment by aricart** [comment]
@adhocmaster you can use nats.ws for browsers. Same API, different transport.
