### ISSUE TITLE
feat: support native stream

### ISSUE THREAD

**Issue by intech** [nats-io/nats.js#477]
It would be useful to change the logic of work or add a separate one for direct interaction through native `Stream`.
The protocol and logic inside NATS can be implemented through `Transform`.
Thus giving more freedom and ability to optimize data flows inside node.

**Comment by aricart** [comment]
Can you elaborate more on your use case please.

**Comment by aricart** [comment]
I understand that you want to have a reader interface for messages, but effectively, the server will not buffer messages for a client for very long, and once the buffer is exhausted, it will deem the client a slow consumer and disconnect it. For JetStream the ability to pull messages from the stream at your own pace is completely possible.

**Comment by aricart** [comment]
@intech can you provide more information?

**Comment by aricart** [comment]
Isn't this effectively the same as you writing your stream with m.data? Effectively, if you consider that each message is just data, and forward it on, you can just ack, and move on, no?

**Comment by aricart** [comment]
@intech I didn't get any more feedback from you, please reopen if you still want to discuss this.
