### ISSUE TITLE
Connect (seems) to default to port 4222 even when specifying port 80

### ISSUE THREAD

**Issue by pabmoflo** [nats-io/nats.js#478]
Hello! I have a cluster node trying to connect to a load balancer which balances traffic to a nats server.
This load balancer is hardcoded to listen to port 80 traffic only, and sadly this behaviour cannot be changed. When using nats.js version 2.5.0, I can't seem to be able to connect to the load balancer using port 80, as nats.js defaults back to port 4222 as can be seen in the screenshot below:

![image](https://user-images.githubusercontent.com/92603701/151681706-9d6e9f55-841e-4ec7-a1d3-659c8bb14ba1.png)

It looks like the load balancer only allows traffic directly to the port 80, as otherwise the system returns host unreachable and no other kind of connectivity is allowed (even ICMP ping returns host unreachable).

Using the port argument returns connection refused instead.
![WindowsTerminal_1LrSbHi4Zl](https://user-images.githubusercontent.com/92603701/151681766-e35c034f-06c7-4fd6-8b10-96fae0cb8fcc.png)

However, if using netcat (`nc`) to put data directly into port 80 of the load balancer, I can see traffic being generated on the nats server as expected.

Client (note that I wrote the `{}` manually to trigger an error in the server):
![WindowsTerminal_WHdzQYYsO5](https://user-images.githubusercontent.com/92603701/151681828-b708567f-829e-46dd-a919-29e9c0f6d269.png)

Server:
![image](https://user-images.githubusercontent.com/92603701/151681891-fa7a8253-7196-4d7e-bfae-9bdd498854fd.png)

Any ideas why this could be happening?
Thanks in advance!

## **WORKAROUND**
As I needed a way to connect to port 80 of the load balancer, I've used the utility `socat` to create a local proxy that will redirect outgoing traffic of port 4222 to port 80. This way, I can make nats.js connect to "localhost:4222" and work properly:
```
socat TCP-LISTEN:4222,fork TCP:<load-balancer-ip-addr>:80 &
```

**Comment by aricart** [comment]
Take a look at the connection options documentation:

https://github.com/nats-io/nats.js#connection-options

> Port to connect to (only used if servers is not specified).

**Comment by pabmoflo** [comment]
Hello, isn't that what I did in the second screenshot?

> Using the port argument returns connection refused instead. ![WindowsTerminal_1LrSbHi4Zl](https://user-images.githubusercontent.com/92603701/151681766-e35c034f-06c7-4fd6-8b10-96fae0cb8fcc.png)

**Comment by aricart** [comment]
@pabmoflo the first option looks correct - the second one is not - I was reacting the the config that listed: `{servers: "sometime", port: 80}` and opened this issue:

https://github.com/nats-io/nats.js/issues/479

Now for the first entry should have worked for you.

**Comment by aricart** [comment]
For the issue why the client/server may be rejecting - can you try to add the connection option `debug: true` - this will print whatever the client is sending or receiving on the wire and may provide more insight.

**Comment by aricart** [comment]
Also if the client is disconnecting, but got an update from the server, it will attempt to connect using that, since the server is behind a load balancer, the port that it will be reporting will be incorrect. You'll need to configure the server to not push cluster updates - on servers that sit behind the load balancer.

**Comment by pabmoflo** [comment]
Using `debug: true` yields the same output:
![image](https://user-images.githubusercontent.com/92603701/151712563-e0a79c40-6156-49c5-8fe2-b7cf62676253.png)

Note that the server is also configured to listen on port 80, so the port should be correct. Looks like it can't even connect in the first place tho.

I've updated the OP with a temporal (hacky) solution using a proxy to redirect traffic to port 80.

**Comment by aricart** [comment]
@pabmoflo that is not the expected output from debug. --- not sure what is going on.

**Comment by pabmoflo** [comment]
Is there any specific way I could check the specific nats.js version from the node CLI? I wonder if running `npm install nats` didn't actually download the latest version or something like that.

**Comment by aricart** [comment]
@pabmoflo actually you did find an issue. In your exact case the port is "forgotten" - because the code is using `new URL()` to perform some of the parsing:

https://github.com/nats-io/nats.deno/blob/main/nats-base-client/servers.ts#L28

URL#port() is returning nothing (it is swallowing, even though it is supposed to report default ports as shown on MDN -https://developer.mozilla.org/en-US/docs/Web/API/URL/port. This basically short-circuits into 4222 - this case is specific I would imagine to 80 and 443. I'll have a fix for you by tomorrow.

**Comment by aricart** [comment]
Also you should be able to verify your installed bundles with `npm ls`
