### ISSUE TITLE
deno error: jsr:@nats-io/obj was not found.

### ISSUE THREAD

**Issue by nounder** [nats-io/nats.js#48]
### Observed behavior

Downloading module via JSR does not work (this command was taken from Readme file)
```
$ deno add @nats-io/obj
error: jsr:@nats-io/obj was not found.
```

Also, visiting jsr.io page shows:
```
This package has not published a stable release yet.
```

Some misconfiguration maybe?

### Expected behavior

It works.

### Server and client version

$ deno -v
deno 1.45.5

**Comment by nounder** [comment]
Other modules seems to have the same issue.

**Comment by nounder** [comment]
Providing specific package version works:
```
deno add jsr:@nats-io/nats-core@3.0.0-4
```

Reason why it is so can be found in #50.

**Comment by aricart** [comment]
Yes - you'll have to do the prerelease until it is released (without qualifier)
