### ISSUE TITLE
No equivalent of `nats account report`

### ISSUE THREAD

**Issue by rennokki** [nats-io/nats.js#480]
I've been fiddling around with NATS and the JS package, but I stumbled upon the lack of `nats account report` equivalent from the NATS CLI variant. (https://github.com/nats-io/nats-server/issues/1988#issuecomment-1025195218)

I don't find any docs nor I was able to find myself a way to implement this and submit a PR, as it seems the feature is not supported at all and I don't know where to start from.

Is there any hack to achieve this?

**Comment by derekcollison** [comment]
If you place a `--trace` onto the nats cli call you will see the raw requests and responses.

**Comment by rennokki** [comment]
I managed to see the incoming request, but not the actual URL that's called or what transporter is used. I feel myself really dumb.

**Comment by derekcollison** [comment]
The nats cli is all NATS messaging. So if you send a request to `$SYS.REQ.ACCOUNT.PING.CONNZ` all servers in a system will report back the information for your account and the connections for your account.

`nats req "\$SYS.REQ.ACCOUNT.PING.CONNZ" ""`

That will only show you a single response but you will get the gist of it from that.

**Comment by rennokki** [comment]
I'm really dumb. So indeed, the `.request` function can be used to communicate not just with other subjects, but also with the cluster itself.

```js
nc.request('$SYS.REQ.ACCOUNT.PING.CONNZ').then(res => {
    //
});
```

Thanks a lot for the quick reply. :+1:
