### ISSUE TITLE
node 17.5.0 buf.slice  Deprecated!

### ISSUE THREAD

**Issue by mmd-app** [nats-io/nats.js#483]
`let nc = await connect()`
throw // reader closed RangeError: Maximum call stack size exceeded

ENV node 17.5.0 Deprecated: Use [buf.subarray](https://nodejs.org/api/buffer.html#bufsubarraystart-end) instead.

```
class Parser {
    constructor(dispatcher) {
        this.dispatcher = dispatcher;
        this.state = State.OP_START;
        this.as = 0;
        this.drop = 0;
        this.hdr = 0;
    }
    parse(buf) {
        // @ts-ignore: on node.js module is a global
        if (typeof module !== "undefined" && module.exports) {
            // Uint8Array.slice() copies in node it doesn't and it is faster
            buf.subarray = buf.slice;
        }
        ...
```
fix plz

**Comment by aricart** [comment]
It's more than deprecated - they internally patched, creating a circular dependency.

**Comment by derekcollison** [comment]
Do we expect them to revert or fix this specific issue? Should we wait and see?

**Comment by aricart** [comment]
I am going to remove our fix - which means some small degradation on as `slice()` will copy data in some versions of node, as we cannot identify the node version deep down without some extensive introspection.

**Comment by aricart** [comment]
@homaily @mmd-app `npm update nats@latest`.

**Comment by Miyagee** [comment]
Seems like they updated node `16.15` with the same change so `npm update nats@latest` to fix the issue as well.

**Comment by ArmorDarks** [comment]
Are there any plans to make a NATS patch release? That issue will greatly affect users on node 16.15+ who use the current NATS stable version, especially considering it can be detected only in runtime
