### ISSUE TITLE
Failing to create a working JetStream consumer

### ISSUE THREAD

**Issue by sdc395** [nats-io/nats.js#485]
Hi all

I'm experimenting with JetStream and experiencing a problem when attempting to subscribe to a stream.  The aim is to create a push consumer with a queue.  My stream configuration is...

```
~ # nats stream info events -j
{
  "config": {
    "name": "events",
    "subjects": [
      "events.\u003e"
    ],
    "retention": "interest",
    "max_consumers": -1,
    "max_msgs_per_subject": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "new",
    "num_replicas": 1,
    "duplicate_window": 120000000000,
    "sealed": false,
    "deny_delete": false,
    "deny_purge": false,
    "allow_rollup_hdrs": false
  },
  "created": "2022-02-22T11:34:25.076620965Z",
  "state": {
    "messages": 0,
    "bytes": 0,
    "first_seq": 175,
    "first_ts": "1970-01-01T00:00:00Z",
    "last_seq": 174,
    "last_ts": "2022-02-22T15:51:15.660077302Z",
    "consumer_count": 1
  }
}
```

My (incomplete TypeScript) code for the subscription is...

```
async subscribe(): Promise<void> {

    const config = {
        'ack_policy': AckPolicy.Explicit,
        'deliver_group': 'event-queue',
        'deliver_policy': DeliverPolicy.New,
        'deliver_subject': 'event-queue',
        'durable_name': 'event-queue',
        'filter_subject': 'events.>',
        'replay_policy': ReplayPolicy.Instant,
    };

    const subscription = await js.subscribe(config.deliver_subject, {
        stream: 'events',
        queue: config.deliver_group,
        config,
        callbackFn: (err: NatsError | null, msg: JsMsg | null) => {

            if (msg !== null) {

                try {
                    console.log(JSON.stringify(this.#codec.decode(msg.data)));
                    msg.ack();
                }
                catch (e) {
                    this.logger.error(e);
                }
            }
        },
    });
}

```

If I run the above without any existing consumer, the error from NATS says: `consumer filter subject is not a valid subset of the interest subjects`.  I assume that "interest subjects" refers to the stream's subjects.  If I remove the `filter_subject` from the consumer configuration, the error remains.

If I create the consumer using `nats` without specifying a subject filter, the error goes away but I don't receive any messages.

If I create the consumer using `nats` with `filter_subject` set to `events.>`, the error from NATS says: `subject does not match consumer`.

I did have it working at one point, but I can no longer find the right combination of settings.  Any help would be greatly appreciated.  I'm finding the JetStream API to be very... challenging.

Thanks
Simon

**Comment by aricart** [comment]
The issue is that you are subscribing to the deliver subject, you need to be specifying one of the subjects in captured by the stream, the `deliver_subject` will create a subscription listening on that, but messages that the consumer is interested in are specified in terms of the stream subjects.

**Comment by aricart** [comment]
```typescript
  await jsm.streams.add({
    name: "events",
    subjects: ["events.>"],
  });


  const sub = await js.subscribe("events.>", {
    stream: "events",
    config: {
      ack_policy: AckPolicy.Explicit,
      deliver_policy: DeliverPolicy.All,
      deliver_subject: "foo",
      durable_name: "me",
      filter_subject: "events.>"
    },
    callbackFn: (err: NatsError|null, msg: JsMsg|null) => {
      console.log(msg?.subject);
      msg?.ack();
    }
  })
```
