### ISSUE TITLE
Error: consumer info specifies deliver_subject - pull consumers cannot have deliver_subject set

### ISSUE THREAD

**Issue by Nahasean94** [nats-io/nats.js#486]
I have this configuration that throws the above error when I start the server
```
const opts = consumerOpts()
    opts.durable(this.queueGroupName))
    opts.manualAck()
    opts.ackExplicit()
    let sub = await this.client.jetstream().pullSubscribe(this.subject, opts)
```

What am I doing wrong?
This code is derived from [this documentation](https://github.com/nats-io/nats.deno/blob/main/jetstream.md#pull-subscriptions)

**Comment by aricart** [comment]
(in my case the durable is called `me`, but in your case the name is in `this.queueGroupName`

**Comment by Nahasean94** [comment]
Thank you @aricart . I am using `"nats": "^2.6.1"`. I have finally managed to solve all my issues- that have been plaguing me for more than a week.
For this code block, my IDE shows a warning that i should add `await` to it. Which resulted to my nodejs server not starting at all
```
(async () => {
    for await(const m of sub) {
      console.log("\n", m.subject);
      m.ack();
    }
  })();
```

I guess the IDE is not always right 
I had to do some digging in the documentation to understand why with this line, the consumer only fetches the first batch and does not process any other messages after that:
`sub.pull({batch: 10, expires: 2000});`

What I have working for me now is:
 ```
   setInterval(() => {
      sub.pull({ batch: 10, no_wait: true })
    }, 1000)
```
Seems pull consumers need more configuration than push consumers, but I needed the horizontal scaling that pull consumers offer. Also, I was migrating from push to pull consumers, and restarting the nats deployments in my K8s cluster 'cleared' the push consumers previously created. 
@aricart if you have a better suggestion on the most optimal way to configure pull consumers that would be welcome as well for us beginners out here. 
One last question, I installed nats in my cluster usign helm, and I see only one replica was deployed per deployment. As traffic increases to my app, will it hurt to add more replicas or will it be problematic?

![image](https://user-images.githubusercontent.com/10699522/155951995-6c799259-bea4-416f-99c0-619c60908640.png)

**Comment by aricart** [comment]
> setInterval(() => {
     sub.pull({ batch: 10, no_wait: true })
   }, 1000)

That code is a server spam because every second you are asking for 10 messages, and for the request to fail immediately if there are no messages - instead, specify an `expires` that is possibly 2000, and an interval that is slightly smaller - this will keep the `pull` open and if messages arrive before the pull expires, they will be fed to you then.

This requires more coordination - the library will help you coordinate this type of action soon - as we are actively looking into making the consumers pull by default (to simplify importing streams) and automatically have them re-pull every so oftne.

**Comment by aricart** [comment]
For questions about Kubernetes, visit our slack channel, or post issues on the [helm repo](https://github.com/nats-io/k8s)

**Comment by Nahasean94** [comment]
Okay thanks alot @aricart
