### ISSUE TITLE
Retrieving total amount of connections seem slow

### ISSUE THREAD

**Issue by rennokki** [nats-io/nats.js#489]
I can have 3-10 clients that connect to a NATS cluster of 3 pods.

Take this following bit of code that was made to look after all messages from NATS and add the amount of connections (which are, in fact, the number of pods) into a sum, just to know how many responses to wait for when issuing request/responses.

```ts
import { timeout } from 'nats/lib/nats-base-client/util';

totaClients(): Promise<number> {
    return new Promise(resolve => {
        let responses: Msg[] = [];
    
        let calculateResponses = () => responses.reduce((total, response) => {
            let { data } = JSON.parse(this.sc.decode(response.data)) as any;
    
            return total += data.total;
        }, 0);
    
        let waiter = timeout(1000);
    
        waiter.finally(() => resolve(calculateResponses()));
    
        this.connection.request('$SYS.REQ.SERVER.PING.CONNZ').then(response => {
            responses.push(response);
            waiter.cancel();
            waiter = timeout(200);
            waiter.catch(() => resolve(calculateResponses()));
        });
    });
}
```

Is there something wrong here? The request seems to be resolve really slow. I have searched throughout the NATS org and barely found any example how to get around this. Compared with Redis where PUBSUB subscribers is a known number and easy to find, in NATS it seems like hell of a job to find out in best time.

Perhaps the approach here is adding some unwanted delay. Tipically, manual adjusted timeouts would be the worst case scenario since it can differ based on the workload. For Redis PubSub, at least there is a promise that can be solved in time adjusted directly to the current demand of `pubsub numsub` commands.

**Comment by derekcollison** [comment]
Are you trying to resolve the number of connections or the number of subscribers?

**Comment by rennokki** [comment]
If I have 10 clients that spread across 3 NATS instances, I would expect the number to be 10, as I expect 10 responses, and resolve the promise when all 10 responses are received or within an arbitrary timeout (whichever comes first).

**Comment by derekcollison** [comment]
So you are trying to get a sense of connections? That request will give you that, but might be better to just ping STATSZ, which returns the equivalent of /varz from HTTP.

Note that you get a response per server, not per connection. If you want connection details stick with what you have, otherwise maybe STATSZ. And to be on the same page, you will get system size (number of servers) responses, so in your case 3.
