### ISSUE TITLE
No wsconnect in nats-core

### ISSUE THREAD

**Issue by nounder** [nats-io/nats.js#49]
### Observed behavior

[Readme](https://github.com/nats-io/nats.js/blob/main/core/README.md) states:

> The core module also offers a for W3C Websocket transport (aka browser, Deno, and Node v22) via the exported wsconnect function.

However, `@nats-io/nats-core` does not export wsconnect (or any other function that is relevant to connections for that matter.) 

@nats-io/nats-core` comes from npm. I discovered it while trying to walk around #48 as it's impossible to download any JSR modules for Deno (including transport-deno one.)` The source code [seems](https://github.com/nats-io/nats.js/blob/147c5d8cbffc34392c7b03eaad027ad3a31b4b63/core/src/mod.ts#L48C3-L48C12) to export wsconnect but in the final build it's not available.

### Expected behavior

wsconnect is exported

### Server and client version

`@nats-io/nats-core@3.0.0-17` from npm

**Comment by nounder** [comment]
In npm package wsconnect is not included at all:

![CleanShot 2024-08-21 at 00 54 29@2x](https://github.com/user-attachments/assets/3ec44458-1fa4-4019-acff-c46a82f55782)

1. Go to https://www.npmjs.com/package/@nats-io/nats-core?activeTab=code 
2. Visit lib/mod.js (npmjs.org does not support file-specific links :()

**Comment by nounder** [comment]
Same for JSR build: neither fetched mod.d.ts nor mod.js contains `wsconnect` export.

**Comment by jasonford** [comment]
I'm blocked on this as well. I wasn't sure if it was an issue at the pnpm / npm / vite level before I saw this issue and made a quick repro for myself https://github.com/jasonford/nats-js-wsconnect-issue to isolate

From what I could tell from the current code, it looks like things are exported properly, so maybe it is already fixed and awaiting the next package publish?

In any case, from the README, it looks like the @nats-io/nats-core package is the current recommendation to use. Considering this issue, should developers hold off for a while before migrating to that package?

Thanks for all the great work already across so many platforms so far!

**Comment by nounder** [comment]
@jasonford I see you're using `3.0.0-17` version. Upgrading to `3.0.0-25` should fix this issue.

**Comment by aricart** [comment]
Yes the latest version published to jsr is 25, and has that. - Note that JSR doesn't consider the library published until there's a release that doesn't have a qualifier, since I am still working on there's no release, so you have to go to https://jsr.io/@nats-io/nats-core/versions and specify the exact version you want to try out.
