### ISSUE TITLE
Receiving all subjects on consumer

### ISSUE THREAD

**Issue by LuisPRamos** [nats-io/nats.js#490]
I'm trying to transition from NATS Streaming to JetStream, to do this I'm trying to set up a consumer for a specific subject in a project with the following configuration:

```javascript
jsm.streams.add({ name: streamName, subjects: [...Object.values(Subjects)] });

const inbox = createInbox(subject);
await natsWrapper.manager.consumers.add(streamName, {
  durable_name: queueGroupName,
  ack_policy: AckPolicy.Explicit,
  deliver_subject: inbox,
  ack_wait: ackWait,
});

options = consumerOpts();
options.deliverTo(subject);
options.callback(fnc)

options.bind(streamName, queueGroupName);


js.subscribe(subject, options);
```

With this configuration whenever I publish to a subject this subscription is receiving a message from all the available subjects. 

Expected logs:

```
[service1] Message sent: project:created
[service2] Message received: project:created
```

Current logs:

```
[service1] Message sent: project:created
[service2] Message received: project:created
[service2] Message received: project:updated
[service2] Message received: algorithm-run:created
[service2] Message received: algorithm-run:finished
```

How do I configure the subscription to only receive messages from a specific subject?

**Comment by aricart** [comment]
the `subject` on `js.subscribe(subject, opttions)` normally becomes the `filter_subject` for the consumer.

When you create your consumer, you need to specify a filter_subject - that will limit what you get.
When you use the `subscribe()` the first argument is a subject in the stream (the stream is located in that way), but that subject is also identified as a filter_subject - because you are using `bind` - that information is not really relevant and will use the consumer you created above, which doesn't have a filter, so you get all the messages from the stream.

**Comment by aricart** [comment]
(the `magic` of subscribe makes it hard to understand what you are doing, so you are not alone in this).

**Comment by LuisPRamos** [comment]
Ok, so I replaced the `deliver_subject` with `filter_subject`, but I am now getting the following error: `Error: consumer info specifies a pull consumer - deliver_subject is required`.

Do I still need a `deliver_subject`?

**Comment by LuisPRamos** [comment]
Ok, it seems I was misunderstanding how JetStream works, the subscription I was looking for is the `push` type however, when setting this up I get the following error: `Error: consumer info specifies a pull consumer - deliver_subject is required`.

New configuration:
``` 
    const options = consumerOpts();

    options.filterSubject(this.subject);
    options.durable(this.queueGroupName);
    options.deliverGroup(this.queueGroupName);
    options.queue(this.queueGroupName);
    options.deliverAll();
    options.ackWait(this.ackWait);
    options.ackExplicit();
    js.subscribe(this.subject, options);
```

How do I configure this subscription to be of the `push` type? Also, do I need multiple streams to receive a single subject in each `subscribe` or just one?

**Comment by LuisPRamos** [comment]
Update: I changed the configuration to the following and it worked. Is it correct?

```javascript
    options.filterSubject(this.subject);
    options.deliverTo(createInbox());
    options.durable(`${this.queueGroupName}|${this.subject}`);
    options.queue(this.queueGroupName);
    options.deliverAll();
    options.ackWait(this.ackWait);
    options.ackExplicit();
    options.manualAck();
    js.subscribe(this.subject, options);
```
