### ISSUE TITLE
removeComments, tsconfig.json, should be set to false in all client builds

### ISSUE THREAD

**Issue by john-livelyvideo** [nats-io/nats.js#494]
The intention is to make sure documentation/comments propagates into node_modules, so people can figure out what they need to do.

For example, these comments don't make it into node_modules after an npm install of the package.

https://github.com/nats-io/nats.deno/blob/ac6f15c5b2ec073e2efd12982ae37efc6fcdd30a/nats-base-client/types.ts#L346

**Comment by aricart** [comment]
Actually, it still doesn't seem to work, but it is merged into tsc, so we'll see it soon:

https://github.com/nhost/nhost/pull/345

**Comment by aricart** [comment]
This seems to be working for me now
![image](https://github.com/nats-io/nats.js/assets/1032976/ba217286-ad2c-4df4-af04-de3610921c03)
