### ISSUE TITLE
question when trying to reconnect

### ISSUE THREAD

**Issue by NoahHahm** [nats-io/nats.js#495]
will all subscribed channels be restored when reconnected?

**Comment by aricart** [comment]
All subscriptions are resent when a client reconnects (client connects, but for some reason, the connection is interrupted and it automatically recovers by reconnecting to the same server or a different server in the cluster) - if the client  `closed` (a terminal state) you must resubscribe.

**Comment by aricart** [comment]
This may be helpful to you:

https://github.com/nats-io/nats.js#lifecycleinformational-events
