### ISSUE TITLE
Question?: Connect to cluster on K8S

### ISSUE THREAD

**Issue by samuraitruong** [nats-io/nats.js#500]
I am looking for the document/guidline for setup NATS for production where we have few clients running on other services and NATS cluster deploy in same k8s namespace.

NATS cluster is deploy using https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts#clustering

My question is how we make the connection to this cluster in client nodejs code.  

- Should we only need to connect to the cluster service ?
- Should we connect to all server using pods name?

**Comment by caleblloyd** [comment]
Since you are only connecting from inside Kubernetes:

You can connect to the headless service created by the helm chat, and do not disabled client advertisements. The client will learn about all of the nats servers through advertisements.
