### ISSUE TITLE
Question: Load Balancing NATS

### ISSUE THREAD

**Issue by germanoeich** [nats-io/nats.js#502]
Greetings, I'm a little confused as to what's the correct way to load balance NATS and handle failures. Here are a few questions:

1 - When nats.js connects to multiple servers (either through direct configuration or discovery), will the library perform any sort of Load balancing across those servers? If so, does that apply both for publish and subscribe?
2 - Is exposing NATS using a Load Balancer (1 IP for multiple nats-servers) considered an anti-pattern? Does it affect performance, availability, etc?
3 - Assume a 1 node deployment, if the server fails for some minutes, when it comes back, will nats.js automatically resubscribe to all topics as it reconnects? Is this true for a 3-node deployment aswell?

For context, our NATS deployment is inside of Kubernetes, but we have workloads that sit outside that cluster. Currently we use a type: LoadBalancer service to expose NATS to these workloads. If there is a better way to do this, suggestions are more than welcome.

**Comment by derekcollison** [comment]
The clients will by default shuffle the list of servers that it has to select a server to connect to. It does not do anything beyond that.

We usually do not recommend putting a load balancer in between clients and servers but we do have folks that use them. 

All clients when they reconnect will re-establish all subscriptions. They also have a a publish buffer that will be flushed upon reconnect for any publishes done while disconnected.

For Kubernetes you can simply expose the client port and have external apps directly connect. I think HostPort option IIRC.
