### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by fungiboletus** [nats-io/nats.js#507]
Hi,

I was looking for the API documentation, related to #92 , and I read that I had to read the source code instead. Fine, but where is it? It seems to be missing from this repositoy. Some files are referenced but not there.

**Comment by Jarema** [comment]
If you're looking for source code NATS client, it's shared between `deno` and `node` Client:

https://github.com/nats-io/nats.deno/tree/main/nats-base-client

**Comment by fungiboletus** [comment]
Thanks @Jarema I also found the `nats-base-client` in the NPM package. I didn't expect the code of nats.js to be in nats.deno.

**Comment by fungiboletus** [comment]
I see that [the source code is in the `.gitignore`](https://github.com/nats-io/nats.js/blob/4e81d8a74d8b06e25fe049ecb4bfc772437528b9/.gitignore#L8).

How is your development process? Do you copy paste the folder nats-base-client folder, or have a link in your local filesystem?

**Comment by aricart** [comment]
The 'npn run stage' clones the base client and then applies some transforms to some of the imports, then uses the typescript compiler on the project.

**Comment by aricart** [comment]
You can also look at the doc in nats.io.   just noticed that some of the structure changed making it harder to find than it should be. The samples here are core nats only but illustrate the cross client API.

https://docs.nats.io/using-nats/developer/connecting/default_server

**Comment by haywirez** [comment]
I agree that this should be pointed out in the readme 👍
