### ISSUE TITLE
request/respond but response trigger multiple times

### ISSUE THREAD

**Issue by samuraitruong** [nats-io/nats.js#509]
We have HA system that the message subscriber has multiple nodes. base on the document, request/reply is equivalent to http request/respond look like all the subscribers got the message and process it. As result I have 2 record in database instead of 1.

**Comment by aricart** [comment]
you need to set up your responders to be in a queue group - 
In NATS all subscribers to a subject receive the message (as long as permissions allow), with a queue group, you can horizontally scale but limit the server to only forward the request to a single subscriber in the group (note that other subscribers in not in a queue group or in a different queue group will also get the message.

https://docs.nats.io/nats-concepts/core-nats/reqreply/reqreply_walkthrough
