### ISSUE TITLE
A question about wildcard subscription

### ISSUE THREAD

**Issue by dor132** [nats-io/nats.js#512]
Hi,
I am currently during the migration process from NATS Streaming to NATS JetStream and I am learning the new concepts NATS JetStream introduced: streams, consumers, etc.
From what I understand up until now, I should create a `stream` to capture all subjects I'd like to be persistent, and then use `consumers` to access those streams.
Then, I can subscribe to a `subject` using a `consumer` that gets messages from a stream (either push-base consumer or pull-based consumer).

Now, from what I saw, `streams` are allowed to have wildcard `subjects`, `consumers` however do not.
Since each `subscription` is connected to a `stream` through a `consumer`, how can a `subscription` be to a wildcard subject if the `stream` it is connected to cannot have a wildcard subject? What am I missing here?

I think the answer lies somewhere in understanding what `deliver_to` and `createInbox` of `consumerBuildOpts` exactly mean, or what is the connection between a `subscription` and a `consumer`.

Thank you!

**Comment by aricart** [comment]
@dor132 few things:

Streams can have capture wildcard subjects or list of subjects - so you can capture ["foo.>"] and ["foo.>", "bar.>"].

Consumers can play back all messages in the stream, but they can also filter. So a consumer for example, can filter on "foo.bar.>" and ignore all other subjects that the stream has. The one thing that the consumer cannot do is supply a list of subjects to playback. If you cannot create a wildcard filter that accommodates the subset of subjects you want, you'll have to create multiple consumers, or have your handler ignore subjects you don't want.

A consumer can specify a `deliver_subject` - that converts it into a _push_ consumer. Push consumers are fed messages as fast as the client can process them, so if your application cannot process that quickly, you may want to use a _pull_ consumer instead. The pull consumer can pull a single or a batch of messages at a time, and it initiates the request that makes jetstream feed the consumer messages.

**Comment by dor132** [comment]
I understand that a `deliver_subject` results in a consumer being a `push consumer`, but what exactly does this variable affect?

Can you elaborate on the difference between the `stream`'s subject, a `consumer`'s `filter_subject` and `delivery_subject`?
Should there be any relation between `deliver_subject` and the others?

**Comment by aricart** [comment]
The messages in the stream regardless of their subject are delivered to the subject specified in `deliver_subject`.

The JetStream consumer will only see messages that were published to the stream with a subject matching `filter_subject`

**Comment by dor132** [comment]
So, just to verify that I understand now.
Suppose I have a stream that tracks the subject `orders.>`.
If I create a push `consumer` with `deliver_subject="my.subject"`, and `filter_subject="orders.new.>"` , all messages consumed by the stream will be delivered on subject `my.subject`, regardless of their actual subject that may be `orders.new.table` or `orders.new.chair`.

Am I correct?

**Comment by aricart** [comment]
yes this is correct - a jetstream subscription doesn't work as normal subs do in that the server can stuff any message with any subject into it.

**Comment by aricart** [comment]
If you have another question, please feel free to open another issue.
