### ISSUE TITLE
Client unable to failover to other nodes in a cluster.

### ISSUE THREAD

**Issue by AyushRanaSamespace** [nats-io/nats.js#513]
I have setup a cluster consisting of two NATS servers on two different machines/servers. One of the server (say A) is the seed server. I've used the node.js nats client to connect to this cluster. The client establishes connection with A(The seed node).
When A goes down the client is unable to connect automatically to B. The machines on which I've deployed these servers have NAT. 

- Configuration file for A looks like this:

```
listen: <A's private IP>:4222
tls: {
  ca_file: './tls/rootCA.pem'
  cert_file: './tls/server-cert.pem'
  key_file: './tls/server-key.pem'
}
authorization: {
  token: $TOKEN
}
cluster {
  name: 'A'
  listen: <A's private IP>:4248
  authorization: {
    user: $USER
    password: $PASSWORD
  }
  cluster_advertise: <A's public IP>:4222
}

log_file: "./logs/nats-server.log"
```

- Configuration file for B looks like this:

```
listen: <B's private IP>:4222

authorization: {
  token: $TOKEN
}

tls: {
  ca_file: './tls/rootCA.pem'
  cert_file: './tls/server-cert.pem'
  key_file: './tls/server-key.pem'
}

cluster {
  listen: <B's private IP>:4248
  name: 'A'

  authorization {
    user: $USER,
    password: $PASSWORD,
  }
  cluster_advertise: <B's public IP>:4222

  routes = [
    nats-route://user:passwd@<A's private IP>:4248
  ]
}
log_file: "./logs/nats-server.log"
http_port: 8222
```
Any help is appreciated!
Also, one thing I noticed was that the connect_urls had private ips of the servers. Shouldn't it be their public IPs instead(as I have advertised the Public IPs)?

**Comment by aricart** [comment]
Hummmm I don't think the server is advertising the value under `cluster_advertise` (it could be that it is detecting the bogus port, but it is not warning about it) - you can inspect what the client is by doing the following:

```
import nats from "nats"

const nc = await nats.connect();
console.log(`connected to ${nc.getServer()}`);
console.log(nc.info);
(async () => {
  for await(const s of nc.status()) {
    console.log(s);
  }
})();
```

In my case - a simplified version of yours:

```
port: 4222
debug: true
cluster {
  name: 'A'
  port: 4248
  cluster_advertise: 127.0.0.1:5444
}
```

```
port:4333
debug: true
cluster {
  port: 4249
  name: 'A'
  cluster_advertise: 127.0.0.1:5555
  routes = [
    nats-route://127.0.0.1:4248
  ]
}
```

**Comment by aricart** [comment]
@AyushRanaSamespace I was looking at the wrong thing also, instead of `cluster_advertise` - part of the `cluster` configuration, you need to specify `client_advertise` at the top level. Once you do this, the client will get the proper information

**Comment by aricart** [comment]
Here's the proper configuration:
```
port: 4222
debug: true
client_advertise: 127.0.0.1:5444
cluster {
  name: 'A'
  port: 4248
}
```

```
port:4333
debug: true
client_advertise: 127.0.0.1:5555

cluster {
  port: 4249
  name: 'A'
  routes = [
    nats-route://127.0.0.1:4248
  ]
}
```

The client will then have proper updated cluster information:
```
connected to 127.0.0.1:4222
{
  server_id: 'NBNW32IWAQV36DCDGA235OXT7I4CLMSZ3QIOVN4RCUBONNX24CJDPIDS',
  server_name: 'NBNW32IWAQV36DCDGA235OXT7I4CLMSZ3QIOVN4RCUBONNX24CJDPIDS',
  version: '2.9.0-beta.12',
  proto: 1,
  go: 'go1.16.5',
  host: '127.0.0.1',
  port: 5444,
  headers: true,
  max_payload: 1048576,
  client_id: 6,
  client_ip: '127.0.0.1',
  cluster: 'A',
  connect_urls: [ '127.0.0.1:5444', '127.0.0.1:5555' ]
}

```

**Comment by AyushRanaSamespace** [comment]
It's working now! Thanks a lot!
