### ISSUE TITLE
Closed connection with 'Authentication Timeout' error doesn't auto-reconnect

### ISSUE THREAD

**Issue by ArmorDarks** [nats-io/nats.js#532]
Partially similar to https://github.com/nats-io/nats.js/issues/531

* Client version: 2.8.1-2
* NATS server version: 2.6.2
* nats-operator: 0.8.3
* Node version: 16.14.2

## What's happening

Given the config

```ts
const connection = await connect({
  maxReconnectAttempts: -1,
  name: 'some-name',
  pass: 'some-pass',
  servers: ['load-balancer-url'], // nats-operator with a bunch of nodes behind balancer
  user: 'some-user',
  inboxPrefix: 'some.inbox',
})
```

If the connection closed with the following error

```
NatsError: 'Authentication Timeout'
    at Function.toError (/code/node_modules/nats/lib/nats-base-client/protocol.js:339:20)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:363:41)
    at Generator.next (<anonymous>)
    at /code/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.processError (/code/node_modules/nats/lib/nats-base-client/protocol.js:361:16)
    at ProtocolHandler.push (/code/node_modules/nats/lib/nats-base-client/protocol.js:461:22)
    at Parser.parse (/code/node_modules/nats/lib/nats-base-client/parser.js:307:45)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:197:45)
```

it will never reconnect despite `maxReconnectAttempts` set to `-1`

## What's expected

If `maxReconnectAttempts` set to `-1`, the connection should automatically try reconnecting. Otherwise, it should be highlighted in the docs that this particular case has to be handled manually.

## Additional info

This issue is usually triggered for many servers if one of the NATS nodes is killed in the cluster.

What's logged on the client:

<img width="2117" alt="image" src="https://user-images.githubusercontent.com/4460311/201971302-5d88c66d-f3fb-4a4f-a959-10dd1e388dbd.png">

nats-server (in cluster) logs the following errors:

<img width="1572" alt="Screenshot 2022-11-15 at 16 40 48" src="https://user-images.githubusercontent.com/4460311/201976753-e862a00b-11f6-47c9-9fc6-3a103c2fd598.png">

I guess it happened because one of the nodes was killed, and the server needed more time to establish the connection. That's ok (I guess) for a server because he will keep retrying, but it completely stops client reconnection attempts for some reason. The client can't know whether the server will ever recover, and I think there's no way to guarantee on the server that this error will never happen, so I'd assume the client must keep trying to reconnect.

It somehow looks similar to https://github.com/nats-io/nats.ws/issues/61 though it's claimed to be fixed. Our setup is actually a bit similar - a few nodes in each region behind geoDNS-based balancer, though we use `nats-operator`.

Another looking similar issue is https://github.com/nats-io/nats.js/issues/145

**Comment by aricart** [comment]
This one is a bit more tricky to test, because we have to possible conditions, once is did the server ever answer or not.
Here's the first:

```javascript
import { createServer } from "net";
import { connect } from "nats";

const PORT = 4321;

const server = createServer();
server.on("connection", (conn) => {
  console.log("client connected");
  setTimeout(() => {
    conn.end();
  }, 30000);
});

server.listen(PORT, (v) => {
});

// The server doesn't have `waitOnFirstConnect` set so after the first connection attempt with timeout, it will give up
// and close - if you add `waitOnFirstConnect: true`, it will keep trying and you can see the server option printing everytime the client attempts a connection.
await connect({
  port: PORT,
  debug: true,
  maxReconnectAttempts: 10,
  timeout: 1000,
});
```

Should see:
```bash
client connected
/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/error.js:101
        return new NatsError(m, code, chainedError);
               ^

NatsError: TIMEOUT
    at NatsError.errorForCode (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/error.js:101:16)
    at timeout (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/util.js:88:35)
    at ProtocolHandler.<anonymous> (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/protocol.js:188:44)
    at Generator.next (<anonymous>)
    at /private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.dial (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/protocol.js:184:16)
    at ProtocolHandler.<anonymous> (/private/tmp/closeOnSubject/node_modules/nats/lib/nats-base-client/protocol.js:250:32)
    at Generator.next (<anonymous>) {
  code: 'TIMEOUT',
  chainedError: undefined
}

```

**Comment by aricart** [comment]
The next scenario is where the server connected, and now the number of attempts is honored as you have them, the client will attempt a reconnect forever:

```javascript
import { createServer } from "net";
import { connect } from "nats";

const PORT = 4432;

let INFO = Buffer.from(
  `INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":${PORT},"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}\r\n`,
);

const PING = { re: /^PING\r\n/i, out: "PONG\r\n" };
const CONNECT = { re: /^CONNECT\s+([^\r\n]+)\r\n/i, out: "" };
const CMDS = [PING, CONNECT];

const server = createServer();
server.on("connection", (conn) => {
  console.log("client connected");
  if (INFO) {
    conn.write(INFO);
    INFO = null;
    let inbound;
    conn.on("data", (data) => {
      if (inbound) {
        inbound = Buffer.concat([inbound, data]);
      } else {
        inbound = data;
      }
      while (data.length > 0) {
        let m = null;
        for (let i = 0; i < CMDS.length; i++) {
          m = CMDS[i].re.exec(inbound);
          if (m) {
            const len = m[0].length;
            if (len <= inbound.length) {
              inbound = inbound.slice(len);
              conn.write(Buffer.from(CMDS[i].out));
              break;
            }
          }
        }
        if (m === null) {
          break;
        }
      }
    });
  }
  setTimeout(() => {
    conn.end();
  }, 5000);
});

server.listen(PORT, (v) => {
});

const nc = await connect({
  port: PORT,
  debug: true,
  maxReconnectAttempts: -1,
  reconnectTimeWait: 500,
  timeout: 1000,
});

(async () => {
  for await(const s of nc.status()) {
    console.log(s)
  }
})()

nc.closed().then((err) => {
  console.log(`client closed with: ${err?.message}`);
  server.close();
});

```

So you should see something like:
```bash
client connected
> INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":4432,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}␍␊
< CONNECT {"protocol":1,"version":"2.9.0","lang":"nats.js","verbose":false,"pedantic":false,"headers":true,"no_responders":true}␍␊
< PING␍␊
> PONG␍␊
{ type: 'disconnect', data: '127.0.0.1:4432' }
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
client connected
{ type: 'reconnecting', data: '127.0.0.1:4432' }
....
```

**Comment by aricart** [comment]
The first case matches your setup, so what is happening is the client is connecting, but your load balancer is not really forwarding the connection to nats so your authentication is timing out after the timeout timer kicks in, and because `waitOnFirstConnect` is not set, the client closes. Specifying the `waitOnFirstConnect` will insure your client restarts.

**Comment by aricart** [comment]
@ArmorDarks I am closing this issue - I am still with you to try to determine why your load balancer is messing up the NATS connection.

**Comment by ArmorDarks** [comment]
> The first case matches your setup, so what is happening is the client is connecting, but your load balancer is not really forwarding the connection to nats so your authentication is timing out after the timeout timer kicks in, and because waitOnFirstConnect is not set, the client closes. Specifying the waitOnFirstConnect will insure your client restarts.

@aricart Similar to the question in https://github.com/nats-io/nats.js/issues/533#issuecomment-1317361297 - does it apply if the connection was already active and good before that error happened? The reported issue happened on connections that were running for days, but then suddenly nats-server node behind the balancer died, and here we go.

The other thing is it sounds very contr-intuitive to drop connection attempts if something is timing out. One thing is that if that's about an error that failed and will never be resolved, but those timeouts sound like something that will eventually resolve, I'd expect the client to keep trying to reconnect until the server reports that the server itself gives up too and will never be restored.

**Comment by aricart** [comment]
The behavior can be tweaked by the waitOnFirstConnect.  The timeout authentication issue is required because the connection could hang forever.  As you see the client will reattempt.  But the nuance is on whether that server was ever reachable

**Comment by aricart** [comment]
The behavior can be tweaked by the waitOnFirstConnect.  The timeout authentication issue is required because the connection could hang forever.  As you see the client will reattempt.  But the nuance is on whether that server was ever reachable

One thing that can cause this is insufficient resources for the server, or thundering heads with TLS and huge number of clients

**Comment by ArmorDarks** [comment]
Our nats pods hosted on dedicated servers and they have quite sufficient resources:

```yml
    resources:
      requests:
        cpu: 4000m
        memory: 8000Mi
      limits:
        cpu: 5000m
        memory: 10000Mi
```

>  or thundering heads with TLS and huge number of clients

That could be true. When a pod with nats-server is dropped, at least a few thousand of clients will try to re-connect. Though it doesn't sound like too much.

**Comment by aricart** [comment]
Actually it might be the initial TLS handshake is more intensive. Make the jitter setting 5000, this could be the reason for some of your timeouts.
