### ISSUE TITLE
Closed connection with 'Authorization Violation' error doesn't auto-reconnect

### ISSUE THREAD

**Issue by ArmorDarks** [nats-io/nats.js#533]
Partially similar to https://github.com/nats-io/nats.js/issues/531 and https://github.com/nats-io/nats.js/issues/532

* Client version: 2.8.1-2
* NATS server version: 2.6.2
* nats-operator: 0.8.3
* Node version: 16.14.2

## What's happening

Given the config

```ts
const connection = await connect({
  maxReconnectAttempts: -1,
  name: 'some-name',
  pass: 'some-pass',
  servers: ['load-balancer-url'], // nats-operator with a bunch of nodes behind balancer
  user: 'some-user',
  inboxPrefix: 'some.inbox',
})
```

If the connection closed with the following error

```
NatsError: 'Authorization Violation'
    at Function.toError (/code/node_modules/nats/lib/nats-base-client/protocol.js:333:20)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:363:41)
    at Generator.next (<anonymous>)
    at /code/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.processError (/code/node_modules/nats/lib/nats-base-client/protocol.js:361:16)
    at ProtocolHandler.push (/code/node_modules/nats/lib/nats-base-client/protocol.js:461:22)
    at Parser.parse (/code/node_modules/nats/lib/nats-base-client/parser.js:307:45)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:197:45)
```

it will never reconnect despite `maxReconnectAttempts` set to `-1`

## What's expected

Well, it's a tricky issue. This error is usually a legitimate reason to exit any attempts to reconnect. However, in our scenario, we've encountered a situation that is kinda "false-positive", and maybe it would be better to keep trying to reconnect.

## Additional info

Similar to the https://github.com/nats-io/nats.js/issues/532, this issue is usually triggered for many servers if one of the NATS nodes is killed in the cluster.

What's logged on the client:

<img width="2111" alt="image" src="https://user-images.githubusercontent.com/4460311/201980588-2956bd43-0fcf-436f-8cd0-ba04d1dc1364.png">

nats-server (in a cluster) logs the following errors:

<img width="1764" alt="Screenshot 2022-11-15 at 17 02 14" src="https://user-images.githubusercontent.com/4460311/201982419-ccf88815-8aa7-4bae-9be3-20d597030fbc.png">

I'm not very familiar with how, internally nats-operator works and gateway connection happens, but it seems there's a small gap after the node start when it can't auth, which returns this error to the client. The client can't distinguish whether it is from normal "wrong credentials" issue and shutdowns connection for good.

In case it's expected behavior, maybe there's a recommendation on how to deal with it? Or should that issue be reported to the nats-server or nats-operator?

**Comment by aricart** [comment]
Now note it is possible for the client to get an `ErrorCode.BadAuthentication` error code, but the message could be a different exception - this means that the client couldn't figure out what failed the server connection (not an expected error). But is reported under the guise of a `ErrorCode.BadAuthentication` error code.

If you want to prevent the bailing on a double Authentication error, I could do something to prevent this, but note that it will be a fairly silent operation, so your client may be spinning forever.  While I don't know the details of your service, I would imagine that if the "network" ie. NATS is down, your service should possibly restart and let systemd restart the process.

Alternatively we have to figure out why you get a rejected authentication, I think it has something to do with your load balancer setup (it could be memory/cpu constraints are not letting the NATS server do its thing properly). Can you tell me what the kubernetes constraints are on the nats-server and/or the client. I am not a Kubernetes savy person, but I can start asking some questions.

**Comment by aricart** [comment]
@ArmorDarks , we have to figure out why you get a rejected authentication, I think it has something to do with your load balancer setup (it could be memory/cpu constraints are not letting the NATS server do its thing properly). Can you tell me what the kubernetes constraints are on the nats-server and/or the client. I am not a Kubernetes savy person, but I can start asking some questions.

**Comment by aricart** [comment]
Are you using JetStream?

**Comment by ArmorDarks** [comment]
@aricart Nope

**Comment by aricart** [comment]
> Quick question: If the first connection attempt fails with that option, will `nats.connect()` promise resolve, or will it keep pending

nats.connect() doesn't resolve until there's an actual connection established.

**Comment by aricart** [comment]
> It could be. nats server logs are showing those errors for a while right after the new nats-server pod was started, so it seems like nats-server is not ready in that new pod while the connection happens, but if it's not ready - it's unclear why nats-server reports ok readiness healthcheck (otherwise balancer would not route to it).

@wallyqs may know more about this, but one thing that he told me is that, you'll need to set up `GOMEMLIMIT` to slightly less than the actual memory limit. On helm chart that is : 

```
nats:
  gomemlimit: "9000MiB"
```

**Comment by aricart** [comment]
IMHO the issue that the LB is answering requests when the server is not ready... Those are probably the timeout authentications.

Now how many clients are in this cluster, if it is resetting and you are using TLS they will all start trying to reconnect at the same time, and that will create a thundering herd. 

You may also want to increase the `reconnectJitterTLS` or `reconnectJitter` to something other than the defaults and perhas help the re-connects from the client to stagger out.

**Comment by aricart** [comment]
@ArmorDarks @wallyqs realized that you are using the operator, you need to be using the helm chart!!!

https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts

**Comment by aricart** [comment]
@ArmorDarks @wallyqs realized that you are using the operator, you need to be using the helm chart!!!

https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts

**Comment by wallyqs** [comment]
What load balancer are you using? Make sure that the load balancer is configured to make healthcheck requests to the port 8222 instead of 4222, not sure if the LB might be pruning the route to the 4222 port due to a raw tcp connect check that is being reset due to auth being configured

**Comment by ArmorDarks** [comment]
@aricart @wallyqs  Yes, we're using nats-operator. It's behind AWS Load Balancer.

AWS Load Balancer configured to make health checks on port 8222, by checking route /subz. However, as tests have shown, 8222/subz route will reply 200 as soon as nats-server is started. I don't know (and not sure) that it's consistent with the time server is actually able to accept NATS clients

**Comment by wallyqs** [comment]
Another thing to try is increasing the auth timeout to be about 3s or 5s just in case

**Comment by ArmorDarks** [comment]
And yes, of course, we do use https://nats-io.github.io/k8s/helm/charts/ charts

**Comment by ArmorDarks** [comment]
> IMHO the issue that the LB is answering requests when the server is not ready... Those are probably the timeout authentications.

I was quite sure about this at first. I've tried to replicate the whole situation, and the load balancer correctly did not route anything on starting nats-server until nats-operator said that pod was fully ready. I've check logs for our older cases and it was similar.

> Now how many clients are in this cluster, if it is resetting and you are using TLS they will all start trying to reconnect at the same time, and that will create a thundering herd.

At the moment when it happened, there were 3 pods housing 10 000 connections in total. After one of pods were killed, only 30% of clients were able to reconnect back. Is that too much for 2 remaining pods to handle?

------

I'm still trying to figure out whether it's an issue on our side, or whether it's happening something unusual for nats-server.

I've inspected closer logs, and that's what the timeline looks like. It's actually quite interesting:

* 09:01:07 - pod 1 killed
* 09:01:07 - nats-operator reports that waiting for pod 1 to start
* 09:01:14 - nats-server in pod 1 reported it started
* 09:01:14 - pod 2 and 3 will start to error.

   Mostly with errors like `cid:14681 - authentication error - User ""` and `Error trying to connect to route (attempt 94): lookup for host "xxxxx": lookup xxxxxx on xxxxxx:xxxx: no such host`

   We also use gateways to connect to our other NATS cluster in a different region. Gateway will error with the same auth errors too.

   Pod 1 will not report anything at this point.

   It will 

* 09:04:14 - nats-operator will report that pod 1 is ready `time="2022-11-15T09:04:14Z" level=info msg="pod \"xxxx-1\" became ready" cluster-name=xxxx namespace=xxxx pkg=cluster`

   At this point error on pod 2 and pod 3 side will stop, and clients will no longer receive `Authentication Timeout` (https://github.com/nats-io/nats.js/issues/532) and `Authorization Violation` errors

During that time balancer never routed clients on restarting pod 1, and while the pod was preparing for 4 minutes, other nats-servers were getting a lot of errors.

So the only "different" thing here was that one pod was temporarily absent. Could it be that nats-server unable to handle new connections properly if one of the pods in the cluster is dead?

-----

Another interesting part is that we have on the same servers clients with NATS clients in Rust-based applications, and somehow they never ended up in such situations 🤷

**Comment by ArmorDarks** [comment]
> Another thing to try is increasing the auth timeout to be about 3s or 5s just in case

Thank you for the suggestion. It's already set to 5s (it's a default value in https://artifacthub.io/packages/helm/nats/nats-operator -> `clientsAuthTimeout`)

**Comment by aricart** [comment]
@ArmorDarks got you a 2.9.1-0 build, which includes only things related to your fixes for the last error etc.

`npm install nats@next`

**Comment by ArmorDarks** [comment]
@aricart Thank you. I assume we must now add `ignoreAuthErrorAbort: true` to the connection parameters?

I've also dug more into what was happening on servers, and I think we indeed hit a CPU limit, probably because of a lot of reconnecting users to the remaining active pods. At the time it was happening, around 6000 clients were reconnecting, all with default jitter settings and servers had auth timeout set to 5 seconds. All pods hit the limit by CPU, which was set in Kubernetes (it was ok with memory, it used 270mb out of 1gb allocated).

To sum up for anyone landing on this issue, here are all recommendations we implemented to deal better with such situations:

* Updated to the edge NATS client, which fixes the issue with connections being wrongly closed.
* Enabled experimental `ignoreAuthErrorAbort` feature (though, I'm still concerned whether it's really good idea. because it masks true auth errors).
* Increased client connection `reconnectJitter` and `reconnectJitterTLS` 10 seconds to distribute clients better during reconnection
* Enabled on the client connection `waitOnFirstConnect` option
* Increased auth timeout on nats-server (`clientsAuthTimeout` in nats-operator charts) to 10 seconds to timeout fewer connections and hence provoke fewer retries.
* We will probably consider adding one more pod or increasing the CPU limit to handle reconnection spikes better.

Although, after all, it looks like a user-side issue, I think there's good room for improvement:

1. Considering we do not use TLS on servers, is it expected? It's many times repeated that TLS is expensive to establish. But in our TLS is handled by the balancer, and internally, between the balancer and pod, it's no longer a TLS connection
2. Are there any plans to improve servers behavior in such situations? As described in https://github.com/nats-io/nats.js/issues/532#issuecomment-1318657521, servers do not signal proper information to clients, and logs are very confusing 
3. Do you think `ignoreAuthErrorAbort` is really a good solution to the problem? To me, it sounds like it's a problem with what servers signal to clients and `ignoreAuthErrorAbort` is basically just a bandage for the issue, which _masks real auth issues_. Servers are 100% knowing that something went wrong, and they can signal to clients info which will allow them to reconnect and properly differentiate CPU/timeout issues from fatal issues (like, indeed, improper, unrecoverable auth).
4. Why Rust client has handled that situation better? They didn't have issues with bailed-out connections.  Does Rust client never bailouts, or it just handles better server signaling?

**Comment by aricart** [comment]
> @aricart Thank you. I assume we must now add `ignoreAuthErrorAbort: true` to the connection parameters?

If you want the client to not close on two consecutive auth errors, yes.

> 
> I've also dug more into what was happening on servers, and I think we indeed hit a CPU limit, probably because of a lot of reconnecting users to the remaining active pods. At the time it was happening, around 6000 clients were reconnecting, all with default jitter settings and servers had auth timeout set to 5 seconds. All pods hit the limit by CPU, which was set in Kubernetes (it was ok with memory, it used 270mb out of 1gb allocated).
> 
> To sum up for anyone landing on this issue, here are all recommendations we implemented to deal better with such situations:
> 
> * Updated to the edge NATS client, which fixes the issue with connections being wrongly closed.
> * Enabled experimental `ignoreAuthErrorAbort` feature (though, I'm still concerned whether it's really good idea. because it masks true auth errors).
> * Increased client connection `reconnectJitter` and `reconnectJitterTLS` 10 seconds to distribute clients better during reconnection
> * Enabled on the client connection `waitOnFirstConnect` option
> * Increased auth timeout on nats-server (`clientsAuthTimeout` in nats-operator charts) to 10 seconds to timeout fewer connections and hence provoke fewer retries.
> * We will probably consider adding one more pod or increasing the CPU limit to handle reconnection spikes better.
> 
> Although, after all, it looks like a user-side issue, I think there's good room for improvement:
> 
> 1. Considering we do not use TLS on servers, is it expected? It's many times repeated that TLS is expensive to establish. But in our TLS is handled by the balancer, and internally, between the balancer and pod, it's no longer a TLS connection

The issue will likely be same regardless, the tls connection on the LB will probably affect its performance as well.

> 2. Are there any plans to improve servers behavior in such situations? As described in [Closed connection with 'Authentication Timeout' error doesn't auto-reconnect #532 (comment)](https://github.com/nats-io/nats.js/issues/532#issuecomment-1318657521), servers do not signal proper information to clients, and logs are very confusing

One way to look at it is, "the server is working on it" but the client has a timeout for the connection specified (which you have always been able to tweak up or down as a connection option). So while we can do something on one side or the other, the main issue we are trying to prevent is a situation where the client doesn't wait for the server indefinitely to send an INFO or perform the authentication. And on the other side, the server doesn't wait indefinitely for a client trying to authenticate. 

> 3. Do you think `ignoreAuthErrorAbort` is really a good solution to the problem? To me, it sounds like it's a problem with what servers signal to clients and `ignoreAuthErrorAbort` is basically just a bandage for the issue, which _masks real auth issues_. Servers are 100% knowing that something went wrong, and they can signal to clients info which will allow them to reconnect and properly differentiate CPU/timeout issues from fatal issues (like, indeed, improper, unrecoverable auth).

See the previous answer. The reason for the 2-auth-fail close is you can see a client with bad credentials trying to setup a connection every so many millis forever. With that said, perhaps the client should keep connecting. I have some very biased and conflicting opinions on what I think should happen (think in terms of a DB connection) but at the same time appreciate and value that the NATS clients recover from a hangup.

> 4. Why Rust client has handled that situation better? They didn't have issues with bailed-out connections.  Does Rust client never bailouts, or it just handles better server signaling?

Not quire sure what rust does @Jarema can possibly jump in on that.

**Comment by aricart** [comment]
@ArmorDarks I am going to close this issue, but if you see any other issue with the `nats@next` build I made for you, I of course really want to know. Please feel free to open a new issue for anything we should be looking at.
