### ISSUE TITLE
json connection option is missing from the docs

### ISSUE THREAD

**Issue by mriedem** [nats-io/nats.js#543]
Looks like #67 added the `json` connection option a long time ago but it's not listed in the connection options table in the README:

https://github.com/nats-io/nats.js/blob/main/README.md#Connection-Options

I stumbled across that option looking at someone else's code and it'd be nice if it were documented (the README does go on to talk about JSON encode/decode manually for messages, but the `json` option makes that simpler).

**Comment by aricart** [comment]
@mriedem encoded connections are not supported in the 2x version of the clients - see https://github.com/nats-io/nats.js/blob/main/migration.md#payloads.

 If you want to do JSON use the JSON encoder as shown https://github.com/nats-io/nats.js#publish-and-subscribe
