### ISSUE TITLE
What is the substitute for "node-nats-streaming"?

### ISSUE THREAD

**Issue by bestofman** [nats-io/nats.js#546]
I have a NodeJS project written with the help of `node-nats-streaming . I want to upgrade it to `jetstream` as the `nats-streaming-server` will be deprecated soon. But I am not sure what is the package I should install? is it `npm install nats@latest` to install?

Also I like to know what are the replacement options for the following old code?

```

import nats , { Message, Stan } from 'node-nats-streaming';

    const subscription = this.client.subscribe();

    subscription.on('message', (msg: Message) => {
      this.onMessage(parsedData, msg);
    }
  
  parseMessage(msg: Message) {
    const data = msg.getData();
  }

   this.client.publish();


```

Does the newer version have the similar architecture as before and we can only update our previous code with small changes or we should also change the functions and the way they were working before?

For example I will put 2 of my old functions to see how can I update them?

The `base-listener.ts` file:
```

import { Message, Stan } from 'node-nats-streaming';
import { Subjects } from './subjects';

interface Event {
  subject: Subjects;
  data: any;
}

export abstract class Listener<T extends Event> {
  abstract subject: T['subject'];
  abstract queueGroupName: string;
  abstract onMessage(data: T['data'], msg: Message): void;
  protected client: Stan;
  protected ackWait = 5 * 1000;

  constructor(client: Stan) {
    this.client = client;
  }

  subscriptionOptions() {
    return this.client
      .subscriptionOptions()
      .setDeliverAllAvailable()
      .setManualAckMode(true)
      .setAckWait(this.ackWait)
      .setDurableName(this.queueGroupName);
  }

  listen() {
    const subscription = this.client.subscribe(
      this.subject,
      this.queueGroupName,
      this.subscriptionOptions()
    );

    subscription.on('message', (msg: Message) => {
      console.log(`Message received: ${this.subject} / ${this.queueGroupName}`);

      const parsedData = this.parseMessage(msg);
      this.onMessage(parsedData, msg);
    });
  }

  parseMessage(msg: Message) {
    const data = msg.getData();
    return typeof data === 'string'
      ? JSON.parse(data)
      : JSON.parse(data.toString('utf8'));
  }
}

```

This is the `base-publisher.ts` file:
```

import { Stan } from 'node-nats-streaming';
import { Subjects } from './subjects';

interface Event {
  subject: Subjects;
  data: any;
}

export abstract class Publisher<T extends Event> {
  abstract subject: T['subject'];
  protected client: Stan;

  constructor(client: Stan) {
    this.client = client;
  }

  publish(data: T['data']): Promise<void> {
    return new Promise((resolve, reject) => {
      this.client.publish(this.subject, JSON.stringify(data), (err) => {
        if (err) {
          return reject(err);
        }
        console.log('Event published to subject', this.subject);
        resolve();
      });
    });
  }
}

```

**Comment by aricart** [comment]
@bestofman the correct library is `nats@latest` however there are a few things in there that you have to consider, and I think that should be done in steps

- The API for the nats core client changed, so if you have NATS core (uses of nats outside of the streaming API) should upgrade those before you embark on the nats-streaming to JetStream. The hints on how to upgrade can be found here: https://github.com/nats-io/nats.js/blob/main/migration.md

- The new API doesn't use any event emitter code, the javascript library for nats runs in 3 different types of runtimes node, deno, and browser, but in the case of your application you should be able to create equivalent functionality

- We are currently in the process of updating how clients receive messages from jetstream, https://github.com/nats-io/nats.deno/pull/427/files#diff-3e1a44a974097fdda34a858eca2863c53047d144f6bbcd4e3b436f5ef910c30eR219 but that is likely not for a few more weeks.

Let me work on a small example for you

**Comment by bestofman** [comment]
> For the docs on jetstream, you can see: https://github.com/nats-io/nats.js#jetstream
> 
> Also made a small commented sample, so you can see different jetstream along side of nats-streaming
> 
> https://gist.github.com/aricart/4b6f43d306287e3df4dafb830b71ff59

Thank you so much for your answers and the sample code. I have one more question to ask. As you can see in my code, I have an event declared like below:

```
interface Event {
  subject: Subjects;
  data: any;
}
```

And I could publish messages included JSON data like below:

```
stan.publish(this.subject, JSON.stringify(data), (err) => {
        if (err) {
          return reject(err);
        }
        console.log('Event published to subject', this.subject);
        resolve();
      });
```

Or I could read this data object using `Meassage.getData()` function like below:

```
    const subscription = this.client.subscribe(
      this.subject,
      this.queueGroupName,
      this.subscriptionOptions()
    );

    subscription.on('message', (msg: Message) => {
      this.onMessage(parsedData, msg);
    }
  
  parseMessage(msg: Message) {
    const data = msg.getData();
  }
```

But it seems there is no way to add `data` object to publishers and also there is no`getData()` function available in `JetStream` Meassage? So how can I do the above things with `JetStream`?

**Comment by aricart** [comment]
The message API is different:

The data is `msg.data` and it can only be UInt8Array - there is a `StringCodec` and a `JSONCodec` that will serialize and encode the payloads. 

https://nats-io.github.io/nats.deno/interfaces/Msg.html

The publish call is simply `nc.publish(subject, data)` with optional values for headers and possibly a reply subject:

https://nats-io.github.io/nats.deno/interfaces/NatsConnection.html#publish

The JetStream publish looks suspiciously similar:

https://nats-io.github.io/nats.deno/interfaces/JetStreamClient.html#publish

**Comment by aricart** [comment]
I would suggest you first take a look at:
https://github.com/nats-io/nats.deno#documentation

The above is how NATS core (no streaming) works. The after you learn what the new api looks like, I would take a look at:
https://github.com/nats-io/nats.deno#jetstream

**Comment by aricart** [comment]
@aricart I am going to close this issue, if you have other questions feel free to open a new issue

**Comment by bestofman** [comment]
In nats-streaming I could create a nats connection via the following line:
```

import nats, { Stan } from 'node-nats-streaming';

private _client?: NATS.JetStreamClient;
this._client = nats.connect(clusterId, clientId, { url });
```
But for the JetStream when I do following:

```
import NATS from "nats";

private _client?: NATS.JetStreamClient;
this._client = await NATS.connect({ name: clientId, servers : url});

```

I get this error:

`Type 'NatsConnection' is missing the following properties from type 'JetStreamClient': pull, fetch, pullSubscribe, views, apiPrefixts(2739)
`

Also it seems there is no `cluster_id` between JetStream's ConnectionOptions!

So how can I create the same NATS client using the connection function using new NATS?

**Comment by aricart** [comment]
jetstream doesn't have a cluster id, there is also the concept of accounts and other things that allows the separation and securing of data to different applications. See https://docs.nats.io/running-a-nats-service/configuration/securing_nats/accounts
