### ISSUE TITLE
Different constructors for the received message

### ISSUE THREAD

**Issue by stas-ut21** [nats-io/nats.js#549]
Hi,
I noticed that depending on the nats server (possibly differing in power and load), the size of the message, and just randomness (since I don't know what the reason is), the constructors differ
The constructors of the received message can be **Buffer** or **Uint8Array**

[Example code](https://gist.github.com/stas-ut21/90a59e8ee5c3aec32800054cf098cc9a)

With demo.nats.io server result:

`
subscription started
sub1000 message constructor is Buffer
sub10000 message constructor is Uint8Array
sub50000 message constructor is Uint8Array
subscription closed

`

With my localhost server(nats server 2.9.11, started with default options from docker) result:

`
subscription started
sub1000 message constructor is Buffer
sub10000 message constructor is Buffer
sub50000 message constructor is Uint8Array
subscription closed

`

or sometimes:

`
subscription started
sub1000 message constructor is Buffer
sub10000 message constructor is Buffer
sub50000 message constructor is Buffer
subscription closed

`

**Comment by aricart** [comment]
yes, you should only be accessing it as an Uint8Array - the reason why you see buffer there, is because in node, data from the socket is yielded as a Buffer, but the APIs on how it is accessed is Uint8Array. Buffer is an Uint8Array.

**Comment by stas-ut21** [comment]
> yes, you should only be accessing it as an Uint8Array - the reason why you see buffer there, is because in node, data from the socket is yielded as a Buffer, but the APIs on how it is accessed is Uint8Array. Buffer is an Uint8Array.

The Buffer API is different from Uint8Array

I wonder, why exactly different come

**Comment by stas-ut21** [comment]
@aricart 
for example, if using the toString method, we will get different behavior, depending on whether it is Buffer or Uint8Array
there are also other differences

[NodeJS docs](https://nodejs.org/api/buffer.html#buffers-and-typedarrays)

[Example](https://gist.github.com/stas-ut21/c20fb1de72ea45411a08e294a3d3baac)

**Comment by aricart** [comment]
I would suggest to stick by the examples.  And use string or JSON codecs.  The alternative is to copy all the data again. Currently the message is dispatched with an array view backed by the data the was provided by the socket.

**Comment by stas-ut21** [comment]
Ok, thanks
