### ISSUE TITLE
Request for "requestOne" method in NATS library

### ISSUE THREAD

**Issue by Giancarlo1974** [nats-io/nats.js#554]
Hello,

I recently updated my code to use the latest version of the NATS library, but noticed that the "requestOne" method is no longer available. This method was previously used to send a request and receive a single response, which was crucial for my implementation.

I have attached a snippet of my code below that demonstrates my use of the "requestOne" method.

`const param = {
    IP: '127.0.0.1',
  }
  const cmd = JSON.stringify(param)
  const uCmd = new Uint8Array(Buffer.from(cmd, 'utf8'))
const msg: NATS.Msg = await nc.request('test', uCmd, { timeout: 5000 })`

I would greatly appreciate it if the "requestOne" method could be restored or if there is an equivalent alternative method that I could use instead.

Thank you for your time and consideration.

Best regards,
Giancarlo

**Comment by kirrg001** [comment]
As far as I know you need to set `noMux: false`:

> await nats.request('xxxx, sc.encode('awaiting reply'), { noMux: false });

**Comment by aricart** [comment]
@Giancarlo1974 requestOne is not available in the 2.x library, you simply use `request()` - if you want to handle multiple messages, you can use https://nats-io.github.io/nats.deno/interfaces/NatsConnection.html#requestMany
