### ISSUE TITLE
Timestamp precision in StreamInfo and StoredMsg

### ISSUE THREAD

**Issue by kakserpom** [nats-io/nats.js#556]
StoredMsgImpl has `time` as a Date object (e.g. `time: 2023-02-20T16:49:29.579Z`)

StreamInfo has it like this: 
```
  created: '2023-02-07T16:10:01.129151419Z',
  state: {
    messages: 36,
    bytes: 33211,
    first_seq: 1,
    first_ts: '2023-02-09T11:23:43.429775802Z',
    last_seq: 36,
    last_ts: '2023-02-20T16:49:29.579453546Z',
    num_subjects: 1,
    consumer_count: 1
  }
```

Both approaches are not ideal:
1) Date object loses nanosecond precision 
2) String representation keeps the precision, but it's a bit of a hassle to convert strings back to nanosecond integer timestamps. It's way easier get a string representation of a timestamp than the way around.

I propose to use BigInt at all times. We might also provide a helper which would convert BigInt into a Date object.

**Comment by aricart** [comment]
@kakserpom  As you can see from below, the server is sending all those dates as UTC formatted, since `Date` only has millisecond resolution, what I can do is actually expose the underlying string received from the server. However it is outside of the scope of the library to parse etc.

Fields like stream info `created` are indeed numeric and mapped as `Nanos` for now you can simply convert these directly to BigInt if needed.

```json
{"type":"io.nats.jetstream.api.v1.stream_info_response","total":0,"offset":0,"limit":0,"config":{"name":"U2ZVV5PTDSE3KV3CG6O5UZ","subjects":["a.\u003e"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"duplicate_window":120000000000,"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false},"created":"2023-02-21T17:31:16.965792Z","state":{"messages":1,"bytes":38,"first_seq":1,"first_ts":"2023-02-21T17:31:16.96872Z","last_seq":1,"last_ts":"2023-02-21T17:31:16.96872Z","num_subjects":1,"consumer_count":0}}␍␊
...
{"type":"io.nats.jetstream.api.v1.stream_msg_get_response","message":{"subject":"a.a","seq":1,"data":"aGVsbG8=","time":"2023-02-21T17:31:16.96872Z"}}␍␊
```

**Comment by aricart** [comment]
Also the StreamInfo and state information are just simply strings, so no resolution was lost in those, I corrected the typescript types and jsdoc.

**Comment by aricart** [comment]
StoredMsg#timestamp will return the raw string read from the server, so that should expose the differences.
