### ISSUE TITLE
Missing created consumers and created subscriptions

### ISSUE THREAD

**Issue by Amansg4** [nats-io/nats.js#557]
Sorry for the cut and paste... I just wanted this to be a little more eye pleasing and presentable and I don't know how to get color on markdowns LOL.

![image](https://user-images.githubusercontent.com/84755940/220228564-283addc1-66e6-40bc-a5a1-d510077fede2.png)

Not all problems are neccessarly shown below, but this is an example where I should have 9 consumers (payment-services is missing). An error occured with the transmission of data within a msg being sent from ticket service to order service where it caused a mongodb error that crashed the order services. Order service does restart but fails to pick up any messages  awaiting proccessing thereafter. It doesn't show the NATS CLI indicating that order-services consumer not processing missed messages to subscribers, but I'm sure I don't need to post that =). 

FYI, the missing consumers tend to be random, rarely all appearing together, but sometimes they do, while other times randomly selected services are present (or none) while others appear. It is important to note that when a service does appear, all containing consumers (and I believe corresponding subscribers) within THAT service are present. So either all the consumers within a service appear or none.

![image](https://user-images.githubusercontent.com/84755940/220229521-94c2a7b7-3563-4a10-b18c-0bcff1584443.png)

Thanks for any help. I might be misunderstanding differences or similarities between nats-streaming and jetstream (Like how a stream or consumer should properly be translated into usage but I think I understand) as well so feel free to question my understanding. Thanks you all!

-ASG

**Comment by Amansg4** [comment]
*Also the consumers created after initial creation or after a crash sometimes states that they have no active interest despite subscriptions intentionally placed after consumer creation in the code.

**Comment by aricart** [comment]
While great that you have some debug output, would be more useful if both your question and snippets was something that I could look at.

**Comment by Amansg4** [comment]
gotcha. I'll delete this and start over on another issue ticket
