### ISSUE TITLE
Server assigns duplicate client_id's to core natsConnections in k8s cluster

### ISSUE THREAD

**Issue by Amansg4** [nats-io/nats.js#561]
Utilizing:
- Nats.js with Jetstream enabled
- k8s w/ skaffold
- Docker

While running skaffold dev for my k8s cluster of services,  am frequently getting interference from service connections sharing the same client_id so that they don't actually build the services NATS connection and subsequent components needed to communicate/function.

The following logs present some server/connection INFO after a natsConnection is formed. 

### Does not work

**Weird thing to note is that the client_id assigned (which I assumed was supposed to be random) ***very*** frequently tends to pick 4**.

```shell
Deployments stabilized in 8.202 seconds
Press Ctrl+C to exit
Watching for changes...
[tickets] 
[tickets] > tickets@1.0.0 start
[tickets] > ts-node src/index.ts
[tickets]
[orders]
[orders] > orders@1.0.0 start
[orders] > ts-node src/index.ts
[orders]
[orders]  >> service framework is beta functionality 
[orders] natsCoreConnectionMsg NatsInitializer Connection Resolved/Succeeded. 
[orders]
[orders] NATS Server Info:
[orders] Server: nats-srv:4222
[orders] Host: 0.0.0.0
[orders] Jetstream: true
[orders] Server_id: NCXY6IVYP5WMXFDTKD6Z4EORF5CTTFYLI5QQIPEGDXWO2W5OFQ66ZU4T
[orders] Server_name: asg4-nats
[orders] Client_id: 4
[orders] Client_ip: 10.1.7.235
[orders] Cluster: asg4-nats-cluster
```

```shell
[tickets]  >> service framework is beta functionality 
[tickets] natsCoreConnectionMsg NatsInitializer Connection Resolved/Succeeded.
[tickets]
[tickets] NATS Server Info:
[tickets] Server: nats-srv:4222
[tickets] Host: 0.0.0.0
[tickets] Jetstream: true
[tickets] Server_id: NC452KG4BR437FT4KKW7IXKCR6QQITNZSSTXBQCNS7OBHZ6WSRH7CVTF
[tickets] Server_name: asg4-nats
[tickets] Client_id: 4
[tickets] Client_ip: 10.1.7.236
[tickets] Cluster: asg4-nats-cluster
```

### Below Works

```shell
[orders] NATS Server Info:
[orders] Server: nats-srv:4222
[orders] Host: 0.0.0.0
[orders] Jetstream: true
[orders] Server_id: NARSKZ7SW2GMIIRVCMJHG43FRZB466OPH6JBMB25TSV7ELZBHKDZR4SZ
[orders] Server_name: asg4-nats
[orders] Client_id: 4
[orders] Client_ip: 10.1.7.226
[orders] Cluster: asg4-nats-cluster
```

```shell
[tickets] NATS Server Info:
[tickets] Server: nats-srv:4222
[tickets] Host: 0.0.0.0
[tickets] Jetstream: true
[tickets] Server_id: NARSKZ7SW2GMIIRVCMJHG43FRZB466OPH6JBMB25TSV7ELZBHKDZR4SZ
[tickets] Server_name: asg4-nats
[tickets] Client_id: 13
[tickets] Client_ip: 10.1.7.230
[tickets] Cluster: asg4-nats-cluster
```

I believe that whatever initiates first is the only service to actually be built.

If the client_id's happen to be different from one another (as intended I believe), then everything is okay. I can't find a way to purposefully alter the client_id, or initiate a reconnection/reassignment in case a client_id is taken. Any help would be appreciated.

**Comment by aricart** [comment]
The client_ids are assigned by the server.  If you have a cluster, it is possible that they have the same ID (as you do), because they are the order of connection on that server. But if you notice the server ID, those are different, so for that server, you could say that server_id + client_id are unique, however if you need an ID that you can use for request/reply and that sort of stuff, you should use `nuid` to generate one - nuid is exported by the same library. A
