### ISSUE TITLE
[JetStream] Pull consumers with durable are not automatically created

### ISSUE THREAD

**Issue by roman-supy-io** [nats-io/nats.js#568]
We're using Pull (`pullSubscribe`) strategy to fetch messages periodically and currently facing an issue with consumers not being created automatically.
Prerequisites:
1. Stream `random` is created
2. Subject `api-consumer-1-random-test-activity123` is created

Steps to reproduce:
1. Connect:
```ts
this.#connection = await connect({
      name: 'api-1',
      servers: [/* servers */]
    });

    this.#jetstream = this.#connection.jetstream();
```

2. Subscribe:
```ts
const subscription = await this.#jetstream.pullSubscribe('random.test.activity123', {
      ...this.options.consumer,
      config: {
        mack: true,
        name: 'api-consumer-1',
        config: {
          max_deliver: 10,
          ack_policy: AckPolicy.Explicit,
          deliver_policy: DeliverPolicy.LastPerSubject,
          durable_name: 'api-consumer-1-random-test-activity123',
          filter_subject: 'random.test.activity123',
        },
      },
    } as JetStreamConsumerOptions);
    
    for await (const message of subscription) {
      // handle message
    }
```

At the time of subscription (2nd step) the error is thrown:
```json
{
  "name":"NatsError",
  "code":"404",
  "api_error":{
    "code":404,"err_code":10014,"description":"consumer not found"
  }
}
```

Question: should the durable consumers be created manually or is there any option to specify that?
We couldn't find any.

P.S.:
Currently we managed to do this by manually creating `consumer`s but:
1. this is not documented anywhere.
2. it involves the usage of non-public `JetStreamClientImpl.prototype.findStream` to be called.

**Comment by aricart** [comment]
@roman-supy-io please reopen if the proposed solution didn't work for you.
