### ISSUE TITLE
[Jetstream] Nats client `drain` impact on `ConsumerMessages`

### ISSUE THREAD

**Issue by DaemonSnake** [nats-io/nats.js#574]
Hello
I have a question regarding the new Jetstream interface (`2.14.0`)
It looks like when calling `.drain` on the nats client the `ConsumerMessages` won't be closed Is that so / expected ?
Previously calling drain on a Nats client would also drain its subscriptions, which was pretty neat

**Comment by aricart** [comment]
thought I had a test for that, but it is possible that the signal is getting lost on the consumer iterator.
