### ISSUE TITLE
How to open page with auth (port 8222)

### ISSUE THREAD

**Issue by trandinhthangv1** [nats-io/nats.js#579]
I have nat server with auth token, how to open page?

**Comment by aricart** [comment]
@trandinhthangv1 not sure what you mean open page, if you are referring to connecting to the nats server with a JWT take a look at:

https://github.com/nats-io/nats.js#authentication
and
https://nats-io.github.io/nats.deno/interfaces/ConnectionOptions.html
more specifically you'll want to look at:
https://nats-io.github.io/nats.deno/functions/credsAuthenticator.html
or 
https://nats-io.github.io/nats.deno/functions/jwtAuthenticator.html

**Comment by aricart** [comment]
if you are accessing monitoring there's no lock on that, this is just an HTTP browser (http/s://localhost:8222)

**Comment by aricart** [comment]
https://docs.nats.io/running-a-nats-service/configuration/monitoring
