### ISSUE TITLE
Error: consumer 'filter_subjects' requires server 2.10.0

### ISSUE THREAD

**Issue by mshahrez** [nats-io/nats.js#588]
### What version were you using?

nats-server: v2.9.21
nats: 2.16.0" (Node JS)

### What environment was the server running in?

Windows 10

### Is this defect reproducible?

import { Injectable } from '@nestjs/common';
import { connect, StringCodec } from "nats";

@Injectable()
export class AppService {

  constructor() {

    const servers = [{ servers: ['nats://localhost:4222'] }];
    servers.forEach(async (v) => {
      try {
        const nc = await connect(v);
        const js = nc.jetstream();

        const b = await js.consumers.get(stream, { filterSubjects: [`foo`] });
        
        console.log(`connected to ${nc.getServer()}`);

        const sc = StringCodec();
 
        // this subscription listens for requests
        const highSub = nc.subscribe("high");
        const mediumSub = nc.subscribe("medium");
        const lowSub = nc.subscribe("low"); 

        (async (sub) => {
          console.log(`listening for ${sub.getSubject()} requests...`);
          for await (const m of sub) {

            const r = await b.next({ expires: 1000 });

            if (r) {
              m.respond(r.data)
              r.ack();
            } else {
              console.log(`didn't get a message`);
            }

          }
          console.log(`subscription ${sub.getSubject()} drained.`);
        })(highSub);

        (async (sub) => {
          console.log(`listening for ${sub.getSubject()} requests...`);
          for await (const m of sub) {
            const r = await getMedium.next({ expires: 1000 });
            if (r) {
              console.log(r.data);
              m.respond(r.data)
              r.ack();
            } else {
              console.log(`didn't get a message`);
            }

          }
          console.log(`subscription ${sub.getSubject()} drained.`);
        })(mediumSub);

        (async (sub) => {
          console.log(`listening for ${sub.getSubject()} requests...`);
          for await (const m of sub) {
            const r = await getLow.next({ expires: 1000 });
            if (r) {
              console.log(r.data);
              m.respond(r.data)
              r.ack();
            } else {
              console.log(`didn't get a message`);
            }

          }
          console.log(`subscription ${sub.getSubject()} drained.`);
        })(lowSub);
 

      } catch (err) {
        console.log(`error connecting to ${JSON.stringify(v)}`);
      }
    })

  }

}

### Given the capability you are leveraging, describe your expectation?

The server should allow the ordered consumer to be created at this point.

### Given the expectation, what is the defect you are observing?

I'm trying to create an ordered consumer but when I start the project, it gives the error

_Error: consumer 'filter_subjects' requires server 2.10.0_

Whereas, the server version 2.10.0 is not even available to download

**Comment by aricart** [comment]
You can download a nightly, and the feature is there. Or you can create the consumer, you just have to use `filter_subject` to have that work correctly with 2.9.
