### ISSUE TITLE
Pull-consumer stops pulling new messages after auto-reconnect

### ISSUE THREAD

**Issue by whocaresk** [nats-io/nats.js#590]
### What version were you using?

nats-server 2.9.16
nats.js 2.16.0

### What environment was the server running in?

Docker on MacOS (m1), kubernetes cluster (gke)

### Is this defect reproducible?

```typescript
import * as nats from 'nats';

const SERVERS = ['localhost:4222'];

const STREAM_NAME = 'stream';

const SUBJECT_NAME = 'str.>';

(async () => {
  const nc = await nats.connect({
    user: 'dev',
    servers: SERVERS,
    pingInterval: 3000,
    reconnect: true,
    maxReconnectAttempts: -1,
    debug: true,
  });

  const iter = nc.status();
  (async () => {
    for await (const e of iter) {
      console.log('---EVENT: ', e);
    }
  })().then();

  const jsm = await nc.jetstreamManager();

  try {
    await jsm.streams.delete(STREAM_NAME);
  } catch (err) {}

  await jsm.streams.add({
    name: STREAM_NAME,
    subjects: [SUBJECT_NAME],
  });

  const js = nc.jetstream();
  const subject = `str.messages.new`;
  const queue = `${subject}_NewMessageHandler`;

  const opts = nats
    .consumerOpts()
    .queue(queue)
    .durable(queue.replace(/\./g, '_'))
    .manualAck()
    .ackWait(1000 * 60 * 2)
    .maxAckPending(20000);

  let messagesCount = 0;

  opts.callback(async (err, msg) => {
    console.log('=== MSG: ', err, msg);

    if (msg) {
      await msg.ackAck();
      messagesCount++;
    }

    // to simplify complicated rxjs pipeline
    if (messagesCount === 5) {
      sub.pull({ batch: 5, expires: Infinity });
      messagesCount = 0;
    }
  });

  const sub = await js.pullSubscribe(subject, opts);

  sub.pull({ batch: 5, expires: Infinity });
})();
```
```yml
services:
  nats:
    restart: always
    image: nats
    command: "--user dev -js --store_dir /data"
    ports:
      - "4222:4222"
    volumes:
      - test-nats-data:/data

volumes:
  test-nats-data:
```

### Given the capability you are leveraging, describe your expectation?

After nats-server restart and client-lib auto-reconnection already created durable pull-consumer should proceed with pulling new messages as it was before nats-server restart.

### Given the expectation, what is the defect you are observing?

Pull-consumer stops pulling new messages from stream after nats-server restart. Restart of running instance is required to recover from this problem.   
There is workaround for this:
if you call `sub.pull(args);` again when client emits `reconnect` status - then everything is working as expected.

I'm not really sure my usage is correct way of using pull-consumer. I guess issue is caused by that pull call with Infinity expire, which hangs forever when reconnect happens.

**Comment by whocaresk** [comment]
This issue reproduces both on single node deploy and 3-node deploy

**Comment by whocaresk** [comment]
Thanks! I've noticed new API, but was unable to find any docs for it. This example is really useful

**Comment by aricart** [comment]
Go to the main page for the library, scroll to the bottom, and click the link to JetStream! - all the docs and also JS doc is part of the bundle as well as hosted https://nats-io.github.io/nats.deno

The new API is incredibly easy to use and doesn't have all the gotchas in the legacy API you were using.
