### ISSUE TITLE
Build target for NPM with ESM-based Core that has TSC compliant .d.ts files and without the `.ts` source files.

### ISSUE THREAD

**Issue by cmidgley** [nats-io/nats.js#60]
### Proposed change

Expand the `NPM` distro to include a `dist` style directory with ESM (such as `_dist/esm`) specified in `tsconfig` and generated by `tsc`.  The `dist` output should include only the `.js`, `.d.ts`, and `.map` files (no `.ts` files).  By using `tsc` (and not `Deno`) to compile, the resulting `.d.ts` files would be compliant with `tsc.`

This request is for all the repos associated with the `nats.js` client.

### Use case

I am targeting the [`Moddable XS'](https://github.com/moddable-opensource/moddable) platform for microcontrollers.  It is an excellent modern implementation of JS, but implements only ESM.

I am so far only working with `Core` (and its associated `nkeys` and nuid` packages), and I've tried using two versions:

- `npm install @nats-io/nats-core`: While this is Node-compatible for ESM, the included `js` source files are CJS and use require.  This will not work with `Moddable`.
- `npx jsr add @nats-io/nats-core`: This is ESM, but the supporting `.d.ts` files are `Deno` compliant and specifically the `header.d.ts` file is incompatible with `TSC`.  For example, line 18 has:

```tsc
findKeys(k: string, match = Match.Exact): string[];
```

This has an initializer in the interface, which is not allowed.  TSC gives this error:

```sh
 error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
 ```
 
I've worked around the issue for now, by building a separate module that builds everything from the TypeScript source files located in the `node_modules` directory, but it would be cleaner if there was a `dist/esm` style directory that had `tsc` compiled files (including only the `.js`, `.d.ts`, and `.map` files, without the `.ts` files).  This last point is because `Moddable` gets confused over the duplicate files in the same directory (the `.ts` and `.js`) and tries to compile both.  
 
I'm still working through getting this to run, as I need to add some polyfills and Node API compatible libraries (such as TextEncoder/Decoder, WebSocket, and more) but it is compiling and loads/imports on the microcontroller, which is a great sign that it may work with the current source tree (using WebSockets).  A custom transport would need to be written to use native IP, but that does not appear to be a big project (thanks to the excellent isolation in this architecture) and can be maintained in a separate repo.

### Contribution

Yes, but I have no Deno experience and don't yet understand the build process involved.

**Comment by aricart** [comment]
Also I believe that soon enough deno will properly support node, which means that the deno libraries will be the node ones, as Deno is striving to be the runtime for node...

**Comment by aricart** [comment]
@cmidgley my suggestion is that you try @nats-io/nats-core from npm. That set of bundles is tsc generated... Are you using the we socket transport?

**Comment by cmidgley** [comment]
Thanks - I did try that, but the transpiled `.js` files use `require` (which works with both esm and cjs with Node).  Moddable only supports `import`...

I am starting with the web socket transport.  I'm just now finishing up a w3c compliant web socket client for `Moddable` now, and already added all the polyfills that `nats.js` uses from Node, so I'm hoping I'll start running it very soon.  If I find success, I'll then move onto the other modules (jetstream, kv, services) and eventually look at creating a transport (though ws will hold the fort for a while).

I really appreciate the help, but I'm going to close this as it's working good enough and I'd hate to take up any more of your time.  Thanks again.
