### ISSUE TITLE
How to pause a consumer?

### ISSUE THREAD

**Issue by matteodisabatino** [nats-io/nats.js#606]
### Proposed change

I have configured  a NATS consumer this way:

```js
const opts = nats.consumerOpts()
opts.manualAck()
opts.deliverNew()
opts.durable('MY_DURABLE')
opts.queue('MY_QUEUE')
opts.deliverTo('MY_QUEUE')
opts.callback((e, message) => {
  // Do something
})

const consumer = await js.subscribe('MY_STREAM.MY_QUEUE', opts)
```

I know that use `js.subscribe` is deprecated and I planned to update my codebase, but I cannot do it at the moment.

Anyway this snippet is included in a complex HTTP service, and my purpose is to pause the consumer (in order to stop receiving messages), do some operations and than resume it. I searched in the official documentation but I didn't found anything... is it possible to do that?

### Use case

In complex HTTP services, it could be useful to receiving messages for some time and then resume.

**Comment by aricart** [comment]
You can simply call `unsubscribe()`  - and then re-start it - The consumer state is on the server by doing the same that you are doing by repeating the js.subscribe - as long as your durable doesn't expire, it will be waiting for you. Also please reconsider updating your use of JetStream to use the new Consumer apis  - see https://github.com/nats-io/nats.deno/blob/main/jetstream.md#processing-messages
