### ISSUE TITLE
NATS wsconnect Client parser ERROR

### ISSUE THREAD

**Issue by timcash** [nats-io/nats.js#61]
### Observed behavior

I get the following error from nats-server

[68341] 2024/09/12 10:11:30.513836 [ERR] 127.0.0.1:60237 - cid:9 - Client parser ERROR, state=0, i=0: proto='"\x16\x03\x01\x06\xb4\x01\x00\x06\xb0\x03\x03\xcfWU\xfe\xde#\xf2\xfc\xc1\xc0\x02t\x04.i\x8cK-I\x16\xbb"...'

### Expected behavior

A successful connection. When connecting from node instead of the browser the connection works.

### Server and client version

nats-server Version:  2.10.18
"@nats-io/nats-core": "^3.0.0-27",
"@nats-io/transport-node": "^3.0.0-12",

### Host environment

mac-os

### Steps to reproduce

using this code in browser with react

```typescript
    import * as nats_core from "@nats-io/nats-core";

    useEffect(() => {

        async function connect_to_nats() {
            const servers = { servers: "0.0.0.0:4222" }
            try {
                const nc = await nats_core.wsconnect(servers);
                console.log(`connected to ${nc.getServer()}`);
                // this promise indicates the client closed
                const done = nc.closed();
                // do something with the connection

                // close the connection
                await nc.close();
                // check if the close was OK
                const err = await done;
                if (err) {
                    console.log(`error closing:`, err);
                }
            } catch (_err) {
                console.log(`error connecting to ${JSON.stringify(servers)}`);
            }
        }

        connect_to_nats();
 ```

**Comment by aricart** [comment]
The port for ws is not 4222, but rather what you config on the server for websocket. Also the client will want a full ws/s://url - (the docs in the nats.js site are not fully accommodating for websocket, so you may want to peek at https://github.com/nats-io/nats.ws?tab=readme-ov-file#connection-options-specific-to-natsws

**Comment by aricart** [comment]
Also for your server config you'll need something like:

```
port: 4222
websocket: {
  port: 9222
  no_tls: true
  compression: true
}
```
