### ISSUE TITLE
Support for Microservices

### ISSUE THREAD

**Issue by philipgen** [nats-io/nats.js#612]
### Proposed change

Is there any support for using microservices?

Such as: https://github.com/nats-io/nats.go/blob/main/micro/README.md

### Use case

Would like to implement microservices on our client which will be using nats.js/ws

**Comment by ripienaar** [comment]
https://github.com/nats-io/nats.deno/blob/main/services.md

**Comment by philipgen** [comment]
Hi @ripienaar thanks for the response.
Our client is set to be a mobile client. I managed to make requests using nats.ws
Deno is more a server base code. Would it be possible to use it in our mobile client?

**Comment by Jarema** [comment]
@philipgen All js-related clients share the same API, they only differ in transport layer.
You should be able to use the service API without any issues.

**Comment by philipgen** [comment]
Thank you for your responses! Effectively, by using the service API it worked fine.

**Comment by aricart** [comment]
And the doc from the main page in the nats.js points you there as well:

https://github.com/nats-io/nats.js?tab=readme-ov-file#service-api
