### ISSUE TITLE
Client loosing connection consistently

### ISSUE THREAD

**Issue by gitgkk** [nats-io/nats.js#621]
### Observed behavior

The client loses connection after about one hour of inactivity.

### Expected behavior

The client should never lose connection.

### Server and client version

V2.10.14
![nats-version](https://github.com/nats-io/nats.js/assets/22524880/f0d2f117-f76a-412d-b4f8-880b3a620dbf)

### Host environment

Ubuntu on Standard B2s (2 vcpus, 4 GiB memory, x64) (Azure)
"publisher": "canonical",
"offer": "0001-com-ubuntu-server-focal",
"sku": "20_04-lts-gen2",
"version": "latest",
"exactVersion": "20.04.202308310"

### Steps to reproduce

Run the server with desired configuration. Leave it idle for one hour or so. The client starts printing "nats: client is attempting to reconnect" as we have configured for unlimited connection attempts.
[nats-server-service-logs(3).txt](https://github.com/nats-io/nats.js/files/15295099/nats-server-service-logs.3.txt)
[ubuntu-stage-server-nats-log.txt](https://github.com/nats-io/nats.js/files/15295102/ubuntu-stage-server-nats-log.txt)

The question was also posted on stackoverflow https://stackoverflow.com/questions/78392442/how-to-avoid-nats-stale-connection-error-on-node-js This was the result with nats-ts, which has since been replaced with nats-js as ts is obsolete.

Thanks for the help in debugging the issue.

**Comment by aricart** [comment]
@gitgkk a few things:

From the logs, it looks like the client is trying to reconnect (see your client logs) which is all that is promised. Disconnects are expected as networks are not reliable... 

Now looking at your logs:

You clients cannot keep up - and are getting slow consumered. It also looks like something else (not a nats client) is attempting to connect to your server (that is all "Client parser ERROR" you see in your server logs.

The server is printing "Readloop" processing times of minutes (which I have never seen) 

Can you share your server configuration?

Are you running behind some load balancer or Kubernetes or something.  I see you have a mix of localhost and remote clients and they all suffer from the same - Also your payloads as printed in the log are possibly not right - you should split your messages and reassemble.

**Comment by aricart** [comment]
Also - how big are your payloads - and why are they that big?

**Comment by wallyqs** [comment]
@gitgkk in the logs it says that you are running with nats-server v2.1.8? were you able to see the same issue on v2.10.14? from the external ssh connection attempts into the port, it looks like it is a public endpoint that does not have auth and maybe in front of a load balancer?

**Comment by aricart** [comment]
@wallyqs at the top he listed V2.10.14

**Comment by wallyqs** [comment]
@aricart in the logs shared this is found
```
[2446] 2024/01/23 12:56:02.109035 [INF] Starting nats-server version 2.1.8
[2446] 2024/01/23 12:56:02.109062 [INF] Git commit [c0b574f]
```

**Comment by aricart** [comment]
hmmm -  I think there's some weird configuration here and coupled with the payloads and the slow consumers there an environmental thing going on.

**Comment by aricart** [comment]
@gitgkk If you have more information on this please feel free to reopen - I believe this is an environment issue.
