### ISSUE TITLE
NatsError: TIMEOUT but message is published into stream

### ISSUE THREAD

**Issue by ludovit-ubrezi** [nats-io/nats.js#628]
### Observed behavior

Message return TIMEOUT every single time BUT i can see that message was published into designated queue

```
catch NatsError: TIMEOUT
    at NatsError.errorForCode (/*******/node_modules/nats/lib/nats-base-client/core.js:142:16)
    at timeout (/*******/node_modules/nats/lib/nats-base-client/util.js:57:48)
    at new RequestOne (/*******/node_modules/nats/lib/nats-base-client/request.js:104:41)
    at NatsConnectionImpl.request (/*******/node_modules/nats/lib/nats-base-client/nats.js:366:23)
    at JetStreamClientImpl.<anonymous> (/*******/node_modules/nats/lib/jetstream/jsclient.js:143:39)
    at Generator.next (<anonymous>)
    at /*******/node_modules/nats/lib/jetstream/jsclient.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/*******/node_modules/nats/lib/jetstream/jsclient.js:18:12)
    at JetStreamClientImpl.publish (/*******/node_modules/nats/lib/jetstream/jsclient.js:103:16) {
  code: 'TIMEOUT',
  chainedError: undefined
} 
```

This is Stream config

```
Options:

             Retention: Limits
       Acknowledgments: false
        Discard Policy: Old
      Duplicate Window: 20.00s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: 10,000,000
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 30m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited
```

Message from debug: true

`< HPUB core.scheduler.schedule _INBOX.7SYNRWFM2IOM80EOBQOO3A.7SYNRWFM2IOM80EOBQOOE0 0 116␍␊{"id":795370768 ->  ...reducted json }␍␊`

Console log from 
 ```
   static errorForCode(code, chainedError) {
        const m = Messages.getMessage(code);
        console.log("NatsError extends Error", m, code, chainedError);
        return new NatsError(m, code, chainedError);
    }
    
log ->  NatsError extends Error CANCELLED CANCELLED
```

### Expected behavior

Should not throw timeout because i can clearly see that message is in stream. 
Problem is that when it throws timeout error i need to NACK consumed message because I am "not sure" that message was pushed without errors.
Which eventually start duplicating messages, because message is sent into stream and consumed message is going into NACK state.

### Server and client version

**Version**:  2.10.14
**Library**: "nats": "^2.26.0"

### Host environment

**Node**: 18.19.0
CPU: Apple M1 Pro
Docker: [nats:latest]

**Comment by aricart** [comment]
I think I see the issue, you turned acknowledgements off for the stream?
Trying...

**Comment by aricart** [comment]
Correct - you cannot use js.publish() when you disable to the streams ability to ack (no_ack: true) - in that case, you should simply use `nc.publish(subject)` - which doesn't wait for acknowledgment from the server that the message was added to the stream.

**Comment by ludovit-ubrezi** [comment]
Thank you, was changing Consumer to NoAck as we changed Stream to Retention: Limits from WorkQueue, but changed this value what you mentioned as well to false as ""bystander"

**Comment by ludovit-ubrezi** [comment]
@aricart Hi i do not want to open new issue. But we got timeout also for ackAck() function.

I can see that default is 1 second but at the scale of processing 100k messages in 10 second it starts doing nasty things like gives us timeouts.

Publishing is doing fine when we added 10 second. But why there is no any option and in node modules there is hardcoded value 1000ms
 ```
   ackAck() {
        return __awaiter(this, void 0, void 0, function* () {
            var _a;
            const d = (0, mod_1.deferred)();
            if (!this.didAck) {
                this.didAck = true;
                if (this.msg.reply) {
                    const mi = this.msg;
                    const proto = mi.publisher;
                    const trace = !(((_a = proto.options) === null || _a === void 0 ? void 0 : _a.noAsyncTraces) || false);
                    const r = new request_1.RequestOne(proto.muxSubscriptions, this.msg.reply, {
                        timeout: 1000,
                    }, trace);
```

**Comment by aricart** [comment]
The bug there is the timeout should be from js option
