### ISSUE TITLE
"http://::ffff:35.234.43.228" cannot be parsed as a URL.

### ISSUE THREAD

**Issue by libkakashi** [nats-io/nats.js#635]
### Observed behavior

My DNS is apparently resolving connect.ngs.global to ::ffff:35.234.43.228. It is a valid IPv6 address that maps to an IPv4 address. However, while trying to connect to it I get the "http://::ffff:35.234.43.228" cannot be parsed as a URL." error.

### Expected behavior

I should be able to connect to that ip.

### Server and client version

nats (the npm package) version: ^2.28.0

### Steps to reproduce

I was just running this simple code (with nats server hosted on Synadia):

```ts
const getNatsClient = async () => {
  const natsGlobalThis = globalThis as {
    nc?: NatsConnection;
  };
  const release = await acquire('nats-connection');

  try {
    if (!natsGlobalThis.nc) {
      const authenticator = credsAuthenticator(
        new TextEncoder().encode(getNatsCreds())
      );
      natsGlobalThis.nc = await connect({
        servers: 'connect.ngs.global',
        authenticator,
      });
    }
  } finally {
    release();
  }
  return natsGlobalThis.nc;
};
```

**Comment by libkakashi** [comment]
I think it's this code over here that's causing it:

```
// node_modules/.pnpm/nats@2.28.0/node_modules/nats/lib/nats-base-client/servers.js:142:23
function isIPV4OrHostname(hp) {
  if (hp.indexOf(".") !== -1) {
    return true;
  }
  if (hp.indexOf("[") !== -1 || hp.indexOf("::") !== -1) {
    return false;
  }
  // if we have a plain hostname or host:port
  if (hp.split(":").length <= 2) {
    return true;
  }
  return false;
}
function isIPV6(hp) {
  return !isIPV4OrHostname(hp);
}
```
The `isIPV4OrHostname` implementation is wrong. Moving the first if statement down like this works:

```ts
function isIPV4OrHostname(hp) {
  if (hp.indexOf("[") !== -1 || hp.indexOf("::") !== -1) {
    return false;
  }
  // if we have a plain hostname or host:port
  if (hp.split(":").length <= 2) {
    return true;
  }
  if (hp.indexOf(".") !== -1) {
    return true;
  }
  return false;
}
```

**Comment by aricart** [comment]
The nats.js client doesn't support `http` protocol. Are you looking for the websocket client? in that case the protocol would be `wss://`

**Comment by aricart** [comment]
Can you post your redacted connection options?

**Comment by aricart** [comment]
For some reason I am not getting any IPv6s on the resolution. Your change looks reasonable.

**Comment by aricart** [comment]
For now can you set the option `resolve: false` to disable resolution. I will put the fix on the new branch.

**Comment by aricart** [comment]
Thank you @libkakashi
