### ISSUE TITLE
Timed out connections leak a socket/connection handle

### ISSUE THREAD

**Issue by cmidgley** [nats-io/nats.js#64]
### Observed behavior

When a connection takes more time to establish than the connection timeout, it loses a connection handle (socket).  

I believe this is caused by a `Promise.race` that awaits both a timer and a connection attempt.  It appears that when the timer expires, the code ignores the connection, yet the connection may still complete and needs to be closed.  See [`core/src/protocol.ts`](https://github.com/nats-io/nats.js/blob/61cb880def0451a46e718f95636d5847a7894e28/core/src/protocol.ts#L553-L555).

### Expected behavior

To finish waiting on the promise and close the established handle if it is established after a timeout.

### Server and client version

Server: any (client-side issue)
Client: 3.0.0-27

### Host environment

Confirmed on Node and my custom port of `nats.js` to Moddable XS, based on `@jsr/nats-io__nats-core`

### Steps to reproduce

My use is all on `ws_transport` but I believe this issue exists for any connection.  To reproduce just set a very short timeout (though in the real world, a busy server or slow name resolution can induce this):

```js
await nats_core.wsconnect({ servers: natsServer, timeout: 5 });
```

This will throw that the connection failed, however there will now be a lost network resource.

**Comment by aricart** [comment]
Thiking about possibly implementing `using` https://www.totaltypescript.com/typescript-5-2-new-keyword-using - keeping this until I verify.

**Comment by aricart** [comment]
So when it gets discarded, it ultimately ends up here:
[      await this.transport.close(err);
](https://github.com/nats-io/nats.js/blob/61cb880def0451a46e718f95636d5847a7894e28/core/src/protocol.ts#L586)


Which will close the current transport - in the case of the websocket transport, which will call close on the websocket.
