### ISSUE TITLE
update https://deno.land/x/nats

### ISSUE THREAD

**Issue by gedw99** [nats-io/nats.js#68]
### Proposed change

point to nats.js repo ?

currently it points to nats deno repo: https://deno.land/x/nats@v1.28.2

### Use case

integration with deno 

deno v2 looks really solid now.

**Comment by aricart** [comment]
The current repo for deno is nats.deno - this version here is yet to be released. Possibly the deno URL mechanism is not necessary since there's jsr now (which is what this repo is using).
