### ISSUE TITLE
OrderedConsumerOptions.filterSubjects should be OrderedConsumerOptions.filter_subjects

### ISSUE THREAD

**Issue by Zambito1** [nats-io/nats.js#85]
### Observed behavior

This is the only field on the object that does not use snake case. It also does not match the nearly identical ConsumerConfig object, which has a field named `filter_subjects` as well as `filter_subject`. I switched from using the Jetstream Manager API to the Jetstream Client API, and this difference tripped me up, as my undefined `filterSubjects` field led to my filter being ignored.

### Expected behavior

Consistent casing

### Server and client version

Library version v1.27.0

### Host environment

N/A

### Steps to reproduce

N/A

**Comment by aricart** [comment]
@Zambito1 this was fixed https://github.com/nats-io/nats.js/blob/8ff2742864e3af38b4980747668fe159d7133f82/jetstream/src/types.ts#L621
