### ISSUE TITLE
`ErrorCode.ConnectionClosed` should still allow the client to reconnect

### ISSUE THREAD

**Issue by atbe** [nats-io/nats.js#89]
### Proposed change

When the NATS server closes the connection, the client should still attempt to reconnect if we have the connection connect options:

```
    const nats = await connect({
      ...
      reconnect: true,
      maxReconnectAttempts: -1,
      token,
      ...
    });
```

**I propose that clients always attempt to reconnect unless the client explicitly calls `.close()`.**

---

I am running the latest JS client, and here's the sequence of events that occur which terminate my client without any chance of reconnecting:

```
[X4Z6Kz6LFdFh6KbW5zDFX|WorkerClientImpl.#sendHeartbeat]: 2024-10-18T17:09:42.234Z 0 Beginning heartbeat -- getting system info  {
  "requestId": "0FEwAkfw",
  "instanceId": "4YDVV3FYvciRVsjdRr8ry",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
< PUB instance.heartbeat kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.WIZC2DYRFDYXPHFVTX8AA5.WIZC2DYRFDYXPHFVTX8CGD 96␍␊{"params":{"workerId":"X4Z6Kz6LFdFh6KbW5zDFX","instanceId":"4YDVV3FYvciRVsjdRr8ry","info":null}}␍␊
> HMSG kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.WIZC2DYRFDYXPHFVTX8AA5.WIZC2DYRFDYXPHFVTX8CGD 1 16 16␍␊NATS/1.0 503␍␊␍␊␍␊
[X4Z6Kz6LFdFh6KbW5zDFX]: 2024-10-18T17:09:42.240Z 3 Failed to send heartbeat: NatsError: 503  {
  "instanceId": "4YDVV3FYvciRVsjdRr8ry",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
> HMSG kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.WIZC2DYRFDYXPHFVTX8C45 5 75 75␍␊NATS/1.0 100 Idle Heartbeat␍␊Nats-Last-Consumer: 1␍␊Nats-Last-Stream: 3␍␊␍␊␍␊
> -ERR 'User Authentication Expired'␍␊
> INFO {"server_id":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","server_name":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","version":"2.10.21","proto":1,"git_commit":"d3a8868","go":"go1.22.7","host":"0.0.0.0","port":9222,"headers":true,"auth_required":true,"max_payload":1048576,"jetstream":true,"client_id":289,"client_ip":"192.168.65.1","xkey":"XAKOYKHBGJB4CZC5QDASQLBF4XED5AKOUJPRR524JW77OWCG7IUW3VLG"} ␍␊
< CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"auth_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJzdWIiOiJYNFo2S3o2TEZkRmg2S2JXNXpERlgiLCJuYXRzIjp7InVzZXJfbmtleSI6IlVDVVhNQVVHVkc1NU5LRk1TRkZOWkhJTlJWV0hHTldJNTZKN1BERktUTjNZS0pLQTRYMlVHWVRQIiwic2VydmVyX2lkIjp7ImlkIjoia3V6Y28tYXV0aC1zZXJ2ZXItMCJ9LCJjbGllbnRfaW5mbyI6eyJuYW1lIjoiS3V6Y28gV29ya2VyIiwid29ya2VyX2lkIjoiWDRaNkt6NkxGZEZoNktiVzV6REZYIiwidGVhbV9pZCI6IllodlphS196Yml6Yy1JS3ozTFFhayJ9LCJ2ZXJzaW9uIjoyfSwiYXVkIjoiTkFUUyIsImp0aSI6IlNhYkh5RHdEUkFYNTdUUmlRY29iQXNDaXZpR0kxY2VCN1lsVEZQaU9ZeDFhOGNOaDFCWVRVVytyeW0xSnU3aGhBNkZuaDQ4cG4zSVFONjlUZTNPbFl3PT0iLCJpYXQiOjE3MjkyNzEzMjIsImlzcyI6IkFEQ0dMSVBYNTNXVEZJRFA0STROUlZJQU5STzMyUjZUTE9LTEY2V0o3V1g1TUFRRTdHUklXS1BMIiwibmFtZSI6Im5hdHNfYXV0aF9jYWxsb3V0IiwiZXhwIjoxNzI5MjcxMzgyfQ._d7mkU9K1viKWXSEcFjC6iEmUUwm4Lv-bmfo0-3MDGZHET6XFgNAN6n9DZ1JJ0uvPfQE-s3AYGaJIVSqsgw1Ag","name":"Worker X4Z6Kz6LFdFh6KbW5zDFX","lang":"nats.ws","version":"3.0.0-27","headers":true}␍␊
< PING␍␊
[X4Z6Kz6LFdFh6KbW5zDFX|WorkerClientImpl.#sendHeartbeat]: 2024-10-18T17:09:45.231Z 0 Beginning heartbeat -- getting system info  {
  "requestId": "wQbJc12o",
  "instanceId": "4YDVV3FYvciRVsjdRr8ry",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
> -ERR 'Authorization Violation'␍␊
> INFO {"server_id":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","server_name":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","version":"2.10.21","proto":1,"git_commit":"d3a8868","go":"go1.22.7","host":"0.0.0.0","port":9222,"headers":true,"auth_required":true,"max_payload":1048576,"jetstream":true,"client_id":290,"client_ip":"192.168.65.1","xkey":"XAKOYKHBGJB4CZC5QDASQLBF4XED5AKOUJPRR524JW77OWCG7IUW3VLG"} ␍␊
< CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"auth_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJzdWIiOiJYNFo2S3o2TEZkRmg2S2JXNXpERlgiLCJuYXRzIjp7InVzZXJfbmtleSI6IlVDVVhNQVVHVkc1NU5LRk1TRkZOWkhJTlJWV0hHTldJNTZKN1BERktUTjNZS0pLQTRYMlVHWVRQIiwic2VydmVyX2lkIjp7ImlkIjoia3V6Y28tYXV0aC1zZXJ2ZXItMCJ9LCJjbGllbnRfaW5mbyI6eyJuYW1lIjoiS3V6Y28gV29ya2VyIiwid29ya2VyX2lkIjoiWDRaNkt6NkxGZEZoNktiVzV6REZYIiwidGVhbV9pZCI6IllodlphS196Yml6Yy1JS3ozTFFhayJ9LCJ2ZXJzaW9uIjoyfSwiYXVkIjoiTkFUUyIsImp0aSI6IlNhYkh5RHdEUkFYNTdUUmlRY29iQXNDaXZpR0kxY2VCN1lsVEZQaU9ZeDFhOGNOaDFCWVRVVytyeW0xSnU3aGhBNkZuaDQ4cG4zSVFONjlUZTNPbFl3PT0iLCJpYXQiOjE3MjkyNzEzMjIsImlzcyI6IkFEQ0dMSVBYNTNXVEZJRFA0STROUlZJQU5STzMyUjZUTE9LTEY2V0o3V1g1TUFRRTdHUklXS1BMIiwibmFtZSI6Im5hdHNfYXV0aF9jYWxsb3V0IiwiZXhwIjoxNzI5MjcxMzgyfQ._d7mkU9K1viKWXSEcFjC6iEmUUwm4Lv-bmfo0-3MDGZHET6XFgNAN6n9DZ1JJ0uvPfQE-s3AYGaJIVSqsgw1Ag","name":"Worker X4Z6Kz6LFdFh6KbW5zDFX","lang":"nats.ws","version":"3.0.0-27","headers":true}␍␊
< PING␍␊
> -ERR 'Authorization Violation'␍␊
[kuzco-cli|createWorkerClient]: 2024-10-18T17:09:47.329Z 4 NATS connection closed, worker exiting...  {
  "requestId": "NAPa9z5m"
}
```

[This code seems relevant.](https://github.com/nats-io/nats.js/blob/552fb20e86620ad52195d072d9797cf850c4ad9f/core/src/protocol.ts#L537)

### Use case

When a client is connecting and is authenticated using the `auth_callback`, and the `auth_callback` subscriber stops responding to messages, NATS terminates the client connection.

This makes it hard to self-heal our client connections when the `auth_callback` subscriber comes back online and is able to start validating JWTs again.

**Comment by atbe** [comment]
Notice this log is from my app:

```
[kuzco-cli|createWorkerClient]: 2024-10-18T17:09:47.329Z 4 NATS connection closed, worker exiting...  {
  "requestId": "NAPa9z5m"
}
```

The reason why we're exiting today is because the NATS connection never recovers, and so we must exit and restart as the only way of reestablishing the NATS client connection.

**Comment by atbe** [comment]
In the example on the OP, the JWT expiration of the `auth_token` was 30 seconds.

I've expanded it to 2 weeks, and still see the same issue:

```
[X4Z6Kz6LFdFh6KbW5zDFX|WorkerClientImpl.#sendHeartbeat]: 2024-10-18T17:14:57.053Z 0 Beginning heartbeat -- getting system info  {
  "requestId": "aNMWaIqr",
  "instanceId": "DS5DrxeM6GjFsLnLHoN6f",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
< PUB instance.heartbeat kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.5JTZAXI0O3YOX9XH7QOEB8.5JTZAXI0O3YOX9XH7QOMAQ 96␍␊{"params":{"workerId":"X4Z6Kz6LFdFh6KbW5zDFX","instanceId":"DS5DrxeM6GjFsLnLHoN6f","info":null}}␍␊
> HMSG kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.5JTZAXI0O3YOX9XH7QOEB8.5JTZAXI0O3YOX9XH7QOMAQ 1 16 16␍␊NATS/1.0 503␍␊␍␊␍␊
[X4Z6Kz6LFdFh6KbW5zDFX]: 2024-10-18T17:14:57.065Z 3 Failed to send heartbeat: NatsError: 503  {
  "instanceId": "DS5DrxeM6GjFsLnLHoN6f",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
> HMSG kuzco-worker.X4Z6Kz6LFdFh6KbW5zDFX._INBOX.5JTZAXI0O3YOX9XH7QOLES 6 75 75␍␊NATS/1.0 100 Idle Heartbeat␍␊Nats-Last-Consumer: 1␍␊Nats-Last-Stream: 3␍␊␍␊␍␊
> -ERR 'User Authentication Expired'␍␊
> INFO {"server_id":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","server_name":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","version":"2.10.21","proto":1,"git_commit":"d3a8868","go":"go1.22.7","host":"0.0.0.0","port":9222,"headers":true,"auth_required":true,"max_payload":1048576,"jetstream":true,"client_id":297,"client_ip":"192.168.65.1","xkey":"XAKOYKHBGJB4CZC5QDASQLBF4XED5AKOUJPRR524JW77OWCG7IUW3VLG"} ␍␊
< CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"auth_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJzdWIiOiJYNFo2S3o2TEZkRmg2S2JXNXpERlgiLCJuYXRzIjp7InVzZXJfbmtleSI6IlVDWkhEQVNPWEhDVTIyQ0U1WlpFTDVXWVhHRDJCSEE3V1hVNk9RUVk0U1Q3TUFWS0dPWjdMSlZYIiwic2VydmVyX2lkIjp7ImlkIjoia3V6Y28tYXV0aC1zZXJ2ZXItMCJ9LCJjbGllbnRfaW5mbyI6eyJuYW1lIjoiS3V6Y28gV29ya2VyIiwid29ya2VyX2lkIjoiWDRaNkt6NkxGZEZoNktiVzV6REZYIiwidGVhbV9pZCI6IllodlphS196Yml6Yy1JS3ozTFFhayJ9LCJ2ZXJzaW9uIjoyfSwiYXVkIjoiTkFUUyIsImp0aSI6Inkwc2xEVVBrQWsybmtHNGs4N0kydExMUGRWRlJQM3k4Y1dmUk0wOFVXbCthbE9udm9YR2FhTHNrZ01ucmwvbS9XK0J4Vm16ejhiN2IvNEwwTEEwVFBBPT0iLCJpYXQiOjE3MjkyNzE2MDksImlzcyI6IkFEQ0dMSVBYNTNXVEZJRFA0STROUlZJQU5STzMyUjZUTE9LTEY2V0o3V1g1TUFRRTdHUklXS1BMIiwibmFtZSI6Im5hdHNfYXV0aF9jYWxsb3V0IiwiZXhwIjoxNzMwNDgxMjA5fQ.g_lRLm8a7o3jDyTGt0neYkH3Z6sn0SRqq1X1jDYrosCxs4Znauli9idnE6VIpbTwfuEialb8BqcWII9OgLndBw","name":"Worker X4Z6Kz6LFdFh6KbW5zDFX","lang":"nats.ws","version":"3.0.0-27","headers":true}␍␊
< PING␍␊
[X4Z6Kz6LFdFh6KbW5zDFX|WorkerClientImpl.#sendHeartbeat]: 2024-10-18T17:15:00.051Z 0 Beginning heartbeat -- getting system info  {
  "requestId": "aaZ2jfMI",
  "instanceId": "DS5DrxeM6GjFsLnLHoN6f",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}

> -ERR 'Authorization Violation'␍␊
> INFO {"server_id":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","server_name":"NA6JB4H7YXBIUWU4HSPZPEM7INIUQF5G72YGDOED6DLPYOK6DKXXDONT","version":"2.10.21","proto":1,"git_commit":"d3a8868","go":"go1.22.7","host":"0.0.0.0","port":9222,"headers":true,"auth_required":true,"max_payload":1048576,"jetstream":true,"client_id":298,"client_ip":"192.168.65.1","xkey":"XAKOYKHBGJB4CZC5QDASQLBF4XED5AKOUJPRR524JW77OWCG7IUW3VLG"} ␍␊
< CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"auth_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJzdWIiOiJYNFo2S3o2TEZkRmg2S2JXNXpERlgiLCJuYXRzIjp7InVzZXJfbmtleSI6IlVDWkhEQVNPWEhDVTIyQ0U1WlpFTDVXWVhHRDJCSEE3V1hVNk9RUVk0U1Q3TUFWS0dPWjdMSlZYIiwic2VydmVyX2lkIjp7ImlkIjoia3V6Y28tYXV0aC1zZXJ2ZXItMCJ9LCJjbGllbnRfaW5mbyI6eyJuYW1lIjoiS3V6Y28gV29ya2VyIiwid29ya2VyX2lkIjoiWDRaNkt6NkxGZEZoNktiVzV6REZYIiwidGVhbV9pZCI6IllodlphS196Yml6Yy1JS3ozTFFhayJ9LCJ2ZXJzaW9uIjoyfSwiYXVkIjoiTkFUUyIsImp0aSI6Inkwc2xEVVBrQWsybmtHNGs4N0kydExMUGRWRlJQM3k4Y1dmUk0wOFVXbCthbE9udm9YR2FhTHNrZ01ucmwvbS9XK0J4Vm16ejhiN2IvNEwwTEEwVFBBPT0iLCJpYXQiOjE3MjkyNzE2MDksImlzcyI6IkFEQ0dMSVBYNTNXVEZJRFA0STROUlZJQU5STzMyUjZUTE9LTEY2V0o3V1g1TUFRRTdHUklXS1BMIiwibmFtZSI6Im5hdHNfYXV0aF9jYWxsb3V0IiwiZXhwIjoxNzMwNDgxMjA5fQ.g_lRLm8a7o3jDyTGt0neYkH3Z6sn0SRqq1X1jDYrosCxs4Znauli9idnE6VIpbTwfuEialb8BqcWII9OgLndBw","name":"Worker X4Z6Kz6LFdFh6KbW5zDFX","lang":"nats.ws","version":"3.0.0-27","headers":true}␍␊
< PING␍␊
[X4Z6Kz6LFdFh6KbW5zDFX|WorkerClientImpl.#sendHeartbeat]: 2024-10-18T17:15:03.058Z 0 Beginning heartbeat -- getting system info  {
  "requestId": "cJXBlYiy",
  "instanceId": "DS5DrxeM6GjFsLnLHoN6f",
  "workerId": "X4Z6Kz6LFdFh6KbW5zDFX"
}
> -ERR 'Authorization Violation'␍␊
[kuzco-cli|createWorkerClient]: 2024-10-18T17:15:03.918Z 4 NATS connection closed, worker exiting...  {
  "requestId": "OVMCSSlX"
}
```

**Comment by aricart** [comment]
The reason why it is failing is the `-ERR 'Authorization Violation` - by default it will try to connect 2 times with this error and then give up, if you don't want that behavior, you can disable it by providing the connect option `ignoreAuthErrorAbort`:

https://github.com/nats-io/nats.js/blob/48eec734a674c6363d34a9f6d5af64554c720ade/core/src/core.ts#L1048

**Comment by atbe** [comment]
Perhaps there should be an additional check here rather than assume that things are "blowing up" ? https://github.com/nats-io/nats.js/blob/552fb20e86620ad52195d072d9797cf850c4ad9f/core/src/protocol.ts#L841

Because authentication failures _can be recovered_ eventually, and I believe it should be up to the client to determine if they should actually halt reconnection attempts.

Notice that I specified `maxReconnectAttempts` as -1, so I'd expect the client to keep trying to reconnect forever.

**Comment by atbe** [comment]
> The reason why it is failing is the `-ERR 'Authorization Violation` - by default it will try to connect 2 times with this error and then give up, if you don't want that behavior, you can disable it by providing the connect option `ignoreAuthErrorAbort`:
> 
> https://github.com/nats-io/nats.js/blob/48eec734a674c6363d34a9f6d5af64554c720ade/core/src/core.ts#L1048

aha, thank you very much @aricart !

**Comment by aricart** [comment]
The auth errors are treated specially - if your client has stale connections, you'll never know that happened. unless you are aware that this is something you'll handle.

**Comment by atbe** [comment]
> The auth errors are treated specially - if your client has stale credentials, you'll never know that happened. unless you are aware that this is something you'll handle.

yes we're aware and handling it separately, so this gives me exactly what I need. Thanks again.

**Comment by aricart** [comment]
Also you can specify functions for the authenticators, so your client can read something new from disk/etc on a reconnect.

**Comment by atbe** [comment]
> Also you can specify functions for the authenticators, so your client can read something new from disk/etc on a reconnect.

Is it possible for the authenticator to use an async function? It doesn't seem like it from what I can tell @aricart

**Comment by atbe** [comment]
What I'd love to be able to do is actually have the client request a new `token` in the event that a reconnection attempt is made so that it can fetch a fresh new token, rather than me setting a long expiration time on the token that's passed to the `connect` method, or alternatively completely ignore expiration times on those tokens (worst possible scenario).

**Comment by atbe** [comment]
Ideally:

```ts
    const nats = await connect({
      servers: [NATS_URL],
      name: `Worker ${workerId}`,
      reconnect: true,
      maxReconnectAttempts: -1,
      inboxPrefix: getWorkerInboxPrefix(workerId),
      ignoreAuthErrorAbort: true,

      // instead of providing the token directly, we use the authenticator to fetch a fresh token when the current one expires,
      // or if the connection is closed and reconnected.
      // token,

      authenticator: tokenAuthenticator(async () => {
        const { token } = await trpc.workerAuth.generateAuthToken.query({
          registrationCode,
        });
        return token;
      }),
    });
```

**Comment by atbe** [comment]
any thoughts or feedback? @aricart

**Comment by aricart** [comment]
The authenticator cannot have async functions, the reason for it is that it is called in line with the handling of the server handshake and that has a time limit - so if for any reason the fetch for your credentials is slow or fails, it would hang during the handshake.

**Comment by aricart** [comment]
if you are using functions, it is reasonable to pre-update these at some interval and the client can cache, ie have a process that pulls credentials every hour (or slightly less than what the expiration would be, and have them ready for the client to read.

**Comment by atbe** [comment]
> if you are using functions, it is reasonable to pre-update what your function is reading at some interval and the client can cache, ie have a process that pulls credentials every hour (or slightly less than what the expiration would be, and have them ready for the client to read.

ya, I thought of this as well and will likely go with this approach

---

> The authenticator cannot have async functions, the reason for it is that it is called in line with the handling of the server handshake and that has a time limit - so if for any reason the fetch for your credentials is slow or fails, it would hang during the handshake.

I think that async authenticator functions should be considered given that the `auth_timeout` is set arbitrarily by the server owner, and could be high enough to allow for async methods on the client (unless the timeout you're referring to is actually different from the `auth_timeout`).

@aricart

**Comment by aricart** [comment]
I don't agree. This could become an unexpected delay on connections if all the sudden the underlying auth mechanism fail

**Comment by aricart** [comment]
If you are dealing with credentials where you are rotating often, etc, possibly an auth-callout would be a better alternative, the other choice is not to have too aggressive expirations... We have discussed for a while the idea of having a re-auth protocol, which would require the client to re-authenticate. That possibly would have better timing, and allow for the client to re-collect stuff before getting disconnected. Not there yet.

**Comment by atbe** [comment]
> I don't agree. This could become an unexpected delay on connections if all the sudden the underlying auth mechanism fail

@aricart sure that's true

But when you consider this suggestion:

> if you are using functions, it is reasonable to pre-update what your function is reading at some interval and the client can cache, ie have a process that pulls credentials every hour (or slightly less than what the expiration would be, and have them ready for the client to read.

It feels like a poor design to require the authenticator to read some local state that is updated by some other asynchronous methods, considering that that could just be done at auth time.

I prefer to have more control than to be forced to use synchronous methods just to eliminate unexpected delays, which should be the responsibility of the consumer of the library rather than the library itself.

---

I do think this should be reconsidered, and its very standard practice to simply allow _either_ a synchronous or asynchronous callback for this sort of thing, but I respect the decision.

**Comment by atbe** [comment]
I did some quick research and the approach you're suggesting about pre-updating the data that the function is reading seems to be a common mechanism.

[I found this example from the Kafka library, for example, which does exactly that.](https://kafka.js.org/docs/configuration#oauthbearer-example)
