### ISSUE TITLE
rejectUnauthorized is not documented for TlsOptions

### ISSUE THREAD

**Issue by mriedem** [nats-io/nats.js#94]
### Observed behavior

I was looking at some app code that uses this library and there was a pass through environment variable for the `tls.rejectUnauthorized` config and I thought it was a mistake because it's not documented [here](https://nats-io.github.io/nats.js/core/interfaces/TlsOptions.html) or [here](https://github.com/nats-io/nats.js/blob/main/core/README.md#tlsoptions), but I see it referenced in the code [here](https://github.com/nats-io/nats.js/blob/54c5dc81b75f6b90d06e6ffc863e56260f3d18a7/transport-node/src/node_transport.ts#L311), so I guess it's a valid option in the `TlsOptions` config?

### Expected behavior

Document the `rejectUnauthorized` TLS config option.

### Server and client version

Server: using `nats:2.9.18-alpine` docker image

Client: `@nats-io/transport-node@3.0.0-12`

### Host environment

n/a

### Steps to reproduce

n/a

**Comment by aricart** [comment]
@mriedem looking back at that property, it is a node-specific option intended to support the `secureEvent` and provide a bypass for CA verification. Instead, I belive that clients that want to bypass those checks should really be using `NODE_TLS_REJECT_UNAUTHORIZED` or using valid certs. Not quite sure how that made it in (I know I put it in), but it is possibly a bad idea, and should be removed.
