### ISSUE TITLE
KvWatchEntry does not include "CREATE" in operation enum

### ISSUE THREAD

**Issue by snoop244** [nats-io/nats.js#95]
### Observed behavior

This code: `if (e.operation === "CREATE") {...` is flagged with: "This comparison appears to be unintentional because the types '"PUT" | "DEL" | "PURGE"' and '"CREATE"' have no overlap.ts(2367)"

Where "e" is: const e: KvWatchEntry

### Expected behavior

I expect to be able to pick up the CREATE operation in my if clause. It's possible that KvEntry intentionally omits it:
```js
export interface KvEntry {
    bucket: string;
    key: string;
    value: Uint8Array;
    created: Date;
    revision: number;
    delta?: number;
    operation: "PUT" | "DEL" | "PURGE";
    length: number;
    /**
     * Convenience method to parse the entry payload as JSON. This method
     * will throw an exception if there's a parsing error;
     */
    json<T>(): T;
    /**
     * Convenience method to parse the entry payload as string. This method
     * may throw an exception if there's a conversion error
     */
    string(): string;
}
```

### Server and client version

nats-server: v2.10.20
dependencies:
    "@nats-io/jetstream": "3.0.0-15",
    "@nats-io/kv": "3.0.0-12",
    "@nats-io/nats-core": "3.0.0-30",

### Steps to reproduce

Create an if clause to test for operation on a kv.watch(). Partial code:
```js
      const watch = await kv.watch();
      (async () => {
        for await (const e of watch) {
          if (e.operation === "CREATE") {
          ... do something only if we CREATEd... like adding a new key to my client side store
         }
  }});

**Comment by aricart** [comment]
KV operations don't have a `CREATE` - marker (these markers are from the server). There's a create operation, which effectively fails the put if the key exists (there's another PUT). Entries do have a `created` property that tells when the entry was added (added could be created or updated).

And regardless, such notification while useful requires an additional strategy - the CREATE is only meaningful if the key doesn't exist. So if the watcher starts after a key is created, then this means that it wouldn't be able to handle the create, even though it has never seen it.

Now, with that said, you could have a something like a bloom filter where you can keep track of entries that exist, and then act on those. You would seed it from history, and possibly would note the revision that you last processed in case your process has to restart.

**Comment by aricart** [comment]
If the server added support for this, then obviously the clients would map it, but right now this would be a client-only feature, which is better implemented by your service.

**Comment by snoop244** [comment]
Got it. I appreciate the explanation. Very helpful.
